/*
 * Поставки FBW
 *
 * Узнать больше о поставках FBW можно в [справочном центре](https://seller.wildberries.ru/instructions/subcategory/5a8e1202-0865-45b7-acae-5d0afc7add56?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e)  В разделе описаны методы получения: - [информации для формирования поставок](https://dev.wildberries.ru/openapi/orders-fbw#tag/informationForFormingSupplies) - [информации о поставках](https://dev.wildberries.ru/openapi/orders-fbw#tag/suppliesInformation) Вы можете создавать карточки товара в песочнице [Контента](https://dev.wildberries.ru/openapi/api-information#tag/authorization/Kategorii-tokenov), а потом использовать баркоды товаров в [песочнице](https://dev.wildberries.ru/sandbox) Поставок
 *
 * The version of the OpenAPI document: ordersfbw
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ValeryVerkhoturov.WbApiClient.OrdersFbw.Client.OpenAPIDateConverter;

namespace ValeryVerkhoturov.WbApiClient.OrdersFbw.Model
{
    /// <summary>
    /// ModelsItem
    /// </summary>
    [DataContract(Name = "models.Item")]
    public partial class ModelsItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ModelsItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsItem" /> class.
        /// </summary>
        /// <param name="quantity">Количество единиц товара  (required).</param>
        /// <param name="sku">Баркод из карточки товара (required).</param>
        public ModelsItem(int quantity = default(int), string sku = default(string))
        {
            this.Quantity = quantity;
            // to ensure "sku" is required (not null)
            if (sku == null)
            {
                throw new ArgumentNullException("sku is a required property for ModelsItem and cannot be null");
            }
            this.Sku = sku;
        }

        /// <summary>
        /// Количество единиц товара 
        /// </summary>
        /// <value>Количество единиц товара </value>
        [DataMember(Name = "quantity", IsRequired = true, EmitDefaultValue = true)]
        public int Quantity { get; set; }

        /// <summary>
        /// Баркод из карточки товара
        /// </summary>
        /// <value>Баркод из карточки товара</value>
        [DataMember(Name = "sku", IsRequired = true, EmitDefaultValue = true)]
        public string Sku { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ModelsItem {\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Quantity (int) maximum
            if (this.Quantity > (int)999999)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value less than or equal to 999999.", new[] { "Quantity" });
            }

            // Quantity (int) minimum
            if (this.Quantity < (int)1)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value greater than or equal to 1.", new[] { "Quantity" });
            }

            yield break;
        }
    }

}
