/*
Общее

В этом разделе: - [общая информация о WB API](https://dev.wildberries.ru/openapi/api-information#tag/introduction) - как [начать работу с WB API](https://dev.wildberries.ru/openapi/api-information#tag/introduction/Kak-nachat-rabotu-s-API) - как [авторизоваться](https://dev.wildberries.ru/openapi/api-information#tag/authorization) и [создавать токены](https://dev.wildberries.ru/openapi/api-information#tag/authorization/Kak-sozdat-personalnyj-bazovyj-ili-testovyj-token) - основные [статус-коды ответов](https://dev.wildberries.ru/openapi/api-information#tag/introduction/Status-kody-HTTP) - [лимиты запросов](https://dev.wildberries.ru/openapi/api-information#tag/introduction/Limity-zaprosov) - как обратиться в [поддержку](https://dev.wildberries.ru/openapi/api-information#tag/introduction/Podderzhka) С помощью методов этого раздела вы можете: - проверить [подключение к WB API](https://dev.wildberries.ru/openapi/api-information#tag/connectionCheck/operation/getPing) - получить [новости портала продавцов](https://dev.wildberries.ru/openapi/api-information#tag/newsApi/operation/getV2News) - получить [информацию о продавце](https://dev.wildberries.ru/openapi/api-information#tag/sellerInformation/operation/getV1SellerInfo) - [управлять пользователями продавца](https://dev.wildberries.ru/openapi/api-information#tag/sellerUserManagement)

API version: general
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package general

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetUsersResponseUsersInnerAccessInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsersResponseUsersInnerAccessInner{}

// GetUsersResponseUsersInnerAccessInner struct for GetUsersResponseUsersInnerAccessInner
type GetUsersResponseUsersInnerAccessInner struct {
	// Код раздела профиля продавца, к которому пользователь получит доступ: * `balance` — Просмотр баланса и вывод средств * `brands` — Управление брендами * `changeJam` — Доступ к подключению подписки **Джем**: **А/Б тесты**, отметки на фото, автозапуски видео, сравнение карточек * `discountPrice` — Изменение цен на товары, управление скидками и акциями * `finance` — Финансовая аналитика. Статистика по балансу, финансовые отчёты, история платежей * `showcase` — Управление витриной магазина * `suppliersDocuments` — Просмотр и скачивание документов по работе с площадкой * `supply` — Создание и управление поставками FBW * `questions` — Просмотр и ответы на вопросы покупателей * `pinFeedbacks` — Возможность закреплять и откреплять отзывы * `pointsForReviews` — Баллы за отзывы * `feedbacks` — Просмотр и ответы на отзывы покупателей * `oldAnalyticsReports` — Отчёты * `marketplace` — Свой склад * `brandsFlow` — Мои бренды * `copyrightComplaints` — Обращения правообладателей * `pretrialClaims` — Досудебные претензии * `sellersChat` — Чат с покупателями * `brandzone` — Бренд-зона. Публикация изменений * `brandzoneSubscribe` — Управление подпиской бренд-зоны 
	Code string `json:"code"`
	// * `true` — доступ к разделу запрещён * `false` — доступ к разделу разрешён 
	Disabled bool `json:"disabled"`
}

type _GetUsersResponseUsersInnerAccessInner GetUsersResponseUsersInnerAccessInner

// NewGetUsersResponseUsersInnerAccessInner instantiates a new GetUsersResponseUsersInnerAccessInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsersResponseUsersInnerAccessInner(code string, disabled bool) *GetUsersResponseUsersInnerAccessInner {
	this := GetUsersResponseUsersInnerAccessInner{}
	this.Code = code
	this.Disabled = disabled
	return &this
}

// NewGetUsersResponseUsersInnerAccessInnerWithDefaults instantiates a new GetUsersResponseUsersInnerAccessInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsersResponseUsersInnerAccessInnerWithDefaults() *GetUsersResponseUsersInnerAccessInner {
	this := GetUsersResponseUsersInnerAccessInner{}
	return &this
}

// GetCode returns the Code field value
func (o *GetUsersResponseUsersInnerAccessInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetUsersResponseUsersInnerAccessInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetUsersResponseUsersInnerAccessInner) SetCode(v string) {
	o.Code = v
}

// GetDisabled returns the Disabled field value
func (o *GetUsersResponseUsersInnerAccessInner) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *GetUsersResponseUsersInnerAccessInner) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *GetUsersResponseUsersInnerAccessInner) SetDisabled(v bool) {
	o.Disabled = v
}

func (o GetUsersResponseUsersInnerAccessInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsersResponseUsersInnerAccessInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["disabled"] = o.Disabled
	return toSerialize, nil
}

func (o *GetUsersResponseUsersInnerAccessInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"disabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUsersResponseUsersInnerAccessInner := _GetUsersResponseUsersInnerAccessInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetUsersResponseUsersInnerAccessInner)

	if err != nil {
		return err
	}

	*o = GetUsersResponseUsersInnerAccessInner(varGetUsersResponseUsersInnerAccessInner)

	return err
}

type NullableGetUsersResponseUsersInnerAccessInner struct {
	value *GetUsersResponseUsersInnerAccessInner
	isSet bool
}

func (v NullableGetUsersResponseUsersInnerAccessInner) Get() *GetUsersResponseUsersInnerAccessInner {
	return v.value
}

func (v *NullableGetUsersResponseUsersInnerAccessInner) Set(val *GetUsersResponseUsersInnerAccessInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsersResponseUsersInnerAccessInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsersResponseUsersInnerAccessInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsersResponseUsersInnerAccessInner(val *GetUsersResponseUsersInnerAccessInner) *NullableGetUsersResponseUsersInnerAccessInner {
	return &NullableGetUsersResponseUsersInnerAccessInner{value: val, isSet: true}
}

func (v NullableGetUsersResponseUsersInnerAccessInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsersResponseUsersInnerAccessInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


