# coding: utf-8

"""
    Работа с товарами

    С помощью методов этого раздела вы можете: - [создавать](https://dev.wildberries.ru/openapi/item-management#tag/listingItems) и [редактировать](https://dev.wildberries.ru/openapi/item-management#tag/listings) карточки товаров - получать [категории, предметы, характеристики и бренды товаров](https://dev.wildberries.ru/openapi/item-management#tag/categoriesSubcategoriesAndCharacteristics) - загружать [медиафайлы](https://dev.wildberries.ru/openapi/item-management#tag/mediaFiles) в карточки товаров - настраивать [ярлыки](https://dev.wildberries.ru/openapi/item-management#tag/labels) для поиска товаров - работать с [рекомендациями](https://dev.wildberries.ru/openapi/item-management#tag/recommendations) для товаров - устанавливать [цены и скидки](https://dev.wildberries.ru/openapi/item-management#tag/pricesAndDiscounts) - управлять [остатками товаров](https://dev.wildberries.ru/openapi/item-management#tag/sellerWarehousesInventory) и [складами](https://dev.wildberries.ru/openapi/item-management#tag/sellerWarehouses), если вы работаете по модели продаж со склада продавца Вы можете протестировать методы работы с товарами в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/itemManagement) для управления карточками товаров  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami) по **работе с товарами**

    The version of the OpenAPI document: items
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from wb_api_client.items.models.good_buffer_history import GoodBufferHistory
from typing import Optional, Set
from typing_extensions import Self


class GetV2BufferGoodsTask200ResponseData(BaseModel):
    """
    Данные ответа
    """  # noqa: E501

    upload_id: Optional[StrictInt] = Field(
        default=None, description="ID загрузки", alias="uploadID"
    )
    buffer_goods: Optional[List[GoodBufferHistory]] = Field(
        default=None, description="Информация о товарах в загрузке", alias="bufferGoods"
    )
    __properties: ClassVar[List[str]] = ["uploadID", "bufferGoods"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetV2BufferGoodsTask200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in buffer_goods (list)
        _items = []
        if self.buffer_goods:
            for _item_buffer_goods in self.buffer_goods:
                if _item_buffer_goods:
                    _items.append(_item_buffer_goods.to_dict())
            _dict["bufferGoods"] = _items
        # set to None if upload_id (nullable) is None
        # and model_fields_set contains the field
        if self.upload_id is None and "upload_id" in self.model_fields_set:
            _dict["uploadID"] = None

        # set to None if buffer_goods (nullable) is None
        # and model_fields_set contains the field
        if self.buffer_goods is None and "buffer_goods" in self.model_fields_set:
            _dict["bufferGoods"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetV2BufferGoodsTask200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "uploadID": obj.get("uploadID"),
                "bufferGoods": (
                    [GoodBufferHistory.from_dict(_item) for _item in obj["bufferGoods"]]
                    if obj.get("bufferGoods") is not None
                    else None
                ),
            }
        )
        return _obj
