/*
 * Работа с товарами
 * С помощью методов этого раздела вы можете: - [создавать](https://dev.wildberries.ru/openapi/item-management#tag/listingItems) и [редактировать](https://dev.wildberries.ru/openapi/item-management#tag/listings) карточки товаров - получать [категории, предметы, характеристики и бренды товаров](https://dev.wildberries.ru/openapi/item-management#tag/categoriesSubcategoriesAndCharacteristics) - загружать [медиафайлы](https://dev.wildberries.ru/openapi/item-management#tag/mediaFiles) в карточки товаров - настраивать [ярлыки](https://dev.wildberries.ru/openapi/item-management#tag/labels) для поиска товаров - работать с [рекомендациями](https://dev.wildberries.ru/openapi/item-management#tag/recommendations) для товаров - устанавливать [цены и скидки](https://dev.wildberries.ru/openapi/item-management#tag/pricesAndDiscounts) - управлять [остатками товаров](https://dev.wildberries.ru/openapi/item-management#tag/sellerWarehousesInventory) и [складами](https://dev.wildberries.ru/openapi/item-management#tag/sellerWarehouses), если вы работаете по модели продаж со склада продавца Вы можете протестировать методы работы с товарами в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/itemManagement) для управления карточками товаров  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami) по **работе с товарами**
 *
 * The version of the OpenAPI document: items
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.valeryverkhoturov.wbapi.items.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.valeryverkhoturov.wbapi.items.JSON;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** GoodHistory */
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.10.0")
public class GoodHistory {
  public static final String SERIALIZED_NAME_NM_I_D = "nmID";

  @SerializedName(SERIALIZED_NAME_NM_I_D)
  @jakarta.annotation.Nullable
  private Integer nmID;

  public static final String SERIALIZED_NAME_VENDOR_CODE = "vendorCode";

  @SerializedName(SERIALIZED_NAME_VENDOR_CODE)
  @jakarta.annotation.Nullable
  private String vendorCode;

  public static final String SERIALIZED_NAME_SIZE_I_D = "sizeID";

  @SerializedName(SERIALIZED_NAME_SIZE_I_D)
  @jakarta.annotation.Nullable
  private Integer sizeID;

  public static final String SERIALIZED_NAME_TECH_SIZE_NAME = "techSizeName";

  @SerializedName(SERIALIZED_NAME_TECH_SIZE_NAME)
  @jakarta.annotation.Nullable
  private String techSizeName;

  public static final String SERIALIZED_NAME_PRICE = "price";

  @SerializedName(SERIALIZED_NAME_PRICE)
  @jakarta.annotation.Nullable
  private Integer price;

  public static final String SERIALIZED_NAME_CURRENCY_ISO_CODE4217 = "currencyIsoCode4217";

  @SerializedName(SERIALIZED_NAME_CURRENCY_ISO_CODE4217)
  @jakarta.annotation.Nullable
  private String currencyIsoCode4217;

  public static final String SERIALIZED_NAME_DISCOUNT = "discount";

  @SerializedName(SERIALIZED_NAME_DISCOUNT)
  @jakarta.annotation.Nullable
  private Integer discount;

  public static final String SERIALIZED_NAME_CLUB_DISCOUNT = "clubDiscount";

  @SerializedName(SERIALIZED_NAME_CLUB_DISCOUNT)
  @jakarta.annotation.Nullable
  private Integer clubDiscount;

  public static final String SERIALIZED_NAME_STATUS = "status";

  @SerializedName(SERIALIZED_NAME_STATUS)
  @jakarta.annotation.Nullable
  private Integer status;

  public static final String SERIALIZED_NAME_ERROR_TEXT = "errorText";

  @SerializedName(SERIALIZED_NAME_ERROR_TEXT)
  @jakarta.annotation.Nullable
  private String errorText;

  public GoodHistory() {}

  public GoodHistory nmID(@jakarta.annotation.Nullable Integer nmID) {
    this.nmID = nmID;
    return this;
  }

  /**
   * Артикул WB
   *
   * @return nmID
   */
  @jakarta.annotation.Nullable
  public Integer getNmID() {
    return nmID;
  }

  public void setNmID(@jakarta.annotation.Nullable Integer nmID) {
    this.nmID = nmID;
  }

  public GoodHistory vendorCode(@jakarta.annotation.Nullable String vendorCode) {
    this.vendorCode = vendorCode;
    return this;
  }

  /**
   * Артикул продавца
   *
   * @return vendorCode
   */
  @jakarta.annotation.Nullable
  public String getVendorCode() {
    return vendorCode;
  }

  public void setVendorCode(@jakarta.annotation.Nullable String vendorCode) {
    this.vendorCode = vendorCode;
  }

  public GoodHistory sizeID(@jakarta.annotation.Nullable Integer sizeID) {
    this.sizeID = sizeID;
    return this;
  }

  /**
   * ID размера. В методах Контента это поле &#x60;chrtID&#x60;
   *
   * @return sizeID
   */
  @jakarta.annotation.Nullable
  public Integer getSizeID() {
    return sizeID;
  }

  public void setSizeID(@jakarta.annotation.Nullable Integer sizeID) {
    this.sizeID = sizeID;
  }

  public GoodHistory techSizeName(@jakarta.annotation.Nullable String techSizeName) {
    this.techSizeName = techSizeName;
    return this;
  }

  /**
   * Размер
   *
   * @return techSizeName
   */
  @jakarta.annotation.Nullable
  public String getTechSizeName() {
    return techSizeName;
  }

  public void setTechSizeName(@jakarta.annotation.Nullable String techSizeName) {
    this.techSizeName = techSizeName;
  }

  public GoodHistory price(@jakarta.annotation.Nullable Integer price) {
    this.price = price;
    return this;
  }

  /**
   * Цена
   *
   * @return price
   */
  @jakarta.annotation.Nullable
  public Integer getPrice() {
    return price;
  }

  public void setPrice(@jakarta.annotation.Nullable Integer price) {
    this.price = price;
  }

  public GoodHistory currencyIsoCode4217(@jakarta.annotation.Nullable String currencyIsoCode4217) {
    this.currencyIsoCode4217 = currencyIsoCode4217;
    return this;
  }

  /**
   * Валюта, по стандарту ISO 4217
   *
   * @return currencyIsoCode4217
   */
  @jakarta.annotation.Nullable
  public String getCurrencyIsoCode4217() {
    return currencyIsoCode4217;
  }

  public void setCurrencyIsoCode4217(@jakarta.annotation.Nullable String currencyIsoCode4217) {
    this.currencyIsoCode4217 = currencyIsoCode4217;
  }

  public GoodHistory discount(@jakarta.annotation.Nullable Integer discount) {
    this.discount = discount;
    return this;
  }

  /**
   * Скидка, %
   *
   * @return discount
   */
  @jakarta.annotation.Nullable
  public Integer getDiscount() {
    return discount;
  }

  public void setDiscount(@jakarta.annotation.Nullable Integer discount) {
    this.discount = discount;
  }

  public GoodHistory clubDiscount(@jakarta.annotation.Nullable Integer clubDiscount) {
    this.clubDiscount = clubDiscount;
    return this;
  }

  /**
   * Скидка WB Клуба, %
   *
   * @return clubDiscount
   */
  @jakarta.annotation.Nullable
  public Integer getClubDiscount() {
    return clubDiscount;
  }

  public void setClubDiscount(@jakarta.annotation.Nullable Integer clubDiscount) {
    this.clubDiscount = clubDiscount;
  }

  public GoodHistory status(@jakarta.annotation.Nullable Integer status) {
    this.status = status;
    return this;
  }

  /**
   * Статус товара: * &#x60;2&#x60; — товар без ошибок, цена и/или скидка обновилась *
   * &#x60;3&#x60; — есть ошибки, данные не обновились
   *
   * @return status
   */
  @jakarta.annotation.Nullable
  public Integer getStatus() {
    return status;
  }

  public void setStatus(@jakarta.annotation.Nullable Integer status) {
    this.status = status;
  }

  public GoodHistory errorText(@jakarta.annotation.Nullable String errorText) {
    this.errorText = errorText;
    return this;
  }

  /**
   * Описание ошибки. Например: - &#x60;New price is several times lower than the current price.
   * Item has been moved to Price Quarantine&#x60; — ошибка возникает, если новая цена со скидкой
   * меньше [порогового
   * значения](https://seller.wildberries.ru/instructions/ru/ru/material/price-quarantine#2ef3641a-5165-41db-9ac7-e4374c9fc3f1).
   * Вы можете изменить цену или скидку с помощью API либо вывести товар из карантина в [личном
   * кабинете](https://seller.wildberries.ru/discount-and-prices/quarantine).
   *
   * @return errorText
   */
  @jakarta.annotation.Nullable
  public String getErrorText() {
    return errorText;
  }

  public void setErrorText(@jakarta.annotation.Nullable String errorText) {
    this.errorText = errorText;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoodHistory goodHistory = (GoodHistory) o;
    return Objects.equals(this.nmID, goodHistory.nmID)
        && Objects.equals(this.vendorCode, goodHistory.vendorCode)
        && Objects.equals(this.sizeID, goodHistory.sizeID)
        && Objects.equals(this.techSizeName, goodHistory.techSizeName)
        && Objects.equals(this.price, goodHistory.price)
        && Objects.equals(this.currencyIsoCode4217, goodHistory.currencyIsoCode4217)
        && Objects.equals(this.discount, goodHistory.discount)
        && Objects.equals(this.clubDiscount, goodHistory.clubDiscount)
        && Objects.equals(this.status, goodHistory.status)
        && Objects.equals(this.errorText, goodHistory.errorText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        nmID,
        vendorCode,
        sizeID,
        techSizeName,
        price,
        currencyIsoCode4217,
        discount,
        clubDiscount,
        status,
        errorText);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoodHistory {\n");
    sb.append("    nmID: ").append(toIndentedString(nmID)).append("\n");
    sb.append("    vendorCode: ").append(toIndentedString(vendorCode)).append("\n");
    sb.append("    sizeID: ").append(toIndentedString(sizeID)).append("\n");
    sb.append("    techSizeName: ").append(toIndentedString(techSizeName)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    currencyIsoCode4217: ")
        .append(toIndentedString(currencyIsoCode4217))
        .append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    clubDiscount: ").append(toIndentedString(clubDiscount)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    errorText: ").append(toIndentedString(errorText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nmID");
    openapiFields.add("vendorCode");
    openapiFields.add("sizeID");
    openapiFields.add("techSizeName");
    openapiFields.add("price");
    openapiFields.add("currencyIsoCode4217");
    openapiFields.add("discount");
    openapiFields.add("clubDiscount");
    openapiFields.add("status");
    openapiFields.add("errorText");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GoodHistory
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!GoodHistory.openapiRequiredFields
          .isEmpty()) { // has required fields but JSON element is null
        throw new IllegalArgumentException(
            String.format(
                "The required field(s) %s in GoodHistory is not found in the empty JSON string",
                GoodHistory.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!GoodHistory.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(
            String.format(
                "The field `%s` in the JSON string is not defined in the `GoodHistory` properties. JSON: %s",
                entry.getKey(), jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if ((jsonObj.get("vendorCode") != null && !jsonObj.get("vendorCode").isJsonNull())
        && !jsonObj.get("vendorCode").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `vendorCode` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("vendorCode").toString()));
    }
    if ((jsonObj.get("techSizeName") != null && !jsonObj.get("techSizeName").isJsonNull())
        && !jsonObj.get("techSizeName").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `techSizeName` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("techSizeName").toString()));
    }
    if ((jsonObj.get("currencyIsoCode4217") != null
            && !jsonObj.get("currencyIsoCode4217").isJsonNull())
        && !jsonObj.get("currencyIsoCode4217").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `currencyIsoCode4217` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("currencyIsoCode4217").toString()));
    }
    if ((jsonObj.get("errorText") != null && !jsonObj.get("errorText").isJsonNull())
        && !jsonObj.get("errorText").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `errorText` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("errorText").toString()));
    }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!GoodHistory.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'GoodHistory' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<GoodHistory> thisAdapter =
          gson.getDelegateAdapter(this, TypeToken.get(GoodHistory.class));

      return (TypeAdapter<T>)
          new TypeAdapter<GoodHistory>() {
            @Override
            public void write(JsonWriter out, GoodHistory value) throws IOException {
              JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
              elementAdapter.write(out, obj);
            }

            @Override
            public GoodHistory read(JsonReader in) throws IOException {
              JsonElement jsonElement = elementAdapter.read(in);
              validateJsonElement(jsonElement);
              return thisAdapter.fromJsonTree(jsonElement);
            }
          }.nullSafe();
    }
  }

  /**
   * Create an instance of GoodHistory given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GoodHistory
   * @throws IOException if the JSON string is invalid with respect to GoodHistory
   */
  public static GoodHistory fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoodHistory.class);
  }

  /**
   * Convert an instance of GoodHistory to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
