/*
 * Работа с товарами
 * С помощью методов этого раздела вы можете: - [создавать](/openapi/item-management#tag/listingItems) и [редактировать](/openapi/item-management#tag/listings) карточки товаров - получать [категории, предметы, характеристики и бренды товаров](/openapi/item-management#tag/categoriesSubcategoriesAndCharacteristics) - загружать [медиафайлы](/openapi/item-management#tag/mediaFiles) в карточки товаров - настраивать [ярлыки](/openapi/item-management#tag/labels) для поиска товаров - работать с [рекомендациями](/openapi/item-management#tag/recommendations) для товаров - устанавливать [цены и скидки](/openapi/item-management#tag/pricesAndDiscounts) - управлять [остатками товаров](/openapi/item-management#tag/sellerWarehousesInventory) и [складами](/openapi/item-management#tag/sellerWarehouses), если вы работаете по модели продаж со склада продавца Вы можете протестировать методы работы с товарами в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/itemManagement) для управления карточками товаровУзнать, как использовать методы в бизнес-кейсах, можно в [инструкции](/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami) по **работе с товарами**
 *
 * The version of the OpenAPI document: items
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.valeryverkhoturov.wbapi.items.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.valeryverkhoturov.wbapi.items.JSON;

/**
 * Параметры фильтрации
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PostV2GetCardsListRequestSettingsFilter {
  /**
   * Фильтр по фото:   * &#x60;-1&#x60; — любые карточки товаров   * &#x60;0&#x60; — только карточки без фото. С [16 июня](/release-notes?id&#x3D;531) — любые карточки товаров   * &#x60;1&#x60; — только карточки с фото   * &#x60;2&#x60; — только карточки без фото. С [16 июня](/release-notes?id&#x3D;531) 
   */
  @JsonAdapter(WithPhotoEnum.Adapter.class)
  public enum WithPhotoEnum {
    NUMBER_MINUS_1(-1),
    
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_2(2);

    private Integer value;

    WithPhotoEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static WithPhotoEnum fromValue(Integer value) {
      for (WithPhotoEnum b : WithPhotoEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<WithPhotoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final WithPhotoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public WithPhotoEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return WithPhotoEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      Integer value = jsonElement.getAsInt();
      WithPhotoEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_WITH_PHOTO = "withPhoto";
  @SerializedName(SERIALIZED_NAME_WITH_PHOTO)
  @jakarta.annotation.Nullable
  private WithPhotoEnum withPhoto = WithPhotoEnum.NUMBER_0;

  public static final String SERIALIZED_NAME_TEXT_SEARCH = "textSearch";
  @SerializedName(SERIALIZED_NAME_TEXT_SEARCH)
  @jakarta.annotation.Nullable
  private String textSearch;

  public static final String SERIALIZED_NAME_TAG_I_DS = "tagIDs";
  @SerializedName(SERIALIZED_NAME_TAG_I_DS)
  @jakarta.annotation.Nullable
  private List<Integer> tagIDs = new ArrayList<>();

  public static final String SERIALIZED_NAME_ALLOWED_CATEGORIES_ONLY = "allowedCategoriesOnly";
  @SerializedName(SERIALIZED_NAME_ALLOWED_CATEGORIES_ONLY)
  @jakarta.annotation.Nullable
  private Boolean allowedCategoriesOnly;

  public static final String SERIALIZED_NAME_OBJECT_I_DS = "objectIDs";
  @SerializedName(SERIALIZED_NAME_OBJECT_I_DS)
  @jakarta.annotation.Nullable
  private List<Integer> objectIDs = new ArrayList<>();

  public static final String SERIALIZED_NAME_BRANDS = "brands";
  @SerializedName(SERIALIZED_NAME_BRANDS)
  @jakarta.annotation.Nullable
  private List<String> brands = new ArrayList<>();

  public static final String SERIALIZED_NAME_IMT_I_D = "imtID";
  @SerializedName(SERIALIZED_NAME_IMT_I_D)
  @jakarta.annotation.Nullable
  private Long imtID;

  public PostV2GetCardsListRequestSettingsFilter() {
  }

  public PostV2GetCardsListRequestSettingsFilter withPhoto(@jakarta.annotation.Nullable WithPhotoEnum withPhoto) {
    this.withPhoto = withPhoto;
    return this;
  }

  /**
   * Фильтр по фото:   * &#x60;-1&#x60; — любые карточки товаров   * &#x60;0&#x60; — только карточки без фото. С [16 июня](/release-notes?id&#x3D;531) — любые карточки товаров   * &#x60;1&#x60; — только карточки с фото   * &#x60;2&#x60; — только карточки без фото. С [16 июня](/release-notes?id&#x3D;531) 
   * @return withPhoto
   */
  @jakarta.annotation.Nullable
  public WithPhotoEnum getWithPhoto() {
    return withPhoto;
  }

  public void setWithPhoto(@jakarta.annotation.Nullable WithPhotoEnum withPhoto) {
    this.withPhoto = withPhoto;
  }


  public PostV2GetCardsListRequestSettingsFilter textSearch(@jakarta.annotation.Nullable String textSearch) {
    this.textSearch = textSearch;
    return this;
  }

  /**
   * Поиск по артикулу продавца, артикулу WB, баркоду
   * @return textSearch
   */
  @jakarta.annotation.Nullable
  public String getTextSearch() {
    return textSearch;
  }

  public void setTextSearch(@jakarta.annotation.Nullable String textSearch) {
    this.textSearch = textSearch;
  }


  public PostV2GetCardsListRequestSettingsFilter tagIDs(@jakarta.annotation.Nullable List<Integer> tagIDs) {
    this.tagIDs = tagIDs;
    return this;
  }

  public PostV2GetCardsListRequestSettingsFilter addTagIDsItem(Integer tagIDsItem) {
    if (this.tagIDs == null) {
      this.tagIDs = new ArrayList<>();
    }
    this.tagIDs.add(tagIDsItem);
    return this;
  }

  /**
   * Поиск по ID ярлыков
   * @return tagIDs
   */
  @jakarta.annotation.Nullable
  public List<Integer> getTagIDs() {
    return tagIDs;
  }

  public void setTagIDs(@jakarta.annotation.Nullable List<Integer> tagIDs) {
    this.tagIDs = tagIDs;
  }


  public PostV2GetCardsListRequestSettingsFilter allowedCategoriesOnly(@jakarta.annotation.Nullable Boolean allowedCategoriesOnly) {
    this.allowedCategoriesOnly = allowedCategoriesOnly;
    return this;
  }

  /**
   * Фильтр по категории:   - &#x60;true&#x60; — только разрешённые   - &#x60;false&#x60; — все    Не используется в песочнице 
   * @return allowedCategoriesOnly
   */
  @jakarta.annotation.Nullable
  public Boolean getAllowedCategoriesOnly() {
    return allowedCategoriesOnly;
  }

  public void setAllowedCategoriesOnly(@jakarta.annotation.Nullable Boolean allowedCategoriesOnly) {
    this.allowedCategoriesOnly = allowedCategoriesOnly;
  }


  public PostV2GetCardsListRequestSettingsFilter objectIDs(@jakarta.annotation.Nullable List<Integer> objectIDs) {
    this.objectIDs = objectIDs;
    return this;
  }

  public PostV2GetCardsListRequestSettingsFilter addObjectIDsItem(Integer objectIDsItem) {
    if (this.objectIDs == null) {
      this.objectIDs = new ArrayList<>();
    }
    this.objectIDs.add(objectIDsItem);
    return this;
  }

  /**
   * Поиск по ID предметов
   * @return objectIDs
   */
  @jakarta.annotation.Nullable
  public List<Integer> getObjectIDs() {
    return objectIDs;
  }

  public void setObjectIDs(@jakarta.annotation.Nullable List<Integer> objectIDs) {
    this.objectIDs = objectIDs;
  }


  public PostV2GetCardsListRequestSettingsFilter brands(@jakarta.annotation.Nullable List<String> brands) {
    this.brands = brands;
    return this;
  }

  public PostV2GetCardsListRequestSettingsFilter addBrandsItem(String brandsItem) {
    if (this.brands == null) {
      this.brands = new ArrayList<>();
    }
    this.brands.add(brandsItem);
    return this;
  }

  /**
   * Поиск по брендам
   * @return brands
   */
  @jakarta.annotation.Nullable
  public List<String> getBrands() {
    return brands;
  }

  public void setBrands(@jakarta.annotation.Nullable List<String> brands) {
    this.brands = brands;
  }


  public PostV2GetCardsListRequestSettingsFilter imtID(@jakarta.annotation.Nullable Long imtID) {
    this.imtID = imtID;
    return this;
  }

  /**
   * Поиск по [ID для объединённых карточек товаров](/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami#obuedinenie-i-razuedinenie-kartochek-tovarov)
   * @return imtID
   */
  @jakarta.annotation.Nullable
  public Long getImtID() {
    return imtID;
  }

  public void setImtID(@jakarta.annotation.Nullable Long imtID) {
    this.imtID = imtID;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostV2GetCardsListRequestSettingsFilter postV2GetCardsListRequestSettingsFilter = (PostV2GetCardsListRequestSettingsFilter) o;
    return Objects.equals(this.withPhoto, postV2GetCardsListRequestSettingsFilter.withPhoto) &&
        Objects.equals(this.textSearch, postV2GetCardsListRequestSettingsFilter.textSearch) &&
        Objects.equals(this.tagIDs, postV2GetCardsListRequestSettingsFilter.tagIDs) &&
        Objects.equals(this.allowedCategoriesOnly, postV2GetCardsListRequestSettingsFilter.allowedCategoriesOnly) &&
        Objects.equals(this.objectIDs, postV2GetCardsListRequestSettingsFilter.objectIDs) &&
        Objects.equals(this.brands, postV2GetCardsListRequestSettingsFilter.brands) &&
        Objects.equals(this.imtID, postV2GetCardsListRequestSettingsFilter.imtID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(withPhoto, textSearch, tagIDs, allowedCategoriesOnly, objectIDs, brands, imtID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostV2GetCardsListRequestSettingsFilter {\n");
    sb.append("    withPhoto: ").append(toIndentedString(withPhoto)).append("\n");
    sb.append("    textSearch: ").append(toIndentedString(textSearch)).append("\n");
    sb.append("    tagIDs: ").append(toIndentedString(tagIDs)).append("\n");
    sb.append("    allowedCategoriesOnly: ").append(toIndentedString(allowedCategoriesOnly)).append("\n");
    sb.append("    objectIDs: ").append(toIndentedString(objectIDs)).append("\n");
    sb.append("    brands: ").append(toIndentedString(brands)).append("\n");
    sb.append("    imtID: ").append(toIndentedString(imtID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("withPhoto");
    openapiFields.add("textSearch");
    openapiFields.add("tagIDs");
    openapiFields.add("allowedCategoriesOnly");
    openapiFields.add("objectIDs");
    openapiFields.add("brands");
    openapiFields.add("imtID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostV2GetCardsListRequestSettingsFilter
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostV2GetCardsListRequestSettingsFilter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostV2GetCardsListRequestSettingsFilter is not found in the empty JSON string", PostV2GetCardsListRequestSettingsFilter.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostV2GetCardsListRequestSettingsFilter.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PostV2GetCardsListRequestSettingsFilter` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `withPhoto`
      if (jsonObj.get("withPhoto") != null && !jsonObj.get("withPhoto").isJsonNull()) {
        WithPhotoEnum.validateJsonElement(jsonObj.get("withPhoto"));
      }
      if ((jsonObj.get("textSearch") != null && !jsonObj.get("textSearch").isJsonNull()) && !jsonObj.get("textSearch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `textSearch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("textSearch").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tagIDs") != null && !jsonObj.get("tagIDs").isJsonNull() && !jsonObj.get("tagIDs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tagIDs` to be an array in the JSON string but got `%s`", jsonObj.get("tagIDs").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("objectIDs") != null && !jsonObj.get("objectIDs").isJsonNull() && !jsonObj.get("objectIDs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `objectIDs` to be an array in the JSON string but got `%s`", jsonObj.get("objectIDs").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("brands") != null && !jsonObj.get("brands").isJsonNull() && !jsonObj.get("brands").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `brands` to be an array in the JSON string but got `%s`", jsonObj.get("brands").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostV2GetCardsListRequestSettingsFilter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostV2GetCardsListRequestSettingsFilter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostV2GetCardsListRequestSettingsFilter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostV2GetCardsListRequestSettingsFilter.class));

       return (TypeAdapter<T>) new TypeAdapter<PostV2GetCardsListRequestSettingsFilter>() {
           @Override
           public void write(JsonWriter out, PostV2GetCardsListRequestSettingsFilter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostV2GetCardsListRequestSettingsFilter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostV2GetCardsListRequestSettingsFilter given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostV2GetCardsListRequestSettingsFilter
   * @throws IOException if the JSON string is invalid with respect to PostV2GetCardsListRequestSettingsFilter
   */
  public static PostV2GetCardsListRequestSettingsFilter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostV2GetCardsListRequestSettingsFilter.class);
  }

  /**
   * Convert an instance of PostV2GetCardsListRequestSettingsFilter to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

