/*
 * Работа с товарами
 * С помощью методов этого раздела вы можете: - [создавать](https://dev.wildberries.ru/openapi/item-management#tag/listingItems) и [редактировать](https://dev.wildberries.ru/openapi/item-management#tag/listings) карточки товаров - получать [категории, предметы, характеристики и бренды товаров](https://dev.wildberries.ru/openapi/item-management#tag/categoriesSubcategoriesAndCharacteristics) - загружать [медиафайлы](https://dev.wildberries.ru/openapi/item-management#tag/mediaFiles) в карточки товаров - настраивать [ярлыки](https://dev.wildberries.ru/openapi/item-management#tag/labels) для поиска товаров - работать с [рекомендациями](https://dev.wildberries.ru/openapi/item-management#tag/recommendations) для товаров - устанавливать [цены и скидки](https://dev.wildberries.ru/openapi/item-management#tag/pricesAndDiscounts) - управлять [остатками товаров](https://dev.wildberries.ru/openapi/item-management#tag/sellerWarehousesInventory) и [складами](https://dev.wildberries.ru/openapi/item-management#tag/sellerWarehouses), если вы работаете по модели продаж со склада продавца Вы можете протестировать методы работы с товарами в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/itemManagement) для управления карточками товаров  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami) по **работе с товарами**
 *
 * The version of the OpenAPI document: items
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.valeryverkhoturov.wbapi.items.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.valeryverkhoturov.wbapi.items.JSON;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** PostV2CardsUpdateRequestInnerDocumentsItemsInner */
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.10.0")
public class PostV2CardsUpdateRequestInnerDocumentsItemsInner {
  public static final String SERIALIZED_NAME_TYPE = "type";

  @SerializedName(SERIALIZED_NAME_TYPE)
  @jakarta.annotation.Nullable
  private Integer type;

  public static final String SERIALIZED_NAME_NUMBER = "number";

  @SerializedName(SERIALIZED_NAME_NUMBER)
  @jakarta.annotation.Nullable
  private String number;

  public static final String SERIALIZED_NAME_PRODUCT_NUMBER = "productNumber";

  @SerializedName(SERIALIZED_NAME_PRODUCT_NUMBER)
  @jakarta.annotation.Nullable
  private String productNumber;

  public static final String SERIALIZED_NAME_TRADE_NAME = "tradeName";

  @SerializedName(SERIALIZED_NAME_TRADE_NAME)
  @jakarta.annotation.Nullable
  private String tradeName;

  public static final String SERIALIZED_NAME_APPLICANT = "applicant";

  @SerializedName(SERIALIZED_NAME_APPLICANT)
  @jakarta.annotation.Nullable
  private String applicant;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";

  @SerializedName(SERIALIZED_NAME_START_DATE)
  @jakarta.annotation.Nullable
  private String startDate;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";

  @SerializedName(SERIALIZED_NAME_END_DATE)
  @jakarta.annotation.Nullable
  private String endDate;

  public static final String SERIALIZED_NAME_IS_ENDLESS = "isEndless";

  @SerializedName(SERIALIZED_NAME_IS_ENDLESS)
  @jakarta.annotation.Nullable
  private Boolean isEndless;

  public static final String SERIALIZED_NAME_ID = "id";

  @SerializedName(SERIALIZED_NAME_ID)
  @jakarta.annotation.Nullable
  private String id;

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner() {}

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner type(
      @jakarta.annotation.Nullable Integer type) {
    this.type = type;
    return this;
  }

  /**
   * Тип документа. Типы документов, которые вы можете добавить для товара, указаны в
   * [характеристиках
   * предмета](./item-management#tag/categoriesSubcategoriesAndCharacteristics/operation/getV2ObjectCharcsSubjectId)
   * — поле &#x60;charcID&#x60;. Возможные типы документов: - &#x60;1&#x60; — Сертификат
   * соответствия. Можно указать для &#x60;charcID&#x60;: 15001136, 15001137, 15001138 -
   * &#x60;2&#x60; — Декларация о соответствии. Можно указать для &#x60;charcID&#x60;: 15001135,
   * 15001137, 15001138 - &#x60;3&#x60; — Свидетельство о государственной регистрации (СГР). Можно
   * указать для &#x60;charcID&#x60;: 62945173, 15000785, 15004302 - &#x60;4&#x60; — Регистрационное
   * удостоверение (РУ) на медицинские изделия. Можно указать для &#x60;charcID&#x60;: 15001574,
   * 15002355, 15002356, 15002357 - &#x60;5&#x60; — Регистрационное удостоверение Республики
   * Беларусь. Можно указать для &#x60;charcID&#x60;: 15003071, 15003939 - &#x60;7&#x60; — Данные о
   * регистрации пестицида. Можно указать для &#x60;charcID&#x60;: 15003924, 15003925 -
   * &#x60;8&#x60; — Данные о регистрации агрохимиката. Можно указать для &#x60;charcID&#x60;:
   * 15003920, 15003921 - &#x60;9&#x60; — Регистрационное удостоверение (РУ) на лекарственные
   * препараты. Можно указать для &#x60;charcID&#x60;: 1897013, 15004284
   *
   * @return type
   */
  @jakarta.annotation.Nullable
  public Integer getType() {
    return type;
  }

  public void setType(@jakarta.annotation.Nullable Integer type) {
    this.type = type;
  }

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner number(
      @jakarta.annotation.Nullable String number) {
    this.number = number;
    return this;
  }

  /**
   * Номер документа
   *
   * @return number
   */
  @jakarta.annotation.Nullable
  public String getNumber() {
    return number;
  }

  public void setNumber(@jakarta.annotation.Nullable String number) {
    this.number = number;
  }

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner productNumber(
      @jakarta.annotation.Nullable String productNumber) {
    this.productNumber = productNumber;
    return this;
  }

  /**
   * Дополнительный номер документа
   *
   * @return productNumber
   */
  @jakarta.annotation.Nullable
  public String getProductNumber() {
    return productNumber;
  }

  public void setProductNumber(@jakarta.annotation.Nullable String productNumber) {
    this.productNumber = productNumber;
  }

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner tradeName(
      @jakarta.annotation.Nullable String tradeName) {
    this.tradeName = tradeName;
    return this;
  }

  /**
   * Торговое наименование
   *
   * @return tradeName
   */
  @jakarta.annotation.Nullable
  public String getTradeName() {
    return tradeName;
  }

  public void setTradeName(@jakarta.annotation.Nullable String tradeName) {
    this.tradeName = tradeName;
  }

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner applicant(
      @jakarta.annotation.Nullable String applicant) {
    this.applicant = applicant;
    return this;
  }

  /**
   * Представитель изготовителя медицинского изделия
   *
   * @return applicant
   */
  @jakarta.annotation.Nullable
  public String getApplicant() {
    return applicant;
  }

  public void setApplicant(@jakarta.annotation.Nullable String applicant) {
    this.applicant = applicant;
  }

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner startDate(
      @jakarta.annotation.Nullable String startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * Дата и время начала срока действия документа
   *
   * @return startDate
   */
  @jakarta.annotation.Nullable
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(@jakarta.annotation.Nullable String startDate) {
    this.startDate = startDate;
  }

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner endDate(
      @jakarta.annotation.Nullable String endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * Дата и время окончания срока действия документа
   *
   * @return endDate
   */
  @jakarta.annotation.Nullable
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(@jakarta.annotation.Nullable String endDate) {
    this.endDate = endDate;
  }

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner isEndless(
      @jakarta.annotation.Nullable Boolean isEndless) {
    this.isEndless = isEndless;
    return this;
  }

  /**
   * Бессрочный ли документ: - &#x60;true&#x60; — да, документ бессрочный - &#x60;false&#x60; — нет,
   * у документа есть срок действия
   *
   * @return isEndless
   */
  @jakarta.annotation.Nullable
  public Boolean getIsEndless() {
    return isEndless;
  }

  public void setIsEndless(@jakarta.annotation.Nullable Boolean isEndless) {
    this.isEndless = isEndless;
  }

  public PostV2CardsUpdateRequestInnerDocumentsItemsInner id(
      @jakarta.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * ID документа, прикреплённого к карточке. Укажите &#x60;id&#x60;, чтобы внести изменения в
   * прикреплённый ранее документ. ID документа указан в [списке карточек
   * товаров](https://dev.wildberries.ru/item-management#tag/listings/operation/postV2GetCardsList).
   * Чтобы добавить новый документ, указывать &#x60;id&#x60; не нужно.
   *
   * @return id
   */
  @jakarta.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostV2CardsUpdateRequestInnerDocumentsItemsInner
        postV2CardsUpdateRequestInnerDocumentsItemsInner =
            (PostV2CardsUpdateRequestInnerDocumentsItemsInner) o;
    return Objects.equals(this.type, postV2CardsUpdateRequestInnerDocumentsItemsInner.type)
        && Objects.equals(this.number, postV2CardsUpdateRequestInnerDocumentsItemsInner.number)
        && Objects.equals(
            this.productNumber, postV2CardsUpdateRequestInnerDocumentsItemsInner.productNumber)
        && Objects.equals(
            this.tradeName, postV2CardsUpdateRequestInnerDocumentsItemsInner.tradeName)
        && Objects.equals(
            this.applicant, postV2CardsUpdateRequestInnerDocumentsItemsInner.applicant)
        && Objects.equals(
            this.startDate, postV2CardsUpdateRequestInnerDocumentsItemsInner.startDate)
        && Objects.equals(this.endDate, postV2CardsUpdateRequestInnerDocumentsItemsInner.endDate)
        && Objects.equals(
            this.isEndless, postV2CardsUpdateRequestInnerDocumentsItemsInner.isEndless)
        && Objects.equals(this.id, postV2CardsUpdateRequestInnerDocumentsItemsInner.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        type, number, productNumber, tradeName, applicant, startDate, endDate, isEndless, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostV2CardsUpdateRequestInnerDocumentsItemsInner {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    productNumber: ").append(toIndentedString(productNumber)).append("\n");
    sb.append("    tradeName: ").append(toIndentedString(tradeName)).append("\n");
    sb.append("    applicant: ").append(toIndentedString(applicant)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    isEndless: ").append(toIndentedString(isEndless)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("number");
    openapiFields.add("productNumber");
    openapiFields.add("tradeName");
    openapiFields.add("applicant");
    openapiFields.add("startDate");
    openapiFields.add("endDate");
    openapiFields.add("isEndless");
    openapiFields.add("id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to
   *     PostV2CardsUpdateRequestInnerDocumentsItemsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!PostV2CardsUpdateRequestInnerDocumentsItemsInner.openapiRequiredFields
          .isEmpty()) { // has required fields but JSON element is null
        throw new IllegalArgumentException(
            String.format(
                "The required field(s) %s in PostV2CardsUpdateRequestInnerDocumentsItemsInner is not found in the empty JSON string",
                PostV2CardsUpdateRequestInnerDocumentsItemsInner.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!PostV2CardsUpdateRequestInnerDocumentsItemsInner.openapiFields.contains(
          entry.getKey())) {
        throw new IllegalArgumentException(
            String.format(
                "The field `%s` in the JSON string is not defined in the `PostV2CardsUpdateRequestInnerDocumentsItemsInner` properties. JSON: %s",
                entry.getKey(), jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if ((jsonObj.get("number") != null && !jsonObj.get("number").isJsonNull())
        && !jsonObj.get("number").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `number` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("number").toString()));
    }
    if ((jsonObj.get("productNumber") != null && !jsonObj.get("productNumber").isJsonNull())
        && !jsonObj.get("productNumber").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `productNumber` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("productNumber").toString()));
    }
    if ((jsonObj.get("tradeName") != null && !jsonObj.get("tradeName").isJsonNull())
        && !jsonObj.get("tradeName").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `tradeName` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("tradeName").toString()));
    }
    if ((jsonObj.get("applicant") != null && !jsonObj.get("applicant").isJsonNull())
        && !jsonObj.get("applicant").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `applicant` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("applicant").toString()));
    }
    if ((jsonObj.get("startDate") != null && !jsonObj.get("startDate").isJsonNull())
        && !jsonObj.get("startDate").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `startDate` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("startDate").toString()));
    }
    if ((jsonObj.get("endDate") != null && !jsonObj.get("endDate").isJsonNull())
        && !jsonObj.get("endDate").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `endDate` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("endDate").toString()));
    }
    if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull())
        && !jsonObj.get("id").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `id` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("id").toString()));
    }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!PostV2CardsUpdateRequestInnerDocumentsItemsInner.class.isAssignableFrom(
          type.getRawType())) {
        return null; // this class only serializes
        // 'PostV2CardsUpdateRequestInnerDocumentsItemsInner' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<PostV2CardsUpdateRequestInnerDocumentsItemsInner> thisAdapter =
          gson.getDelegateAdapter(
              this, TypeToken.get(PostV2CardsUpdateRequestInnerDocumentsItemsInner.class));

      return (TypeAdapter<T>)
          new TypeAdapter<PostV2CardsUpdateRequestInnerDocumentsItemsInner>() {
            @Override
            public void write(
                JsonWriter out, PostV2CardsUpdateRequestInnerDocumentsItemsInner value)
                throws IOException {
              JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
              elementAdapter.write(out, obj);
            }

            @Override
            public PostV2CardsUpdateRequestInnerDocumentsItemsInner read(JsonReader in)
                throws IOException {
              JsonElement jsonElement = elementAdapter.read(in);
              validateJsonElement(jsonElement);
              return thisAdapter.fromJsonTree(jsonElement);
            }
          }.nullSafe();
    }
  }

  /**
   * Create an instance of PostV2CardsUpdateRequestInnerDocumentsItemsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostV2CardsUpdateRequestInnerDocumentsItemsInner
   * @throws IOException if the JSON string is invalid with respect to
   *     PostV2CardsUpdateRequestInnerDocumentsItemsInner
   */
  public static PostV2CardsUpdateRequestInnerDocumentsItemsInner fromJson(String jsonString)
      throws IOException {
    return JSON.getGson()
        .fromJson(jsonString, PostV2CardsUpdateRequestInnerDocumentsItemsInner.class);
  }

  /**
   * Convert an instance of PostV2CardsUpdateRequestInnerDocumentsItemsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
