/*
Маркетинг и продвижение

Узнать больше о маркетинге и продвижении можно в [справочном центре](https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e)Методы маркетинга и продвижения позволяют: 1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/campaigns) и [медиакампаниях](/openapi/promotion#tag/media) 2. [Создавать](/openapi/promotion#tag/creatingCampaigns) и [управлять](/openapi/promotion#tag/campaignManagement) кампаниями 3. Управлять [финансами](/openapi/promotion#tag/finances) кампаний 4. Выгружать [статистику](/openapi/promotion#tag/statistics) кампаний продвижения и медиакампаний 5. Работать с [календарём акций](/openapi/promotion#tag/promoCalendar) Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  Вы можете протестировать методы продвижения в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/promotion) для управления тестовым балансом

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
)

// checks if the GetV1CountResponse200Adverts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetV1CountResponse200Adverts{}

// GetV1CountResponse200Adverts struct for GetV1CountResponse200Adverts
type GetV1CountResponse200Adverts struct {
	// Тип медиакампании: - `1` — размещение по дням - `2` — размещение по просмотрам 
	Type *int32 `json:"type,omitempty"`
	// Статус медиакампании:   - `1` — черновик   - `2` — модерация   - `3` — отклонена (с возможностью вернуть на модерацию)   - `4` — готова к запуску   - `5` — запланирована   - `6` — на показах   - `7` — завершена   - `8` — отменена   - `9` — приостановлена продавцом   - `10` — пауза по дневному лимиту   - `11` — пауза 
	Status *int32 `json:"status,omitempty"`
	// Количество медиакампаний
	Count *int32 `json:"count,omitempty"`
}

// NewGetV1CountResponse200Adverts instantiates a new GetV1CountResponse200Adverts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetV1CountResponse200Adverts() *GetV1CountResponse200Adverts {
	this := GetV1CountResponse200Adverts{}
	return &this
}

// NewGetV1CountResponse200AdvertsWithDefaults instantiates a new GetV1CountResponse200Adverts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetV1CountResponse200AdvertsWithDefaults() *GetV1CountResponse200Adverts {
	this := GetV1CountResponse200Adverts{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetV1CountResponse200Adverts) GetType() int32 {
	if o == nil || IsNil(o.Type) {
		var ret int32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV1CountResponse200Adverts) GetTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetV1CountResponse200Adverts) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given int32 and assigns it to the Type field.
func (o *GetV1CountResponse200Adverts) SetType(v int32) {
	o.Type = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetV1CountResponse200Adverts) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV1CountResponse200Adverts) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetV1CountResponse200Adverts) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *GetV1CountResponse200Adverts) SetStatus(v int32) {
	o.Status = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetV1CountResponse200Adverts) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV1CountResponse200Adverts) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetV1CountResponse200Adverts) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetV1CountResponse200Adverts) SetCount(v int32) {
	o.Count = &v
}

func (o GetV1CountResponse200Adverts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetV1CountResponse200Adverts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableGetV1CountResponse200Adverts struct {
	value *GetV1CountResponse200Adverts
	isSet bool
}

func (v NullableGetV1CountResponse200Adverts) Get() *GetV1CountResponse200Adverts {
	return v.value
}

func (v *NullableGetV1CountResponse200Adverts) Set(val *GetV1CountResponse200Adverts) {
	v.value = val
	v.isSet = true
}

func (v NullableGetV1CountResponse200Adverts) IsSet() bool {
	return v.isSet
}

func (v *NullableGetV1CountResponse200Adverts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetV1CountResponse200Adverts(val *GetV1CountResponse200Adverts) *NullableGetV1CountResponse200Adverts {
	return &NullableGetV1CountResponse200Adverts{value: val, isSet: true}
}

func (v NullableGetV1CountResponse200Adverts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetV1CountResponse200Adverts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


