/*
 * Заказы FBS
 *
 * С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете: - получать информацию о [сборочных заданиях](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsAssemblyOrders) и их статусах, отменять сборочные задания, получать стикеры - добавлять, редактировать и удалять [идентификаторы маркировки](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsLabelIdentifiers) сборочных заданий - управлять [поставками](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsSupplies) - создавать, редактировать и удалять [пропуска](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsPasses) на склады WB Вы можете протестировать методы заказов FBS в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/marketplaceFbs) для эмуляции действий пользователя  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs) по работе с **заказами FBS**  Узнать больше о заказах FBS можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d)
 *
 * The version of the OpenAPI document: order
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ValeryVerkhoturov.WbApiClient.OrdersFbs.Client.OpenAPIDateConverter;

namespace ValeryVerkhoturov.WbApiClient.OrdersFbs.Model
{
    /// <summary>
    /// UpdateSupplyWaybill
    /// </summary>
    [DataContract(Name = "UpdateSupplyWaybill")]
    public partial class UpdateSupplyWaybill : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSupplyWaybill" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateSupplyWaybill() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSupplyWaybill" /> class.
        /// </summary>
        /// <param name="supplyId">ID поставки (required).</param>
        /// <param name="waybillUuid">ID ЭТрН (required).</param>
        public UpdateSupplyWaybill(string supplyId = default(string), Guid waybillUuid = default(Guid))
        {
            // to ensure "supplyId" is required (not null)
            if (supplyId == null)
            {
                throw new ArgumentNullException("supplyId is a required property for UpdateSupplyWaybill and cannot be null");
            }
            this.SupplyId = supplyId;
            this.WaybillUuid = waybillUuid;
        }

        /// <summary>
        /// ID поставки
        /// </summary>
        /// <value>ID поставки</value>
        /*
        <example>WB-GI-100</example>
        */
        [DataMember(Name = "supplyId", IsRequired = true, EmitDefaultValue = true)]
        public string SupplyId { get; set; }

        /// <summary>
        /// ID ЭТрН
        /// </summary>
        /// <value>ID ЭТрН</value>
        /*
        <example>550e8400-e29b-41d4-a716-445676543567</example>
        */
        [DataMember(Name = "waybillUuid", IsRequired = true, EmitDefaultValue = true)]
        public Guid WaybillUuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateSupplyWaybill {\n");
            sb.Append("  SupplyId: ").Append(SupplyId).Append("\n");
            sb.Append("  WaybillUuid: ").Append(WaybillUuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
