/*
 * Маркетинг и продвижение
 * Узнать больше о маркетинге и продвижении можно в [справочном центре](https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e)Методы маркетинга и продвижения позволяют: 1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/campaigns) и [медиакампаниях](/openapi/promotion#tag/media) 2. [Создавать](/openapi/promotion#tag/creatingCampaigns) и [управлять](/openapi/promotion#tag/campaignManagement) кампаниями 3. Управлять [финансами](/openapi/promotion#tag/finances) кампаний 4. Выгружать [статистику](/openapi/promotion#tag/statistics) кампаний продвижения и медиакампаний 5. Работать с [календарём акций](/openapi/promotion#tag/promoCalendar) Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  Вы можете протестировать методы продвижения в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/promotion) для управления тестовым балансом
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.valeryverkhoturov.wbapi.promotion.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.valeryverkhoturov.wbapi.promotion.JSON;

/**
 * Максимальный охват: 76-100% 
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class V0BidRecommendationReachMax {
  public static final String SERIALIZED_NAME_BID_KOPECKS = "bidKopecks";
  @SerializedName(SERIALIZED_NAME_BID_KOPECKS)
  @jakarta.annotation.Nullable
  private Integer bidKopecks;

  public static final String SERIALIZED_NAME_BID_KOPECKS_MIN = "bidKopecksMin";
  @SerializedName(SERIALIZED_NAME_BID_KOPECKS_MIN)
  @jakarta.annotation.Nullable
  private Integer bidKopecksMin;

  public V0BidRecommendationReachMax() {
  }

  public V0BidRecommendationReachMax bidKopecks(@jakarta.annotation.Nullable Integer bidKopecks) {
    this.bidKopecks = bidKopecks;
    return this;
  }

  /**
   * Рекомендуемая ставка в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances).
   * @return bidKopecks
   */
  @jakarta.annotation.Nullable
  public Integer getBidKopecks() {
    return bidKopecks;
  }

  public void setBidKopecks(@jakarta.annotation.Nullable Integer bidKopecks) {
    this.bidKopecks = bidKopecks;
  }


  public V0BidRecommendationReachMax bidKopecksMin(@jakarta.annotation.Nullable Integer bidKopecksMin) {
    this.bidKopecksMin = bidKopecksMin;
    return this;
  }

  /**
   * Минимальная ставка в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances).
   * @return bidKopecksMin
   */
  @jakarta.annotation.Nullable
  public Integer getBidKopecksMin() {
    return bidKopecksMin;
  }

  public void setBidKopecksMin(@jakarta.annotation.Nullable Integer bidKopecksMin) {
    this.bidKopecksMin = bidKopecksMin;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V0BidRecommendationReachMax v0BidRecommendationReachMax = (V0BidRecommendationReachMax) o;
    return Objects.equals(this.bidKopecks, v0BidRecommendationReachMax.bidKopecks) &&
        Objects.equals(this.bidKopecksMin, v0BidRecommendationReachMax.bidKopecksMin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bidKopecks, bidKopecksMin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V0BidRecommendationReachMax {\n");
    sb.append("    bidKopecks: ").append(toIndentedString(bidKopecks)).append("\n");
    sb.append("    bidKopecksMin: ").append(toIndentedString(bidKopecksMin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bidKopecks");
    openapiFields.add("bidKopecksMin");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V0BidRecommendationReachMax
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V0BidRecommendationReachMax.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V0BidRecommendationReachMax is not found in the empty JSON string", V0BidRecommendationReachMax.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V0BidRecommendationReachMax.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V0BidRecommendationReachMax` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V0BidRecommendationReachMax.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V0BidRecommendationReachMax' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V0BidRecommendationReachMax> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V0BidRecommendationReachMax.class));

       return (TypeAdapter<T>) new TypeAdapter<V0BidRecommendationReachMax>() {
           @Override
           public void write(JsonWriter out, V0BidRecommendationReachMax value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V0BidRecommendationReachMax read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V0BidRecommendationReachMax given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V0BidRecommendationReachMax
   * @throws IOException if the JSON string is invalid with respect to V0BidRecommendationReachMax
   */
  public static V0BidRecommendationReachMax fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V0BidRecommendationReachMax.class);
  }

  /**
   * Convert an instance of V0BidRecommendationReachMax to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

