/*
 * Отчёты
 * Узнать больше об отчётах можно в [справочном центре](https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0)  С помощью этих методов вы можете получать [основные отчёты](https://dev.wildberries.ru/openapi/reports#tag/mainReports) и отчёты о: 1. [Остатках на складах](https://dev.wildberries.ru/openapi/reports#tag/warehousesInventoryReport) 2. [Товарах с обязательной маркировкой](https://dev.wildberries.ru/openapi/reports#tag/reportOnItemsWithMandatoryLabeling) 3. [Удержаниях](https://dev.wildberries.ru/openapi/reports#tag/retentionReports) 4. [Операциях при приёмке](https://dev.wildberries.ru/openapi/reports#tag/acceptanceExpenses) 5. [Платном хранении](https://dev.wildberries.ru/openapi/reports#tag/paidStorage) 6. [Продажах по регионам](https://dev.wildberries.ru/openapi/reports#tag/salesByRegions) 7. [Доле бренда в продажах](https://dev.wildberries.ru/openapi/reports#tag/shareOfBrandInSales) 8. [Заблокированных карточках](https://dev.wildberries.ru/openapi/reports#tag/blockedItems) 9. [Возвратах и перемещении товаров](https://dev.wildberries.ru/openapi/reports#tag/returnsAndItemMovementReport)
 *
 * The version of the OpenAPI document: reports
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.valeryverkhoturov.wbapi.reports.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.valeryverkhoturov.wbapi.reports.JSON;

/**
 * GetV1PaidStorageTasksTaskIdDownloadResponse200Inner
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class GetV1PaidStorageTasksTaskIdDownloadResponse200Inner {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @jakarta.annotation.Nullable
  private String date;

  public static final String SERIALIZED_NAME_LOG_WAREHOUSE_COEF = "logWarehouseCoef";
  @SerializedName(SERIALIZED_NAME_LOG_WAREHOUSE_COEF)
  @jakarta.annotation.Nullable
  private BigDecimal logWarehouseCoef;

  public static final String SERIALIZED_NAME_OFFICE_ID = "officeId";
  @SerializedName(SERIALIZED_NAME_OFFICE_ID)
  @jakarta.annotation.Nullable
  private Integer officeId;

  public static final String SERIALIZED_NAME_WAREHOUSE = "warehouse";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE)
  @jakarta.annotation.Nullable
  private String warehouse;

  public static final String SERIALIZED_NAME_WAREHOUSE_COEF = "warehouseCoef";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE_COEF)
  @jakarta.annotation.Nullable
  private BigDecimal warehouseCoef;

  public static final String SERIALIZED_NAME_GI_ID = "giId";
  @SerializedName(SERIALIZED_NAME_GI_ID)
  @jakarta.annotation.Nullable
  private Integer giId;

  public static final String SERIALIZED_NAME_CHRT_ID = "chrtId";
  @SerializedName(SERIALIZED_NAME_CHRT_ID)
  @jakarta.annotation.Nullable
  private Integer chrtId;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  @jakarta.annotation.Nullable
  private String size;

  public static final String SERIALIZED_NAME_BARCODE = "barcode";
  @SerializedName(SERIALIZED_NAME_BARCODE)
  @jakarta.annotation.Nullable
  private String barcode;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  @jakarta.annotation.Nullable
  private String subject;

  public static final String SERIALIZED_NAME_BRAND = "brand";
  @SerializedName(SERIALIZED_NAME_BRAND)
  @jakarta.annotation.Nullable
  private String brand;

  public static final String SERIALIZED_NAME_VENDOR_CODE = "vendorCode";
  @SerializedName(SERIALIZED_NAME_VENDOR_CODE)
  @jakarta.annotation.Nullable
  private String vendorCode;

  public static final String SERIALIZED_NAME_NM_ID = "nmId";
  @SerializedName(SERIALIZED_NAME_NM_ID)
  @jakarta.annotation.Nullable
  private Integer nmId;

  public static final String SERIALIZED_NAME_VOLUME = "volume";
  @SerializedName(SERIALIZED_NAME_VOLUME)
  @jakarta.annotation.Nullable
  private BigDecimal volume;

  public static final String SERIALIZED_NAME_CALC_TYPE = "calcType";
  @SerializedName(SERIALIZED_NAME_CALC_TYPE)
  @jakarta.annotation.Nullable
  private String calcType;

  public static final String SERIALIZED_NAME_WAREHOUSE_PRICE = "warehousePrice";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE_PRICE)
  @jakarta.annotation.Nullable
  private BigDecimal warehousePrice;

  public static final String SERIALIZED_NAME_BARCODES_COUNT = "barcodesCount";
  @SerializedName(SERIALIZED_NAME_BARCODES_COUNT)
  @jakarta.annotation.Nullable
  private Integer barcodesCount;

  public static final String SERIALIZED_NAME_PALLET_PLACE_CODE = "palletPlaceCode";
  @SerializedName(SERIALIZED_NAME_PALLET_PLACE_CODE)
  @jakarta.annotation.Nullable
  private Integer palletPlaceCode;

  public static final String SERIALIZED_NAME_PALLET_COUNT = "palletCount";
  @SerializedName(SERIALIZED_NAME_PALLET_COUNT)
  @jakarta.annotation.Nullable
  private BigDecimal palletCount;

  public static final String SERIALIZED_NAME_ORIGINAL_DATE = "originalDate";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_DATE)
  @jakarta.annotation.Nullable
  private String originalDate;

  public static final String SERIALIZED_NAME_LOYALTY_DISCOUNT = "loyaltyDiscount";
  @SerializedName(SERIALIZED_NAME_LOYALTY_DISCOUNT)
  @jakarta.annotation.Nullable
  private BigDecimal loyaltyDiscount;

  public static final String SERIALIZED_NAME_TARIFF_FIX_DATE = "tariffFixDate";
  @SerializedName(SERIALIZED_NAME_TARIFF_FIX_DATE)
  @jakarta.annotation.Nullable
  private String tariffFixDate;

  public static final String SERIALIZED_NAME_TARIFF_LOWER_DATE = "tariffLowerDate";
  @SerializedName(SERIALIZED_NAME_TARIFF_LOWER_DATE)
  @jakarta.annotation.Nullable
  private String tariffLowerDate;

  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner() {
  }

  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner date(@jakarta.annotation.Nullable String date) {
    this.date = date;
    return this;
  }

  /**
   * Дата, за которую был расчёт или перерасчёт
   * @return date
   */
  @jakarta.annotation.Nullable
  public String getDate() {
    return date;
  }

  public void setDate(@jakarta.annotation.Nullable String date) {
    this.date = date;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner logWarehouseCoef(@jakarta.annotation.Nullable BigDecimal logWarehouseCoef) {
    this.logWarehouseCoef = logWarehouseCoef;
    return this;
  }

  /**
   * Коэффициент логистики и хранения. [На данный момент](https://dev.wildberries.ru/release-notes?id&#x3D;570) может быть только &#x60;0&#x60;
   * @return logWarehouseCoef
   */
  @jakarta.annotation.Nullable
  public BigDecimal getLogWarehouseCoef() {
    return logWarehouseCoef;
  }

  public void setLogWarehouseCoef(@jakarta.annotation.Nullable BigDecimal logWarehouseCoef) {
    this.logWarehouseCoef = logWarehouseCoef;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner officeId(@jakarta.annotation.Nullable Integer officeId) {
    this.officeId = officeId;
    return this;
  }

  /**
   * ID склада. [На данный момент](https://dev.wildberries.ru/release-notes?id&#x3D;570) может быть только &#x60;0&#x60;
   * @return officeId
   */
  @jakarta.annotation.Nullable
  public Integer getOfficeId() {
    return officeId;
  }

  public void setOfficeId(@jakarta.annotation.Nullable Integer officeId) {
    this.officeId = officeId;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner warehouse(@jakarta.annotation.Nullable String warehouse) {
    this.warehouse = warehouse;
    return this;
  }

  /**
   * Название склада. [На данный момент](https://dev.wildberries.ru/release-notes?id&#x3D;570) может быть только &#x60;Склад WB РФ&#x60;
   * @return warehouse
   */
  @jakarta.annotation.Nullable
  public String getWarehouse() {
    return warehouse;
  }

  public void setWarehouse(@jakarta.annotation.Nullable String warehouse) {
    this.warehouse = warehouse;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner warehouseCoef(@jakarta.annotation.Nullable BigDecimal warehouseCoef) {
    this.warehouseCoef = warehouseCoef;
    return this;
  }

  /**
   * Коэффициент хранения
   * @return warehouseCoef
   */
  @jakarta.annotation.Nullable
  public BigDecimal getWarehouseCoef() {
    return warehouseCoef;
  }

  public void setWarehouseCoef(@jakarta.annotation.Nullable BigDecimal warehouseCoef) {
    this.warehouseCoef = warehouseCoef;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner giId(@jakarta.annotation.Nullable Integer giId) {
    this.giId = giId;
    return this;
  }

  /**
   * ID поставки
   * @return giId
   */
  @jakarta.annotation.Nullable
  public Integer getGiId() {
    return giId;
  }

  public void setGiId(@jakarta.annotation.Nullable Integer giId) {
    this.giId = giId;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner chrtId(@jakarta.annotation.Nullable Integer chrtId) {
    this.chrtId = chrtId;
    return this;
  }

  /**
   * ID размера для этого артикула WB
   * @return chrtId
   */
  @jakarta.annotation.Nullable
  public Integer getChrtId() {
    return chrtId;
  }

  public void setChrtId(@jakarta.annotation.Nullable Integer chrtId) {
    this.chrtId = chrtId;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner size(@jakarta.annotation.Nullable String size) {
    this.size = size;
    return this;
  }

  /**
   * Размер (&#x60;techSize&#x60; в карточке товара)
   * @return size
   */
  @jakarta.annotation.Nullable
  public String getSize() {
    return size;
  }

  public void setSize(@jakarta.annotation.Nullable String size) {
    this.size = size;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner barcode(@jakarta.annotation.Nullable String barcode) {
    this.barcode = barcode;
    return this;
  }

  /**
   * Баркод
   * @return barcode
   */
  @jakarta.annotation.Nullable
  public String getBarcode() {
    return barcode;
  }

  public void setBarcode(@jakarta.annotation.Nullable String barcode) {
    this.barcode = barcode;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner subject(@jakarta.annotation.Nullable String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Предмет
   * @return subject
   */
  @jakarta.annotation.Nullable
  public String getSubject() {
    return subject;
  }

  public void setSubject(@jakarta.annotation.Nullable String subject) {
    this.subject = subject;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner brand(@jakarta.annotation.Nullable String brand) {
    this.brand = brand;
    return this;
  }

  /**
   * Бренд
   * @return brand
   */
  @jakarta.annotation.Nullable
  public String getBrand() {
    return brand;
  }

  public void setBrand(@jakarta.annotation.Nullable String brand) {
    this.brand = brand;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner vendorCode(@jakarta.annotation.Nullable String vendorCode) {
    this.vendorCode = vendorCode;
    return this;
  }

  /**
   * Артикул продавца
   * @return vendorCode
   */
  @jakarta.annotation.Nullable
  public String getVendorCode() {
    return vendorCode;
  }

  public void setVendorCode(@jakarta.annotation.Nullable String vendorCode) {
    this.vendorCode = vendorCode;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner nmId(@jakarta.annotation.Nullable Integer nmId) {
    this.nmId = nmId;
    return this;
  }

  /**
   * Артикул WB
   * @return nmId
   */
  @jakarta.annotation.Nullable
  public Integer getNmId() {
    return nmId;
  }

  public void setNmId(@jakarta.annotation.Nullable Integer nmId) {
    this.nmId = nmId;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner volume(@jakarta.annotation.Nullable BigDecimal volume) {
    this.volume = volume;
    return this;
  }

  /**
   * Объём товара
   * @return volume
   */
  @jakarta.annotation.Nullable
  public BigDecimal getVolume() {
    return volume;
  }

  public void setVolume(@jakarta.annotation.Nullable BigDecimal volume) {
    this.volume = volume;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner calcType(@jakarta.annotation.Nullable String calcType) {
    this.calcType = calcType;
    return this;
  }

  /**
   * Способ расчёта
   * @return calcType
   */
  @jakarta.annotation.Nullable
  public String getCalcType() {
    return calcType;
  }

  public void setCalcType(@jakarta.annotation.Nullable String calcType) {
    this.calcType = calcType;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner warehousePrice(@jakarta.annotation.Nullable BigDecimal warehousePrice) {
    this.warehousePrice = warehousePrice;
    return this;
  }

  /**
   * Сумма хранения
   * @return warehousePrice
   */
  @jakarta.annotation.Nullable
  public BigDecimal getWarehousePrice() {
    return warehousePrice;
  }

  public void setWarehousePrice(@jakarta.annotation.Nullable BigDecimal warehousePrice) {
    this.warehousePrice = warehousePrice;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner barcodesCount(@jakarta.annotation.Nullable Integer barcodesCount) {
    this.barcodesCount = barcodesCount;
    return this;
  }

  /**
   * Количество единиц товара (штук), подлежащих тарифицированию за расчётные сутки
   * @return barcodesCount
   */
  @jakarta.annotation.Nullable
  public Integer getBarcodesCount() {
    return barcodesCount;
  }

  public void setBarcodesCount(@jakarta.annotation.Nullable Integer barcodesCount) {
    this.barcodesCount = barcodesCount;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner palletPlaceCode(@jakarta.annotation.Nullable Integer palletPlaceCode) {
    this.palletPlaceCode = palletPlaceCode;
    return this;
  }

  /**
   * Код паллетоместа. [На данный момент](https://dev.wildberries.ru/release-notes?id&#x3D;570) может быть только &#x60;0&#x60;
   * @return palletPlaceCode
   */
  @jakarta.annotation.Nullable
  public Integer getPalletPlaceCode() {
    return palletPlaceCode;
  }

  public void setPalletPlaceCode(@jakarta.annotation.Nullable Integer palletPlaceCode) {
    this.palletPlaceCode = palletPlaceCode;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner palletCount(@jakarta.annotation.Nullable BigDecimal palletCount) {
    this.palletCount = palletCount;
    return this;
  }

  /**
   * Количество паллет
   * @return palletCount
   */
  @jakarta.annotation.Nullable
  public BigDecimal getPalletCount() {
    return palletCount;
  }

  public void setPalletCount(@jakarta.annotation.Nullable BigDecimal palletCount) {
    this.palletCount = palletCount;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner originalDate(@jakarta.annotation.Nullable String originalDate) {
    this.originalDate = originalDate;
    return this;
  }

  /**
   * Если был перерасчёт, это дата первоначального расчёта. Если перерасчёта не было, совпадает с &#x60;date&#x60;
   * @return originalDate
   */
  @jakarta.annotation.Nullable
  public String getOriginalDate() {
    return originalDate;
  }

  public void setOriginalDate(@jakarta.annotation.Nullable String originalDate) {
    this.originalDate = originalDate;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner loyaltyDiscount(@jakarta.annotation.Nullable BigDecimal loyaltyDiscount) {
    this.loyaltyDiscount = loyaltyDiscount;
    return this;
  }

  /**
   * Скидка программы лояльности, ₽
   * @return loyaltyDiscount
   */
  @jakarta.annotation.Nullable
  public BigDecimal getLoyaltyDiscount() {
    return loyaltyDiscount;
  }

  public void setLoyaltyDiscount(@jakarta.annotation.Nullable BigDecimal loyaltyDiscount) {
    this.loyaltyDiscount = loyaltyDiscount;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner tariffFixDate(@jakarta.annotation.Nullable String tariffFixDate) {
    this.tariffFixDate = tariffFixDate;
    return this;
  }

  /**
   * Дата фиксации тарифа
   * @return tariffFixDate
   */
  @jakarta.annotation.Nullable
  public String getTariffFixDate() {
    return tariffFixDate;
  }

  public void setTariffFixDate(@jakarta.annotation.Nullable String tariffFixDate) {
    this.tariffFixDate = tariffFixDate;
  }


  public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner tariffLowerDate(@jakarta.annotation.Nullable String tariffLowerDate) {
    this.tariffLowerDate = tariffLowerDate;
    return this;
  }

  /**
   * Дата понижения тарифа
   * @return tariffLowerDate
   */
  @jakarta.annotation.Nullable
  public String getTariffLowerDate() {
    return tariffLowerDate;
  }

  public void setTariffLowerDate(@jakarta.annotation.Nullable String tariffLowerDate) {
    this.tariffLowerDate = tariffLowerDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetV1PaidStorageTasksTaskIdDownloadResponse200Inner getV1PaidStorageTasksTaskIdDownloadResponse200Inner = (GetV1PaidStorageTasksTaskIdDownloadResponse200Inner) o;
    return Objects.equals(this.date, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.date) &&
        Objects.equals(this.logWarehouseCoef, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.logWarehouseCoef) &&
        Objects.equals(this.officeId, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.officeId) &&
        Objects.equals(this.warehouse, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.warehouse) &&
        Objects.equals(this.warehouseCoef, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.warehouseCoef) &&
        Objects.equals(this.giId, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.giId) &&
        Objects.equals(this.chrtId, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.chrtId) &&
        Objects.equals(this.size, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.size) &&
        Objects.equals(this.barcode, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.barcode) &&
        Objects.equals(this.subject, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.subject) &&
        Objects.equals(this.brand, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.brand) &&
        Objects.equals(this.vendorCode, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.vendorCode) &&
        Objects.equals(this.nmId, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.nmId) &&
        Objects.equals(this.volume, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.volume) &&
        Objects.equals(this.calcType, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.calcType) &&
        Objects.equals(this.warehousePrice, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.warehousePrice) &&
        Objects.equals(this.barcodesCount, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.barcodesCount) &&
        Objects.equals(this.palletPlaceCode, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.palletPlaceCode) &&
        Objects.equals(this.palletCount, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.palletCount) &&
        Objects.equals(this.originalDate, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.originalDate) &&
        Objects.equals(this.loyaltyDiscount, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.loyaltyDiscount) &&
        Objects.equals(this.tariffFixDate, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.tariffFixDate) &&
        Objects.equals(this.tariffLowerDate, getV1PaidStorageTasksTaskIdDownloadResponse200Inner.tariffLowerDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, logWarehouseCoef, officeId, warehouse, warehouseCoef, giId, chrtId, size, barcode, subject, brand, vendorCode, nmId, volume, calcType, warehousePrice, barcodesCount, palletPlaceCode, palletCount, originalDate, loyaltyDiscount, tariffFixDate, tariffLowerDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetV1PaidStorageTasksTaskIdDownloadResponse200Inner {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    logWarehouseCoef: ").append(toIndentedString(logWarehouseCoef)).append("\n");
    sb.append("    officeId: ").append(toIndentedString(officeId)).append("\n");
    sb.append("    warehouse: ").append(toIndentedString(warehouse)).append("\n");
    sb.append("    warehouseCoef: ").append(toIndentedString(warehouseCoef)).append("\n");
    sb.append("    giId: ").append(toIndentedString(giId)).append("\n");
    sb.append("    chrtId: ").append(toIndentedString(chrtId)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    barcode: ").append(toIndentedString(barcode)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    vendorCode: ").append(toIndentedString(vendorCode)).append("\n");
    sb.append("    nmId: ").append(toIndentedString(nmId)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    calcType: ").append(toIndentedString(calcType)).append("\n");
    sb.append("    warehousePrice: ").append(toIndentedString(warehousePrice)).append("\n");
    sb.append("    barcodesCount: ").append(toIndentedString(barcodesCount)).append("\n");
    sb.append("    palletPlaceCode: ").append(toIndentedString(palletPlaceCode)).append("\n");
    sb.append("    palletCount: ").append(toIndentedString(palletCount)).append("\n");
    sb.append("    originalDate: ").append(toIndentedString(originalDate)).append("\n");
    sb.append("    loyaltyDiscount: ").append(toIndentedString(loyaltyDiscount)).append("\n");
    sb.append("    tariffFixDate: ").append(toIndentedString(tariffFixDate)).append("\n");
    sb.append("    tariffLowerDate: ").append(toIndentedString(tariffLowerDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date");
    openapiFields.add("logWarehouseCoef");
    openapiFields.add("officeId");
    openapiFields.add("warehouse");
    openapiFields.add("warehouseCoef");
    openapiFields.add("giId");
    openapiFields.add("chrtId");
    openapiFields.add("size");
    openapiFields.add("barcode");
    openapiFields.add("subject");
    openapiFields.add("brand");
    openapiFields.add("vendorCode");
    openapiFields.add("nmId");
    openapiFields.add("volume");
    openapiFields.add("calcType");
    openapiFields.add("warehousePrice");
    openapiFields.add("barcodesCount");
    openapiFields.add("palletPlaceCode");
    openapiFields.add("palletCount");
    openapiFields.add("originalDate");
    openapiFields.add("loyaltyDiscount");
    openapiFields.add("tariffFixDate");
    openapiFields.add("tariffLowerDate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetV1PaidStorageTasksTaskIdDownloadResponse200Inner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetV1PaidStorageTasksTaskIdDownloadResponse200Inner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetV1PaidStorageTasksTaskIdDownloadResponse200Inner is not found in the empty JSON string", GetV1PaidStorageTasksTaskIdDownloadResponse200Inner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetV1PaidStorageTasksTaskIdDownloadResponse200Inner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetV1PaidStorageTasksTaskIdDownloadResponse200Inner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("date") != null && !jsonObj.get("date").isJsonNull()) && !jsonObj.get("date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date").toString()));
      }
      if ((jsonObj.get("warehouse") != null && !jsonObj.get("warehouse").isJsonNull()) && !jsonObj.get("warehouse").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `warehouse` to be a primitive type in the JSON string but got `%s`", jsonObj.get("warehouse").toString()));
      }
      if ((jsonObj.get("size") != null && !jsonObj.get("size").isJsonNull()) && !jsonObj.get("size").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `size` to be a primitive type in the JSON string but got `%s`", jsonObj.get("size").toString()));
      }
      if ((jsonObj.get("barcode") != null && !jsonObj.get("barcode").isJsonNull()) && !jsonObj.get("barcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `barcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("barcode").toString()));
      }
      if ((jsonObj.get("subject") != null && !jsonObj.get("subject").isJsonNull()) && !jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if ((jsonObj.get("brand") != null && !jsonObj.get("brand").isJsonNull()) && !jsonObj.get("brand").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brand` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brand").toString()));
      }
      if ((jsonObj.get("vendorCode") != null && !jsonObj.get("vendorCode").isJsonNull()) && !jsonObj.get("vendorCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vendorCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vendorCode").toString()));
      }
      if ((jsonObj.get("calcType") != null && !jsonObj.get("calcType").isJsonNull()) && !jsonObj.get("calcType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `calcType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("calcType").toString()));
      }
      if ((jsonObj.get("originalDate") != null && !jsonObj.get("originalDate").isJsonNull()) && !jsonObj.get("originalDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `originalDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("originalDate").toString()));
      }
      if ((jsonObj.get("tariffFixDate") != null && !jsonObj.get("tariffFixDate").isJsonNull()) && !jsonObj.get("tariffFixDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tariffFixDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tariffFixDate").toString()));
      }
      if ((jsonObj.get("tariffLowerDate") != null && !jsonObj.get("tariffLowerDate").isJsonNull()) && !jsonObj.get("tariffLowerDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tariffLowerDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tariffLowerDate").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetV1PaidStorageTasksTaskIdDownloadResponse200Inner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetV1PaidStorageTasksTaskIdDownloadResponse200Inner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetV1PaidStorageTasksTaskIdDownloadResponse200Inner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetV1PaidStorageTasksTaskIdDownloadResponse200Inner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetV1PaidStorageTasksTaskIdDownloadResponse200Inner>() {
           @Override
           public void write(JsonWriter out, GetV1PaidStorageTasksTaskIdDownloadResponse200Inner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetV1PaidStorageTasksTaskIdDownloadResponse200Inner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetV1PaidStorageTasksTaskIdDownloadResponse200Inner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetV1PaidStorageTasksTaskIdDownloadResponse200Inner
   * @throws IOException if the JSON string is invalid with respect to GetV1PaidStorageTasksTaskIdDownloadResponse200Inner
   */
  public static GetV1PaidStorageTasksTaskIdDownloadResponse200Inner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetV1PaidStorageTasksTaskIdDownloadResponse200Inner.class);
  }

  /**
   * Convert an instance of GetV1PaidStorageTasksTaskIdDownloadResponse200Inner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

