/*
 * Аналитика и данные
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)В разделе описаны методы получения: 1. [Воронки продаж](/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](/openapi/analytics#tag/stocksReport) 5. [Оценки товара](/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.valeryverkhoturov.wbapi.analytics.auth;

import io.github.valeryverkhoturov.wbapi.analytics.Pair;
import io.github.valeryverkhoturov.wbapi.analytics.ApiException;

import okhttp3.Credentials;

import java.net.URI;
import java.util.Map;
import java.util.List;

public class HttpBasicAuth implements Authentication {
    private String username;
    private String password;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams, Map<String, String> cookieParams,
                              String payload, String method, URI uri) throws ApiException {
        if (username == null && password == null) {
            return;
        }
        headerParams.put("Authorization", Credentials.basic(
            username == null ? "" : username,
            password == null ? "" : password));
    }
}
