/*
Заказы FBS

С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете: - получать информацию о [сборочных заданиях](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsAssemblyOrders) и их статусах, отменять сборочные задания, получать стикеры - добавлять, редактировать и удалять [идентификаторы маркировки](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsLabelIdentifiers) сборочных заданий - управлять [поставками](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsSupplies) - создавать, редактировать и удалять [пропуска](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsPasses) на склады WB Вы можете протестировать методы заказов FBS в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/marketplaceFbs) для эмуляции действий пользователя  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs) по работе с **заказами FBS**  Узнать больше о заказах FBS можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d)

API version: order
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders_fbs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner{}

// GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner struct for GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner
type GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner struct {
	// ID предмета
	SubjectId int32 `json:"subjectId"`
}

type _GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner

// NewGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner instantiates a new GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner(subjectId int32) *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner {
	this := GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner{}
	this.SubjectId = subjectId
	return &this
}

// NewGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInnerWithDefaults instantiates a new GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInnerWithDefaults() *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner {
	this := GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner{}
	return &this
}

// GetSubjectId returns the SubjectId field value
func (o *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) GetSubjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SubjectId
}

// GetSubjectIdOk returns a tuple with the SubjectId field value
// and a boolean to check if the value has been set.
func (o *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) GetSubjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectId, true
}

// SetSubjectId sets field value
func (o *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) SetSubjectId(v int32) {
	o.SubjectId = v
}

func (o GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subjectId"] = o.SubjectId
	return toSerialize, nil
}

func (o *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subjectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner := _GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner)

	if err != nil {
		return err
	}

	*o = GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner(varGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner)

	return err
}

type NullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner struct {
	value *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner
	isSet bool
}

func (v NullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) Get() *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner {
	return v.value
}

func (v *NullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) Set(val *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner(val *GetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) *NullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner {
	return &NullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner{value: val, isSet: true}
}

func (v NullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestrictedResponse200DataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


