/*
Заказы FBS

С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете: - получать информацию о [сборочных заданиях](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsAssemblyOrders) и их статусах, отменять сборочные задания, получать стикеры - добавлять, редактировать и удалять [идентификаторы маркировки](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsLabelIdentifiers) сборочных заданий - управлять [поставками](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsSupplies) - создавать, редактировать и удалять [пропуска](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsPasses) на склады WB Вы можете протестировать методы заказов FBS в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/marketplaceFbs) для эмуляции действий пользователя  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs) по работе с **заказами FBS**  Узнать больше о заказах FBS можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d)

API version: order
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders_fbs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PatchV3FbsSuppliesWaybillRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchV3FbsSuppliesWaybillRequest{}

// PatchV3FbsSuppliesWaybillRequest struct for PatchV3FbsSuppliesWaybillRequest
type PatchV3FbsSuppliesWaybillRequest struct {
	Data []UpdateSupplyWaybill `json:"data"`
}

type _PatchV3FbsSuppliesWaybillRequest PatchV3FbsSuppliesWaybillRequest

// NewPatchV3FbsSuppliesWaybillRequest instantiates a new PatchV3FbsSuppliesWaybillRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchV3FbsSuppliesWaybillRequest(data []UpdateSupplyWaybill) *PatchV3FbsSuppliesWaybillRequest {
	this := PatchV3FbsSuppliesWaybillRequest{}
	this.Data = data
	return &this
}

// NewPatchV3FbsSuppliesWaybillRequestWithDefaults instantiates a new PatchV3FbsSuppliesWaybillRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchV3FbsSuppliesWaybillRequestWithDefaults() *PatchV3FbsSuppliesWaybillRequest {
	this := PatchV3FbsSuppliesWaybillRequest{}
	return &this
}

// GetData returns the Data field value
func (o *PatchV3FbsSuppliesWaybillRequest) GetData() []UpdateSupplyWaybill {
	if o == nil {
		var ret []UpdateSupplyWaybill
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PatchV3FbsSuppliesWaybillRequest) GetDataOk() ([]UpdateSupplyWaybill, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PatchV3FbsSuppliesWaybillRequest) SetData(v []UpdateSupplyWaybill) {
	o.Data = v
}

func (o PatchV3FbsSuppliesWaybillRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchV3FbsSuppliesWaybillRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PatchV3FbsSuppliesWaybillRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchV3FbsSuppliesWaybillRequest := _PatchV3FbsSuppliesWaybillRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchV3FbsSuppliesWaybillRequest)

	if err != nil {
		return err
	}

	*o = PatchV3FbsSuppliesWaybillRequest(varPatchV3FbsSuppliesWaybillRequest)

	return err
}

type NullablePatchV3FbsSuppliesWaybillRequest struct {
	value *PatchV3FbsSuppliesWaybillRequest
	isSet bool
}

func (v NullablePatchV3FbsSuppliesWaybillRequest) Get() *PatchV3FbsSuppliesWaybillRequest {
	return v.value
}

func (v *NullablePatchV3FbsSuppliesWaybillRequest) Set(val *PatchV3FbsSuppliesWaybillRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchV3FbsSuppliesWaybillRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchV3FbsSuppliesWaybillRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchV3FbsSuppliesWaybillRequest(val *PatchV3FbsSuppliesWaybillRequest) *NullablePatchV3FbsSuppliesWaybillRequest {
	return &NullablePatchV3FbsSuppliesWaybillRequest{value: val, isSet: true}
}

func (v NullablePatchV3FbsSuppliesWaybillRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchV3FbsSuppliesWaybillRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


