/*
Аналитика и данные

Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PostV3SalesFunnelProductsHistoryResponse200Inner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV3SalesFunnelProductsHistoryResponse200Inner{}

// PostV3SalesFunnelProductsHistoryResponse200Inner struct for PostV3SalesFunnelProductsHistoryResponse200Inner
type PostV3SalesFunnelProductsHistoryResponse200Inner struct {
	Product PostV3SalesFunnelProductsHistoryResponse200InnerProduct `json:"product"`
	// Статистика за период
	History []History `json:"history"`
	// Валюта отчёта
	Currency string `json:"currency"`
}

type _PostV3SalesFunnelProductsHistoryResponse200Inner PostV3SalesFunnelProductsHistoryResponse200Inner

// NewPostV3SalesFunnelProductsHistoryResponse200Inner instantiates a new PostV3SalesFunnelProductsHistoryResponse200Inner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV3SalesFunnelProductsHistoryResponse200Inner(product PostV3SalesFunnelProductsHistoryResponse200InnerProduct, history []History, currency string) *PostV3SalesFunnelProductsHistoryResponse200Inner {
	this := PostV3SalesFunnelProductsHistoryResponse200Inner{}
	this.Product = product
	this.History = history
	this.Currency = currency
	return &this
}

// NewPostV3SalesFunnelProductsHistoryResponse200InnerWithDefaults instantiates a new PostV3SalesFunnelProductsHistoryResponse200Inner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV3SalesFunnelProductsHistoryResponse200InnerWithDefaults() *PostV3SalesFunnelProductsHistoryResponse200Inner {
	this := PostV3SalesFunnelProductsHistoryResponse200Inner{}
	return &this
}

// GetProduct returns the Product field value
func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) GetProduct() PostV3SalesFunnelProductsHistoryResponse200InnerProduct {
	if o == nil {
		var ret PostV3SalesFunnelProductsHistoryResponse200InnerProduct
		return ret
	}

	return o.Product
}

// GetProductOk returns a tuple with the Product field value
// and a boolean to check if the value has been set.
func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) GetProductOk() (*PostV3SalesFunnelProductsHistoryResponse200InnerProduct, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Product, true
}

// SetProduct sets field value
func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) SetProduct(v PostV3SalesFunnelProductsHistoryResponse200InnerProduct) {
	o.Product = v
}

// GetHistory returns the History field value
func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) GetHistory() []History {
	if o == nil {
		var ret []History
		return ret
	}

	return o.History
}

// GetHistoryOk returns a tuple with the History field value
// and a boolean to check if the value has been set.
func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) GetHistoryOk() ([]History, bool) {
	if o == nil {
		return nil, false
	}
	return o.History, true
}

// SetHistory sets field value
func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) SetHistory(v []History) {
	o.History = v
}

// GetCurrency returns the Currency field value
func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) SetCurrency(v string) {
	o.Currency = v
}

func (o PostV3SalesFunnelProductsHistoryResponse200Inner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV3SalesFunnelProductsHistoryResponse200Inner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["product"] = o.Product
	toSerialize["history"] = o.History
	toSerialize["currency"] = o.Currency
	return toSerialize, nil
}

func (o *PostV3SalesFunnelProductsHistoryResponse200Inner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"product",
		"history",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostV3SalesFunnelProductsHistoryResponse200Inner := _PostV3SalesFunnelProductsHistoryResponse200Inner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostV3SalesFunnelProductsHistoryResponse200Inner)

	if err != nil {
		return err
	}

	*o = PostV3SalesFunnelProductsHistoryResponse200Inner(varPostV3SalesFunnelProductsHistoryResponse200Inner)

	return err
}

type NullablePostV3SalesFunnelProductsHistoryResponse200Inner struct {
	value *PostV3SalesFunnelProductsHistoryResponse200Inner
	isSet bool
}

func (v NullablePostV3SalesFunnelProductsHistoryResponse200Inner) Get() *PostV3SalesFunnelProductsHistoryResponse200Inner {
	return v.value
}

func (v *NullablePostV3SalesFunnelProductsHistoryResponse200Inner) Set(val *PostV3SalesFunnelProductsHistoryResponse200Inner) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV3SalesFunnelProductsHistoryResponse200Inner) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV3SalesFunnelProductsHistoryResponse200Inner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV3SalesFunnelProductsHistoryResponse200Inner(val *PostV3SalesFunnelProductsHistoryResponse200Inner) *NullablePostV3SalesFunnelProductsHistoryResponse200Inner {
	return &NullablePostV3SalesFunnelProductsHistoryResponse200Inner{value: val, isSet: true}
}

func (v NullablePostV3SalesFunnelProductsHistoryResponse200Inner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV3SalesFunnelProductsHistoryResponse200Inner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
