/*
Аналитика и данные

Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PostV3SalesFunnelProductsHistoryResponse200InnerProduct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV3SalesFunnelProductsHistoryResponse200InnerProduct{}

// PostV3SalesFunnelProductsHistoryResponse200InnerProduct struct for PostV3SalesFunnelProductsHistoryResponse200InnerProduct
type PostV3SalesFunnelProductsHistoryResponse200InnerProduct struct {
	// Артикул WB
	NmId int64 `json:"nmId"`
	// Название карточки товара
	Title string `json:"title"`
	// Артикул продавца
	VendorCode string `json:"vendorCode"`
	// Бренд
	BrandName string `json:"brandName"`
	// ID предмета
	SubjectId int32 `json:"subjectId"`
	// Название предмета
	SubjectName string `json:"subjectName"`
}

type _PostV3SalesFunnelProductsHistoryResponse200InnerProduct PostV3SalesFunnelProductsHistoryResponse200InnerProduct

// NewPostV3SalesFunnelProductsHistoryResponse200InnerProduct instantiates a new PostV3SalesFunnelProductsHistoryResponse200InnerProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV3SalesFunnelProductsHistoryResponse200InnerProduct(nmId int64, title string, vendorCode string, brandName string, subjectId int32, subjectName string) *PostV3SalesFunnelProductsHistoryResponse200InnerProduct {
	this := PostV3SalesFunnelProductsHistoryResponse200InnerProduct{}
	this.NmId = nmId
	this.Title = title
	this.VendorCode = vendorCode
	this.BrandName = brandName
	this.SubjectId = subjectId
	this.SubjectName = subjectName
	return &this
}

// NewPostV3SalesFunnelProductsHistoryResponse200InnerProductWithDefaults instantiates a new PostV3SalesFunnelProductsHistoryResponse200InnerProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV3SalesFunnelProductsHistoryResponse200InnerProductWithDefaults() *PostV3SalesFunnelProductsHistoryResponse200InnerProduct {
	this := PostV3SalesFunnelProductsHistoryResponse200InnerProduct{}
	return &this
}

// GetNmId returns the NmId field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetNmId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NmId
}

// GetNmIdOk returns a tuple with the NmId field value
// and a boolean to check if the value has been set.
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetNmIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NmId, true
}

// SetNmId sets field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) SetNmId(v int64) {
	o.NmId = v
}

// GetTitle returns the Title field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) SetTitle(v string) {
	o.Title = v
}

// GetVendorCode returns the VendorCode field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetVendorCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VendorCode
}

// GetVendorCodeOk returns a tuple with the VendorCode field value
// and a boolean to check if the value has been set.
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetVendorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VendorCode, true
}

// SetVendorCode sets field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) SetVendorCode(v string) {
	o.VendorCode = v
}

// GetBrandName returns the BrandName field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetBrandName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BrandName
}

// GetBrandNameOk returns a tuple with the BrandName field value
// and a boolean to check if the value has been set.
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetBrandNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrandName, true
}

// SetBrandName sets field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) SetBrandName(v string) {
	o.BrandName = v
}

// GetSubjectId returns the SubjectId field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetSubjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SubjectId
}

// GetSubjectIdOk returns a tuple with the SubjectId field value
// and a boolean to check if the value has been set.
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetSubjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectId, true
}

// SetSubjectId sets field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) SetSubjectId(v int32) {
	o.SubjectId = v
}

// GetSubjectName returns the SubjectName field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetSubjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectName
}

// GetSubjectNameOk returns a tuple with the SubjectName field value
// and a boolean to check if the value has been set.
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) GetSubjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectName, true
}

// SetSubjectName sets field value
func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) SetSubjectName(v string) {
	o.SubjectName = v
}

func (o PostV3SalesFunnelProductsHistoryResponse200InnerProduct) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV3SalesFunnelProductsHistoryResponse200InnerProduct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nmId"] = o.NmId
	toSerialize["title"] = o.Title
	toSerialize["vendorCode"] = o.VendorCode
	toSerialize["brandName"] = o.BrandName
	toSerialize["subjectId"] = o.SubjectId
	toSerialize["subjectName"] = o.SubjectName
	return toSerialize, nil
}

func (o *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nmId",
		"title",
		"vendorCode",
		"brandName",
		"subjectId",
		"subjectName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostV3SalesFunnelProductsHistoryResponse200InnerProduct := _PostV3SalesFunnelProductsHistoryResponse200InnerProduct{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostV3SalesFunnelProductsHistoryResponse200InnerProduct)

	if err != nil {
		return err
	}

	*o = PostV3SalesFunnelProductsHistoryResponse200InnerProduct(varPostV3SalesFunnelProductsHistoryResponse200InnerProduct)

	return err
}

type NullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct struct {
	value *PostV3SalesFunnelProductsHistoryResponse200InnerProduct
	isSet bool
}

func (v NullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct) Get() *PostV3SalesFunnelProductsHistoryResponse200InnerProduct {
	return v.value
}

func (v *NullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct) Set(val *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct(val *PostV3SalesFunnelProductsHistoryResponse200InnerProduct) *NullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct {
	return &NullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct{value: val, isSet: true}
}

func (v NullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV3SalesFunnelProductsHistoryResponse200InnerProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
