/*
Аналитика и данные

Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"encoding/json"
)

// checks if the InventoryWbResponseItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryWbResponseItemsInner{}

// InventoryWbResponseItemsInner struct for InventoryWbResponseItemsInner
type InventoryWbResponseItemsInner struct {
	// Артикул WB
	NmId *int64 `json:"nmId,omitempty"`
	// ID размера
	ChrtId *int32 `json:"chrtId,omitempty"`
	// ID склада. [На данный момент](https://dev.wildberries.ru/release-notes?id=570) может быть только `-999999`
	WarehouseId *int64 `json:"warehouseId,omitempty"`
	// Название склада. [На данный момент](https://dev.wildberries.ru/release-notes?id=570) может быть только `Склад WB`
	WarehouseName *string `json:"warehouseName,omitempty"`
	// Регион отгрузки. [На данный момент](https://dev.wildberries.ru/release-notes?id=570) может быть только `Склад WB`
	RegionName *string `json:"regionName,omitempty"`
	// Количество товара на складе, доступное клиентам для добавления в корзину
	Quantity *int32 `json:"quantity,omitempty"`
	// В пути к клиенту
	InWayToClient *int32 `json:"inWayToClient,omitempty"`
	// В пути от клиента
	InWayFromClient *int32 `json:"inWayFromClient,omitempty"`
}

// NewInventoryWbResponseItemsInner instantiates a new InventoryWbResponseItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryWbResponseItemsInner() *InventoryWbResponseItemsInner {
	this := InventoryWbResponseItemsInner{}
	return &this
}

// NewInventoryWbResponseItemsInnerWithDefaults instantiates a new InventoryWbResponseItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryWbResponseItemsInnerWithDefaults() *InventoryWbResponseItemsInner {
	this := InventoryWbResponseItemsInner{}
	return &this
}

// GetNmId returns the NmId field value if set, zero value otherwise.
func (o *InventoryWbResponseItemsInner) GetNmId() int64 {
	if o == nil || IsNil(o.NmId) {
		var ret int64
		return ret
	}
	return *o.NmId
}

// GetNmIdOk returns a tuple with the NmId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryWbResponseItemsInner) GetNmIdOk() (*int64, bool) {
	if o == nil || IsNil(o.NmId) {
		return nil, false
	}
	return o.NmId, true
}

// HasNmId returns a boolean if a field has been set.
func (o *InventoryWbResponseItemsInner) HasNmId() bool {
	if o != nil && !IsNil(o.NmId) {
		return true
	}

	return false
}

// SetNmId gets a reference to the given int64 and assigns it to the NmId field.
func (o *InventoryWbResponseItemsInner) SetNmId(v int64) {
	o.NmId = &v
}

// GetChrtId returns the ChrtId field value if set, zero value otherwise.
func (o *InventoryWbResponseItemsInner) GetChrtId() int32 {
	if o == nil || IsNil(o.ChrtId) {
		var ret int32
		return ret
	}
	return *o.ChrtId
}

// GetChrtIdOk returns a tuple with the ChrtId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryWbResponseItemsInner) GetChrtIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ChrtId) {
		return nil, false
	}
	return o.ChrtId, true
}

// HasChrtId returns a boolean if a field has been set.
func (o *InventoryWbResponseItemsInner) HasChrtId() bool {
	if o != nil && !IsNil(o.ChrtId) {
		return true
	}

	return false
}

// SetChrtId gets a reference to the given int32 and assigns it to the ChrtId field.
func (o *InventoryWbResponseItemsInner) SetChrtId(v int32) {
	o.ChrtId = &v
}

// GetWarehouseId returns the WarehouseId field value if set, zero value otherwise.
func (o *InventoryWbResponseItemsInner) GetWarehouseId() int64 {
	if o == nil || IsNil(o.WarehouseId) {
		var ret int64
		return ret
	}
	return *o.WarehouseId
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryWbResponseItemsInner) GetWarehouseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.WarehouseId) {
		return nil, false
	}
	return o.WarehouseId, true
}

// HasWarehouseId returns a boolean if a field has been set.
func (o *InventoryWbResponseItemsInner) HasWarehouseId() bool {
	if o != nil && !IsNil(o.WarehouseId) {
		return true
	}

	return false
}

// SetWarehouseId gets a reference to the given int64 and assigns it to the WarehouseId field.
func (o *InventoryWbResponseItemsInner) SetWarehouseId(v int64) {
	o.WarehouseId = &v
}

// GetWarehouseName returns the WarehouseName field value if set, zero value otherwise.
func (o *InventoryWbResponseItemsInner) GetWarehouseName() string {
	if o == nil || IsNil(o.WarehouseName) {
		var ret string
		return ret
	}
	return *o.WarehouseName
}

// GetWarehouseNameOk returns a tuple with the WarehouseName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryWbResponseItemsInner) GetWarehouseNameOk() (*string, bool) {
	if o == nil || IsNil(o.WarehouseName) {
		return nil, false
	}
	return o.WarehouseName, true
}

// HasWarehouseName returns a boolean if a field has been set.
func (o *InventoryWbResponseItemsInner) HasWarehouseName() bool {
	if o != nil && !IsNil(o.WarehouseName) {
		return true
	}

	return false
}

// SetWarehouseName gets a reference to the given string and assigns it to the WarehouseName field.
func (o *InventoryWbResponseItemsInner) SetWarehouseName(v string) {
	o.WarehouseName = &v
}

// GetRegionName returns the RegionName field value if set, zero value otherwise.
func (o *InventoryWbResponseItemsInner) GetRegionName() string {
	if o == nil || IsNil(o.RegionName) {
		var ret string
		return ret
	}
	return *o.RegionName
}

// GetRegionNameOk returns a tuple with the RegionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryWbResponseItemsInner) GetRegionNameOk() (*string, bool) {
	if o == nil || IsNil(o.RegionName) {
		return nil, false
	}
	return o.RegionName, true
}

// HasRegionName returns a boolean if a field has been set.
func (o *InventoryWbResponseItemsInner) HasRegionName() bool {
	if o != nil && !IsNil(o.RegionName) {
		return true
	}

	return false
}

// SetRegionName gets a reference to the given string and assigns it to the RegionName field.
func (o *InventoryWbResponseItemsInner) SetRegionName(v string) {
	o.RegionName = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *InventoryWbResponseItemsInner) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryWbResponseItemsInner) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *InventoryWbResponseItemsInner) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *InventoryWbResponseItemsInner) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetInWayToClient returns the InWayToClient field value if set, zero value otherwise.
func (o *InventoryWbResponseItemsInner) GetInWayToClient() int32 {
	if o == nil || IsNil(o.InWayToClient) {
		var ret int32
		return ret
	}
	return *o.InWayToClient
}

// GetInWayToClientOk returns a tuple with the InWayToClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryWbResponseItemsInner) GetInWayToClientOk() (*int32, bool) {
	if o == nil || IsNil(o.InWayToClient) {
		return nil, false
	}
	return o.InWayToClient, true
}

// HasInWayToClient returns a boolean if a field has been set.
func (o *InventoryWbResponseItemsInner) HasInWayToClient() bool {
	if o != nil && !IsNil(o.InWayToClient) {
		return true
	}

	return false
}

// SetInWayToClient gets a reference to the given int32 and assigns it to the InWayToClient field.
func (o *InventoryWbResponseItemsInner) SetInWayToClient(v int32) {
	o.InWayToClient = &v
}

// GetInWayFromClient returns the InWayFromClient field value if set, zero value otherwise.
func (o *InventoryWbResponseItemsInner) GetInWayFromClient() int32 {
	if o == nil || IsNil(o.InWayFromClient) {
		var ret int32
		return ret
	}
	return *o.InWayFromClient
}

// GetInWayFromClientOk returns a tuple with the InWayFromClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryWbResponseItemsInner) GetInWayFromClientOk() (*int32, bool) {
	if o == nil || IsNil(o.InWayFromClient) {
		return nil, false
	}
	return o.InWayFromClient, true
}

// HasInWayFromClient returns a boolean if a field has been set.
func (o *InventoryWbResponseItemsInner) HasInWayFromClient() bool {
	if o != nil && !IsNil(o.InWayFromClient) {
		return true
	}

	return false
}

// SetInWayFromClient gets a reference to the given int32 and assigns it to the InWayFromClient field.
func (o *InventoryWbResponseItemsInner) SetInWayFromClient(v int32) {
	o.InWayFromClient = &v
}

func (o InventoryWbResponseItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryWbResponseItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NmId) {
		toSerialize["nmId"] = o.NmId
	}
	if !IsNil(o.ChrtId) {
		toSerialize["chrtId"] = o.ChrtId
	}
	if !IsNil(o.WarehouseId) {
		toSerialize["warehouseId"] = o.WarehouseId
	}
	if !IsNil(o.WarehouseName) {
		toSerialize["warehouseName"] = o.WarehouseName
	}
	if !IsNil(o.RegionName) {
		toSerialize["regionName"] = o.RegionName
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.InWayToClient) {
		toSerialize["inWayToClient"] = o.InWayToClient
	}
	if !IsNil(o.InWayFromClient) {
		toSerialize["inWayFromClient"] = o.InWayFromClient
	}
	return toSerialize, nil
}

type NullableInventoryWbResponseItemsInner struct {
	value *InventoryWbResponseItemsInner
	isSet bool
}

func (v NullableInventoryWbResponseItemsInner) Get() *InventoryWbResponseItemsInner {
	return v.value
}

func (v *NullableInventoryWbResponseItemsInner) Set(val *InventoryWbResponseItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryWbResponseItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryWbResponseItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryWbResponseItemsInner(val *InventoryWbResponseItemsInner) *NullableInventoryWbResponseItemsInner {
	return &NullableInventoryWbResponseItemsInner{value: val, isSet: true}
}

func (v NullableInventoryWbResponseItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryWbResponseItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
