/*
Аналитика и данные

Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"encoding/json"
)

// checks if the TableCommonMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableCommonMetrics{}

// TableCommonMetrics Метрики
type TableCommonMetrics struct {
	// Заказы, шт.
	OrdersCount *int32 `json:"ordersCount,omitempty"`
	// Заказы, сумма
	OrdersSum *int32 `json:"ordersSum,omitempty"`
	// Среднее количество заказов в день
	AvgOrders *float32 `json:"avgOrders,omitempty"`
	// Среднее количество заказов по месяцам
	AvgOrdersByMonth []FloatGraphByPeriodItem `json:"avgOrdersByMonth,omitempty"`
	// Выкупы, шт.
	BuyoutCount *int32 `json:"buyoutCount,omitempty"`
	// Выкупы, сумма
	BuyoutSum *int32 `json:"buyoutSum,omitempty"`
	// Процент выкупа
	BuyoutPercent *int32 `json:"buyoutPercent,omitempty"`
	// Остатки на текущий день, шт.
	StockCount *int32 `json:"stockCount,omitempty"`
	// Стоимость остатков на текущий день
	StockSum         *int32                              `json:"stockSum,omitempty"`
	SaleRate         *TableCommonMetricsSaleRate         `json:"saleRate,omitempty"`
	AvgStockTurnover *TableCommonMetricsAvgStockTurnover `json:"avgStockTurnover,omitempty"`
	// В пути к клиенту, шт.
	ToClientCount *int32 `json:"toClientCount,omitempty"`
	// В пути от клиента, шт.
	FromClientCount   *int32                               `json:"fromClientCount,omitempty"`
	OfficeMissingTime *TableCommonMetricsOfficeMissingTime `json:"officeMissingTime,omitempty"`
	// Упущенные заказы, шт. Особые случаи:   1. Значение меньше `0` и не равно `-2` — значение не рассчитано   2. Значение `-2` — нулевое значение
	LostOrdersCount *float32 `json:"lostOrdersCount,omitempty"`
	// Упущенные заказы, сумма. Особые случаи:   1. Значение меньше `0` и не равно `-2` — значение не рассчитано   2. Значение `-2` — нулевое значение
	LostOrdersSum *float32 `json:"lostOrdersSum,omitempty"`
	// Упущенные выкупы, шт. Особые случаи:   1. Значение меньше `0` и не равно `-2` — значение не рассчитано   2. Значение `-2` — нулевое значение
	LostBuyoutsCount *float32 `json:"lostBuyoutsCount,omitempty"`
	// Упущенные выкупы, сумма. Особые случаи:   1. Значение меньше `0` и не равно `-2` — значение не рассчитано   2. Значение `-2` — нулевое значение
	LostBuyoutsSum *float32 `json:"lostBuyoutsSum,omitempty"`
}

// NewTableCommonMetrics instantiates a new TableCommonMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableCommonMetrics() *TableCommonMetrics {
	this := TableCommonMetrics{}
	return &this
}

// NewTableCommonMetricsWithDefaults instantiates a new TableCommonMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableCommonMetricsWithDefaults() *TableCommonMetrics {
	this := TableCommonMetrics{}
	return &this
}

// GetOrdersCount returns the OrdersCount field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetOrdersCount() int32 {
	if o == nil || IsNil(o.OrdersCount) {
		var ret int32
		return ret
	}
	return *o.OrdersCount
}

// GetOrdersCountOk returns a tuple with the OrdersCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetOrdersCountOk() (*int32, bool) {
	if o == nil || IsNil(o.OrdersCount) {
		return nil, false
	}
	return o.OrdersCount, true
}

// HasOrdersCount returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasOrdersCount() bool {
	if o != nil && !IsNil(o.OrdersCount) {
		return true
	}

	return false
}

// SetOrdersCount gets a reference to the given int32 and assigns it to the OrdersCount field.
func (o *TableCommonMetrics) SetOrdersCount(v int32) {
	o.OrdersCount = &v
}

// GetOrdersSum returns the OrdersSum field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetOrdersSum() int32 {
	if o == nil || IsNil(o.OrdersSum) {
		var ret int32
		return ret
	}
	return *o.OrdersSum
}

// GetOrdersSumOk returns a tuple with the OrdersSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetOrdersSumOk() (*int32, bool) {
	if o == nil || IsNil(o.OrdersSum) {
		return nil, false
	}
	return o.OrdersSum, true
}

// HasOrdersSum returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasOrdersSum() bool {
	if o != nil && !IsNil(o.OrdersSum) {
		return true
	}

	return false
}

// SetOrdersSum gets a reference to the given int32 and assigns it to the OrdersSum field.
func (o *TableCommonMetrics) SetOrdersSum(v int32) {
	o.OrdersSum = &v
}

// GetAvgOrders returns the AvgOrders field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetAvgOrders() float32 {
	if o == nil || IsNil(o.AvgOrders) {
		var ret float32
		return ret
	}
	return *o.AvgOrders
}

// GetAvgOrdersOk returns a tuple with the AvgOrders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetAvgOrdersOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgOrders) {
		return nil, false
	}
	return o.AvgOrders, true
}

// HasAvgOrders returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasAvgOrders() bool {
	if o != nil && !IsNil(o.AvgOrders) {
		return true
	}

	return false
}

// SetAvgOrders gets a reference to the given float32 and assigns it to the AvgOrders field.
func (o *TableCommonMetrics) SetAvgOrders(v float32) {
	o.AvgOrders = &v
}

// GetAvgOrdersByMonth returns the AvgOrdersByMonth field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetAvgOrdersByMonth() []FloatGraphByPeriodItem {
	if o == nil || IsNil(o.AvgOrdersByMonth) {
		var ret []FloatGraphByPeriodItem
		return ret
	}
	return o.AvgOrdersByMonth
}

// GetAvgOrdersByMonthOk returns a tuple with the AvgOrdersByMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetAvgOrdersByMonthOk() ([]FloatGraphByPeriodItem, bool) {
	if o == nil || IsNil(o.AvgOrdersByMonth) {
		return nil, false
	}
	return o.AvgOrdersByMonth, true
}

// HasAvgOrdersByMonth returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasAvgOrdersByMonth() bool {
	if o != nil && !IsNil(o.AvgOrdersByMonth) {
		return true
	}

	return false
}

// SetAvgOrdersByMonth gets a reference to the given []FloatGraphByPeriodItem and assigns it to the AvgOrdersByMonth field.
func (o *TableCommonMetrics) SetAvgOrdersByMonth(v []FloatGraphByPeriodItem) {
	o.AvgOrdersByMonth = v
}

// GetBuyoutCount returns the BuyoutCount field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetBuyoutCount() int32 {
	if o == nil || IsNil(o.BuyoutCount) {
		var ret int32
		return ret
	}
	return *o.BuyoutCount
}

// GetBuyoutCountOk returns a tuple with the BuyoutCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetBuyoutCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BuyoutCount) {
		return nil, false
	}
	return o.BuyoutCount, true
}

// HasBuyoutCount returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasBuyoutCount() bool {
	if o != nil && !IsNil(o.BuyoutCount) {
		return true
	}

	return false
}

// SetBuyoutCount gets a reference to the given int32 and assigns it to the BuyoutCount field.
func (o *TableCommonMetrics) SetBuyoutCount(v int32) {
	o.BuyoutCount = &v
}

// GetBuyoutSum returns the BuyoutSum field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetBuyoutSum() int32 {
	if o == nil || IsNil(o.BuyoutSum) {
		var ret int32
		return ret
	}
	return *o.BuyoutSum
}

// GetBuyoutSumOk returns a tuple with the BuyoutSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetBuyoutSumOk() (*int32, bool) {
	if o == nil || IsNil(o.BuyoutSum) {
		return nil, false
	}
	return o.BuyoutSum, true
}

// HasBuyoutSum returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasBuyoutSum() bool {
	if o != nil && !IsNil(o.BuyoutSum) {
		return true
	}

	return false
}

// SetBuyoutSum gets a reference to the given int32 and assigns it to the BuyoutSum field.
func (o *TableCommonMetrics) SetBuyoutSum(v int32) {
	o.BuyoutSum = &v
}

// GetBuyoutPercent returns the BuyoutPercent field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetBuyoutPercent() int32 {
	if o == nil || IsNil(o.BuyoutPercent) {
		var ret int32
		return ret
	}
	return *o.BuyoutPercent
}

// GetBuyoutPercentOk returns a tuple with the BuyoutPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetBuyoutPercentOk() (*int32, bool) {
	if o == nil || IsNil(o.BuyoutPercent) {
		return nil, false
	}
	return o.BuyoutPercent, true
}

// HasBuyoutPercent returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasBuyoutPercent() bool {
	if o != nil && !IsNil(o.BuyoutPercent) {
		return true
	}

	return false
}

// SetBuyoutPercent gets a reference to the given int32 and assigns it to the BuyoutPercent field.
func (o *TableCommonMetrics) SetBuyoutPercent(v int32) {
	o.BuyoutPercent = &v
}

// GetStockCount returns the StockCount field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetStockCount() int32 {
	if o == nil || IsNil(o.StockCount) {
		var ret int32
		return ret
	}
	return *o.StockCount
}

// GetStockCountOk returns a tuple with the StockCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetStockCountOk() (*int32, bool) {
	if o == nil || IsNil(o.StockCount) {
		return nil, false
	}
	return o.StockCount, true
}

// HasStockCount returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasStockCount() bool {
	if o != nil && !IsNil(o.StockCount) {
		return true
	}

	return false
}

// SetStockCount gets a reference to the given int32 and assigns it to the StockCount field.
func (o *TableCommonMetrics) SetStockCount(v int32) {
	o.StockCount = &v
}

// GetStockSum returns the StockSum field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetStockSum() int32 {
	if o == nil || IsNil(o.StockSum) {
		var ret int32
		return ret
	}
	return *o.StockSum
}

// GetStockSumOk returns a tuple with the StockSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetStockSumOk() (*int32, bool) {
	if o == nil || IsNil(o.StockSum) {
		return nil, false
	}
	return o.StockSum, true
}

// HasStockSum returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasStockSum() bool {
	if o != nil && !IsNil(o.StockSum) {
		return true
	}

	return false
}

// SetStockSum gets a reference to the given int32 and assigns it to the StockSum field.
func (o *TableCommonMetrics) SetStockSum(v int32) {
	o.StockSum = &v
}

// GetSaleRate returns the SaleRate field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetSaleRate() TableCommonMetricsSaleRate {
	if o == nil || IsNil(o.SaleRate) {
		var ret TableCommonMetricsSaleRate
		return ret
	}
	return *o.SaleRate
}

// GetSaleRateOk returns a tuple with the SaleRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetSaleRateOk() (*TableCommonMetricsSaleRate, bool) {
	if o == nil || IsNil(o.SaleRate) {
		return nil, false
	}
	return o.SaleRate, true
}

// HasSaleRate returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasSaleRate() bool {
	if o != nil && !IsNil(o.SaleRate) {
		return true
	}

	return false
}

// SetSaleRate gets a reference to the given TableCommonMetricsSaleRate and assigns it to the SaleRate field.
func (o *TableCommonMetrics) SetSaleRate(v TableCommonMetricsSaleRate) {
	o.SaleRate = &v
}

// GetAvgStockTurnover returns the AvgStockTurnover field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetAvgStockTurnover() TableCommonMetricsAvgStockTurnover {
	if o == nil || IsNil(o.AvgStockTurnover) {
		var ret TableCommonMetricsAvgStockTurnover
		return ret
	}
	return *o.AvgStockTurnover
}

// GetAvgStockTurnoverOk returns a tuple with the AvgStockTurnover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetAvgStockTurnoverOk() (*TableCommonMetricsAvgStockTurnover, bool) {
	if o == nil || IsNil(o.AvgStockTurnover) {
		return nil, false
	}
	return o.AvgStockTurnover, true
}

// HasAvgStockTurnover returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasAvgStockTurnover() bool {
	if o != nil && !IsNil(o.AvgStockTurnover) {
		return true
	}

	return false
}

// SetAvgStockTurnover gets a reference to the given TableCommonMetricsAvgStockTurnover and assigns it to the AvgStockTurnover field.
func (o *TableCommonMetrics) SetAvgStockTurnover(v TableCommonMetricsAvgStockTurnover) {
	o.AvgStockTurnover = &v
}

// GetToClientCount returns the ToClientCount field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetToClientCount() int32 {
	if o == nil || IsNil(o.ToClientCount) {
		var ret int32
		return ret
	}
	return *o.ToClientCount
}

// GetToClientCountOk returns a tuple with the ToClientCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetToClientCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ToClientCount) {
		return nil, false
	}
	return o.ToClientCount, true
}

// HasToClientCount returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasToClientCount() bool {
	if o != nil && !IsNil(o.ToClientCount) {
		return true
	}

	return false
}

// SetToClientCount gets a reference to the given int32 and assigns it to the ToClientCount field.
func (o *TableCommonMetrics) SetToClientCount(v int32) {
	o.ToClientCount = &v
}

// GetFromClientCount returns the FromClientCount field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetFromClientCount() int32 {
	if o == nil || IsNil(o.FromClientCount) {
		var ret int32
		return ret
	}
	return *o.FromClientCount
}

// GetFromClientCountOk returns a tuple with the FromClientCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetFromClientCountOk() (*int32, bool) {
	if o == nil || IsNil(o.FromClientCount) {
		return nil, false
	}
	return o.FromClientCount, true
}

// HasFromClientCount returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasFromClientCount() bool {
	if o != nil && !IsNil(o.FromClientCount) {
		return true
	}

	return false
}

// SetFromClientCount gets a reference to the given int32 and assigns it to the FromClientCount field.
func (o *TableCommonMetrics) SetFromClientCount(v int32) {
	o.FromClientCount = &v
}

// GetOfficeMissingTime returns the OfficeMissingTime field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetOfficeMissingTime() TableCommonMetricsOfficeMissingTime {
	if o == nil || IsNil(o.OfficeMissingTime) {
		var ret TableCommonMetricsOfficeMissingTime
		return ret
	}
	return *o.OfficeMissingTime
}

// GetOfficeMissingTimeOk returns a tuple with the OfficeMissingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetOfficeMissingTimeOk() (*TableCommonMetricsOfficeMissingTime, bool) {
	if o == nil || IsNil(o.OfficeMissingTime) {
		return nil, false
	}
	return o.OfficeMissingTime, true
}

// HasOfficeMissingTime returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasOfficeMissingTime() bool {
	if o != nil && !IsNil(o.OfficeMissingTime) {
		return true
	}

	return false
}

// SetOfficeMissingTime gets a reference to the given TableCommonMetricsOfficeMissingTime and assigns it to the OfficeMissingTime field.
func (o *TableCommonMetrics) SetOfficeMissingTime(v TableCommonMetricsOfficeMissingTime) {
	o.OfficeMissingTime = &v
}

// GetLostOrdersCount returns the LostOrdersCount field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetLostOrdersCount() float32 {
	if o == nil || IsNil(o.LostOrdersCount) {
		var ret float32
		return ret
	}
	return *o.LostOrdersCount
}

// GetLostOrdersCountOk returns a tuple with the LostOrdersCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetLostOrdersCountOk() (*float32, bool) {
	if o == nil || IsNil(o.LostOrdersCount) {
		return nil, false
	}
	return o.LostOrdersCount, true
}

// HasLostOrdersCount returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasLostOrdersCount() bool {
	if o != nil && !IsNil(o.LostOrdersCount) {
		return true
	}

	return false
}

// SetLostOrdersCount gets a reference to the given float32 and assigns it to the LostOrdersCount field.
func (o *TableCommonMetrics) SetLostOrdersCount(v float32) {
	o.LostOrdersCount = &v
}

// GetLostOrdersSum returns the LostOrdersSum field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetLostOrdersSum() float32 {
	if o == nil || IsNil(o.LostOrdersSum) {
		var ret float32
		return ret
	}
	return *o.LostOrdersSum
}

// GetLostOrdersSumOk returns a tuple with the LostOrdersSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetLostOrdersSumOk() (*float32, bool) {
	if o == nil || IsNil(o.LostOrdersSum) {
		return nil, false
	}
	return o.LostOrdersSum, true
}

// HasLostOrdersSum returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasLostOrdersSum() bool {
	if o != nil && !IsNil(o.LostOrdersSum) {
		return true
	}

	return false
}

// SetLostOrdersSum gets a reference to the given float32 and assigns it to the LostOrdersSum field.
func (o *TableCommonMetrics) SetLostOrdersSum(v float32) {
	o.LostOrdersSum = &v
}

// GetLostBuyoutsCount returns the LostBuyoutsCount field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetLostBuyoutsCount() float32 {
	if o == nil || IsNil(o.LostBuyoutsCount) {
		var ret float32
		return ret
	}
	return *o.LostBuyoutsCount
}

// GetLostBuyoutsCountOk returns a tuple with the LostBuyoutsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetLostBuyoutsCountOk() (*float32, bool) {
	if o == nil || IsNil(o.LostBuyoutsCount) {
		return nil, false
	}
	return o.LostBuyoutsCount, true
}

// HasLostBuyoutsCount returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasLostBuyoutsCount() bool {
	if o != nil && !IsNil(o.LostBuyoutsCount) {
		return true
	}

	return false
}

// SetLostBuyoutsCount gets a reference to the given float32 and assigns it to the LostBuyoutsCount field.
func (o *TableCommonMetrics) SetLostBuyoutsCount(v float32) {
	o.LostBuyoutsCount = &v
}

// GetLostBuyoutsSum returns the LostBuyoutsSum field value if set, zero value otherwise.
func (o *TableCommonMetrics) GetLostBuyoutsSum() float32 {
	if o == nil || IsNil(o.LostBuyoutsSum) {
		var ret float32
		return ret
	}
	return *o.LostBuyoutsSum
}

// GetLostBuyoutsSumOk returns a tuple with the LostBuyoutsSum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableCommonMetrics) GetLostBuyoutsSumOk() (*float32, bool) {
	if o == nil || IsNil(o.LostBuyoutsSum) {
		return nil, false
	}
	return o.LostBuyoutsSum, true
}

// HasLostBuyoutsSum returns a boolean if a field has been set.
func (o *TableCommonMetrics) HasLostBuyoutsSum() bool {
	if o != nil && !IsNil(o.LostBuyoutsSum) {
		return true
	}

	return false
}

// SetLostBuyoutsSum gets a reference to the given float32 and assigns it to the LostBuyoutsSum field.
func (o *TableCommonMetrics) SetLostBuyoutsSum(v float32) {
	o.LostBuyoutsSum = &v
}

func (o TableCommonMetrics) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableCommonMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrdersCount) {
		toSerialize["ordersCount"] = o.OrdersCount
	}
	if !IsNil(o.OrdersSum) {
		toSerialize["ordersSum"] = o.OrdersSum
	}
	if !IsNil(o.AvgOrders) {
		toSerialize["avgOrders"] = o.AvgOrders
	}
	if !IsNil(o.AvgOrdersByMonth) {
		toSerialize["avgOrdersByMonth"] = o.AvgOrdersByMonth
	}
	if !IsNil(o.BuyoutCount) {
		toSerialize["buyoutCount"] = o.BuyoutCount
	}
	if !IsNil(o.BuyoutSum) {
		toSerialize["buyoutSum"] = o.BuyoutSum
	}
	if !IsNil(o.BuyoutPercent) {
		toSerialize["buyoutPercent"] = o.BuyoutPercent
	}
	if !IsNil(o.StockCount) {
		toSerialize["stockCount"] = o.StockCount
	}
	if !IsNil(o.StockSum) {
		toSerialize["stockSum"] = o.StockSum
	}
	if !IsNil(o.SaleRate) {
		toSerialize["saleRate"] = o.SaleRate
	}
	if !IsNil(o.AvgStockTurnover) {
		toSerialize["avgStockTurnover"] = o.AvgStockTurnover
	}
	if !IsNil(o.ToClientCount) {
		toSerialize["toClientCount"] = o.ToClientCount
	}
	if !IsNil(o.FromClientCount) {
		toSerialize["fromClientCount"] = o.FromClientCount
	}
	if !IsNil(o.OfficeMissingTime) {
		toSerialize["officeMissingTime"] = o.OfficeMissingTime
	}
	if !IsNil(o.LostOrdersCount) {
		toSerialize["lostOrdersCount"] = o.LostOrdersCount
	}
	if !IsNil(o.LostOrdersSum) {
		toSerialize["lostOrdersSum"] = o.LostOrdersSum
	}
	if !IsNil(o.LostBuyoutsCount) {
		toSerialize["lostBuyoutsCount"] = o.LostBuyoutsCount
	}
	if !IsNil(o.LostBuyoutsSum) {
		toSerialize["lostBuyoutsSum"] = o.LostBuyoutsSum
	}
	return toSerialize, nil
}

type NullableTableCommonMetrics struct {
	value *TableCommonMetrics
	isSet bool
}

func (v NullableTableCommonMetrics) Get() *TableCommonMetrics {
	return v.value
}

func (v *NullableTableCommonMetrics) Set(val *TableCommonMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableTableCommonMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableTableCommonMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableCommonMetrics(val *TableCommonMetrics) *NullableTableCommonMetrics {
	return &NullableTableCommonMetrics{value: val, isSet: true}
}

func (v NullableTableCommonMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableCommonMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
