/*
 * Маркетинг и продвижение
 *
 * Узнать больше о маркетинге и продвижении можно в [справочном центре](https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e)  Методы маркетинга и продвижения позволяют: 1. Получать информацию о кампаниях [продвижения](https://dev.wildberries.ru/openapi/promotion#tag/campaigns) и [медиакампаниях](https://dev.wildberries.ru/openapi/promotion#tag/media) 2. [Создавать](https://dev.wildberries.ru/openapi/promotion#tag/creatingCampaigns) и [управлять](https://dev.wildberries.ru/openapi/promotion#tag/campaignManagement) кампаниями 3. Управлять [финансами](https://dev.wildberries.ru/openapi/promotion#tag/finances) кампаний 4. Выгружать [статистику](https://dev.wildberries.ru/openapi/promotion#tag/statistics) кампаний продвижения и медиакампаний 5. Работать с [календарём акций](https://dev.wildberries.ru/openapi/promotion#tag/promoCalendar) Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  Вы можете протестировать методы продвижения в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/promotion) для управления тестовым балансом
 *
 * The version of the OpenAPI document: promotion
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ValeryVerkhoturov.WbApiClient.Promotion.Client.OpenAPIDateConverter;

namespace ValeryVerkhoturov.WbApiClient.Promotion.Model
{
    /// <summary>
    /// Статистика по одной кампании за период, указанный в запросе. По всем артикулам WB и платформам
    /// </summary>
    [DataContract(Name = "FullStatsItem")]
    public partial class FullStatsItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FullStatsItem" /> class.
        /// </summary>
        /// <param name="advertId">ID кампании.</param>
        /// <param name="atbs">Количество добавлений товаров в корзину.</param>
        /// <param name="boosterStats">Статистика по средней позиции товара (для кампаний с единой ставкой).</param>
        /// <param name="canceled">Отмены, шт..</param>
        /// <param name="clicks">Количество кликов.</param>
        /// <param name="cpc">Средняя стоимость клика в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances).</param>
        /// <param name="cr">CR (conversion rate) — отношение количества заказов к общему количеству кликов.</param>
        /// <param name="ctr">CTR (click-through rate) — отношение числа кликов к количеству показов в процентах.</param>
        /// <param name="days">Статистка по дням.</param>
        /// <param name="orders">Количество заказов.</param>
        /// <param name="shks">Количество заказанных товаров, шт..</param>
        /// <param name="sum">Затраты в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances).</param>
        /// <param name="sumPrice">Сумма заказов в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances).</param>
        /// <param name="views">Количество просмотров.</param>
        /// <param name="currency">Валюта [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances).</param>
        public FullStatsItem(int advertId = default(int), int atbs = default(int), List<FullStatsItemBoosterStatsInner> boosterStats = default(List<FullStatsItemBoosterStatsInner>), int canceled = default(int), int clicks = default(int), double cpc = default(double), double cr = default(double), double ctr = default(double), List<FullStatsItemDaysInner> days = default(List<FullStatsItemDaysInner>), int orders = default(int), int shks = default(int), double sum = default(double), double sumPrice = default(double), int views = default(int), string currency = default(string))
        {
            this.AdvertId = advertId;
            this.Atbs = atbs;
            this.BoosterStats = boosterStats;
            this.Canceled = canceled;
            this.Clicks = clicks;
            this.Cpc = cpc;
            this.Cr = cr;
            this.Ctr = ctr;
            this.Days = days;
            this.Orders = orders;
            this.Shks = shks;
            this.Sum = sum;
            this.SumPrice = sumPrice;
            this.Views = views;
            this.Currency = currency;
        }

        /// <summary>
        /// ID кампании
        /// </summary>
        /// <value>ID кампании</value>
        [DataMember(Name = "advertId", EmitDefaultValue = false)]
        public int AdvertId { get; set; }

        /// <summary>
        /// Количество добавлений товаров в корзину
        /// </summary>
        /// <value>Количество добавлений товаров в корзину</value>
        [DataMember(Name = "atbs", EmitDefaultValue = false)]
        public int Atbs { get; set; }

        /// <summary>
        /// Статистика по средней позиции товара (для кампаний с единой ставкой)
        /// </summary>
        /// <value>Статистика по средней позиции товара (для кампаний с единой ставкой)</value>
        [DataMember(Name = "boosterStats", EmitDefaultValue = false)]
        public List<FullStatsItemBoosterStatsInner> BoosterStats { get; set; }

        /// <summary>
        /// Отмены, шт.
        /// </summary>
        /// <value>Отмены, шт.</value>
        [DataMember(Name = "canceled", EmitDefaultValue = false)]
        public int Canceled { get; set; }

        /// <summary>
        /// Количество кликов
        /// </summary>
        /// <value>Количество кликов</value>
        [DataMember(Name = "clicks", EmitDefaultValue = false)]
        public int Clicks { get; set; }

        /// <summary>
        /// Средняя стоимость клика в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)
        /// </summary>
        /// <value>Средняя стоимость клика в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)</value>
        [DataMember(Name = "cpc", EmitDefaultValue = false)]
        public double Cpc { get; set; }

        /// <summary>
        /// CR (conversion rate) — отношение количества заказов к общему количеству кликов
        /// </summary>
        /// <value>CR (conversion rate) — отношение количества заказов к общему количеству кликов</value>
        [DataMember(Name = "cr", EmitDefaultValue = false)]
        public double Cr { get; set; }

        /// <summary>
        /// CTR (click-through rate) — отношение числа кликов к количеству показов в процентах
        /// </summary>
        /// <value>CTR (click-through rate) — отношение числа кликов к количеству показов в процентах</value>
        [DataMember(Name = "ctr", EmitDefaultValue = false)]
        public double Ctr { get; set; }

        /// <summary>
        /// Статистка по дням
        /// </summary>
        /// <value>Статистка по дням</value>
        [DataMember(Name = "days", EmitDefaultValue = false)]
        public List<FullStatsItemDaysInner> Days { get; set; }

        /// <summary>
        /// Количество заказов
        /// </summary>
        /// <value>Количество заказов</value>
        [DataMember(Name = "orders", EmitDefaultValue = false)]
        public int Orders { get; set; }

        /// <summary>
        /// Количество заказанных товаров, шт.
        /// </summary>
        /// <value>Количество заказанных товаров, шт.</value>
        [DataMember(Name = "shks", EmitDefaultValue = false)]
        public int Shks { get; set; }

        /// <summary>
        /// Затраты в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)
        /// </summary>
        /// <value>Затраты в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)</value>
        [DataMember(Name = "sum", EmitDefaultValue = false)]
        public double Sum { get; set; }

        /// <summary>
        /// Сумма заказов в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)
        /// </summary>
        /// <value>Сумма заказов в базовых единицах валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)</value>
        [DataMember(Name = "sum_price", EmitDefaultValue = false)]
        public double SumPrice { get; set; }

        /// <summary>
        /// Количество просмотров
        /// </summary>
        /// <value>Количество просмотров</value>
        [DataMember(Name = "views", EmitDefaultValue = false)]
        public int Views { get; set; }

        /// <summary>
        /// Валюта [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)
        /// </summary>
        /// <value>Валюта [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)</value>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FullStatsItem {\n");
            sb.Append("  AdvertId: ").Append(AdvertId).Append("\n");
            sb.Append("  Atbs: ").Append(Atbs).Append("\n");
            sb.Append("  BoosterStats: ").Append(BoosterStats).Append("\n");
            sb.Append("  Canceled: ").Append(Canceled).Append("\n");
            sb.Append("  Clicks: ").Append(Clicks).Append("\n");
            sb.Append("  Cpc: ").Append(Cpc).Append("\n");
            sb.Append("  Cr: ").Append(Cr).Append("\n");
            sb.Append("  Ctr: ").Append(Ctr).Append("\n");
            sb.Append("  Days: ").Append(Days).Append("\n");
            sb.Append("  Orders: ").Append(Orders).Append("\n");
            sb.Append("  Shks: ").Append(Shks).Append("\n");
            sb.Append("  Sum: ").Append(Sum).Append("\n");
            sb.Append("  SumPrice: ").Append(SumPrice).Append("\n");
            sb.Append("  Views: ").Append(Views).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
