/*
 * Маркетинг и продвижение
 *
 * Узнать больше о маркетинге и продвижении можно в [справочном центре](https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e)  Методы маркетинга и продвижения позволяют: 1. Получать информацию о кампаниях [продвижения](https://dev.wildberries.ru/openapi/promotion#tag/campaigns) и [медиакампаниях](https://dev.wildberries.ru/openapi/promotion#tag/media) 2. [Создавать](https://dev.wildberries.ru/openapi/promotion#tag/creatingCampaigns) и [управлять](https://dev.wildberries.ru/openapi/promotion#tag/campaignManagement) кампаниями 3. Управлять [финансами](https://dev.wildberries.ru/openapi/promotion#tag/finances) кампаний 4. Выгружать [статистику](https://dev.wildberries.ru/openapi/promotion#tag/statistics) кампаний продвижения и медиакампаний 5. Работать с [календарём акций](https://dev.wildberries.ru/openapi/promotion#tag/promoCalendar) Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  Вы можете протестировать методы продвижения в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/promotion) для управления тестовым балансом
 *
 * The version of the OpenAPI document: promotion
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ValeryVerkhoturov.WbApiClient.Promotion.Client.OpenAPIDateConverter;

namespace ValeryVerkhoturov.WbApiClient.Promotion.Model
{
    /// <summary>
    /// V0DailyLimitAdvert
    /// </summary>
    [DataContract(Name = "V0DailyLimitAdvert")]
    public partial class V0DailyLimitAdvert : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V0DailyLimitAdvert" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V0DailyLimitAdvert() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V0DailyLimitAdvert" /> class.
        /// </summary>
        /// <param name="advertId">ID кампании (required).</param>
        /// <param name="enabled">- &#x60;true&#x60; — дневной лимит включен - &#x60;false&#x60; — дневной лимит отключен  (required).</param>
        /// <param name="dailyLimit">Размер дневного лимита в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances) (required).</param>
        /// <param name="spentToday">Потрачено сегодня в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances) (required).</param>
        /// <param name="currency">Код валюты (required).</param>
        /// <param name="carryOverEnabled">Перенос остатка дневного лимита на следующий день. Если за 24 часа лимит потратится не полностью, добавим остаток суммы к лимиту следующего дня. Расходы на продвижение не увеличатся.   - &#x60;true&#x60; — перенос остатка включен   - &#x60;false&#x60; — перенос остатка отключен  (required).</param>
        /// <param name="valid">Хватает ли текущего размера лимита на установку ставок кампании:   - &#x60;true&#x60; — да   - &#x60;false&#x60; — нет, рекомендуем повысить лимит, иначе бюджет кампании может расходоваться неравномерно  (required).</param>
        /// <param name="requiredLimit">Рекомендуемый минимальный размер дневного лимита при текущих ставках кампании. Указывается в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)  (required).</param>
        public V0DailyLimitAdvert(long advertId = default(long), bool enabled = default(bool), long dailyLimit = default(long), long spentToday = default(long), string currency = default(string), bool carryOverEnabled = default(bool), bool valid = default(bool), long requiredLimit = default(long))
        {
            this.AdvertId = advertId;
            this.Enabled = enabled;
            this.DailyLimit = dailyLimit;
            this.SpentToday = spentToday;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for V0DailyLimitAdvert and cannot be null");
            }
            this.Currency = currency;
            this.CarryOverEnabled = carryOverEnabled;
            this.Valid = valid;
            this.RequiredLimit = requiredLimit;
        }

        /// <summary>
        /// ID кампании
        /// </summary>
        /// <value>ID кампании</value>
        /*
        <example>12346</example>
        */
        [DataMember(Name = "advertId", IsRequired = true, EmitDefaultValue = true)]
        public long AdvertId { get; set; }

        /// <summary>
        /// - &#x60;true&#x60; — дневной лимит включен - &#x60;false&#x60; — дневной лимит отключен 
        /// </summary>
        /// <value>- &#x60;true&#x60; — дневной лимит включен - &#x60;false&#x60; — дневной лимит отключен </value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Размер дневного лимита в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)
        /// </summary>
        /// <value>Размер дневного лимита в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)</value>
        /*
        <example>100000</example>
        */
        [DataMember(Name = "dailyLimit", IsRequired = true, EmitDefaultValue = true)]
        public long DailyLimit { get; set; }

        /// <summary>
        /// Потрачено сегодня в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)
        /// </summary>
        /// <value>Потрачено сегодня в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances)</value>
        /*
        <example>35000</example>
        */
        [DataMember(Name = "spentToday", IsRequired = true, EmitDefaultValue = true)]
        public long SpentToday { get; set; }

        /// <summary>
        /// Код валюты
        /// </summary>
        /// <value>Код валюты</value>
        /*
        <example>RUB</example>
        */
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Перенос остатка дневного лимита на следующий день. Если за 24 часа лимит потратится не полностью, добавим остаток суммы к лимиту следующего дня. Расходы на продвижение не увеличатся.   - &#x60;true&#x60; — перенос остатка включен   - &#x60;false&#x60; — перенос остатка отключен 
        /// </summary>
        /// <value>Перенос остатка дневного лимита на следующий день. Если за 24 часа лимит потратится не полностью, добавим остаток суммы к лимиту следующего дня. Расходы на продвижение не увеличатся.   - &#x60;true&#x60; — перенос остатка включен   - &#x60;false&#x60; — перенос остатка отключен </value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "carryOverEnabled", IsRequired = true, EmitDefaultValue = true)]
        public bool CarryOverEnabled { get; set; }

        /// <summary>
        /// Хватает ли текущего размера лимита на установку ставок кампании:   - &#x60;true&#x60; — да   - &#x60;false&#x60; — нет, рекомендуем повысить лимит, иначе бюджет кампании может расходоваться неравномерно 
        /// </summary>
        /// <value>Хватает ли текущего размера лимита на установку ставок кампании:   - &#x60;true&#x60; — да   - &#x60;false&#x60; — нет, рекомендуем повысить лимит, иначе бюджет кампании может расходоваться неравномерно </value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "valid", IsRequired = true, EmitDefaultValue = true)]
        public bool Valid { get; set; }

        /// <summary>
        /// Рекомендуемый минимальный размер дневного лимита при текущих ставках кампании. Указывается в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances) 
        /// </summary>
        /// <value>Рекомендуемый минимальный размер дневного лимита при текущих ставках кампании. Указывается в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wildberries.ru/campaigns/finances) </value>
        /*
        <example>3001</example>
        */
        [DataMember(Name = "requiredLimit", IsRequired = true, EmitDefaultValue = true)]
        public long RequiredLimit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V0DailyLimitAdvert {\n");
            sb.Append("  AdvertId: ").Append(AdvertId).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  DailyLimit: ").Append(DailyLimit).Append("\n");
            sb.Append("  SpentToday: ").Append(SpentToday).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  CarryOverEnabled: ").Append(CarryOverEnabled).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  RequiredLimit: ").Append(RequiredLimit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
