/*
 * Тарифы
 * Узнать больше о тарифах можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/material/fees-site-section)  В разделе описаны методы получения: 1. [Комиссий](https://dev.wildberries.ru/openapi/rates#tag/fees) 2. [Тарифов на поставку](https://dev.wildberries.ru/openapi/rates#tag/supplyRates) 3. [Тарифов на остаток](https://dev.wildberries.ru/openapi/rates#tag/stockRates) 4. [Тарифов на возврат товаров продавцу](https://dev.wildberries.ru/openapi/rates#tag/returnCostToSeller)
 *
 * The version of the OpenAPI document: rates
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.valeryverkhoturov.wbapi.rates.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.valeryverkhoturov.wbapi.rates.JSON;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** ModelsWarehousePalletRates */
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.10.0")
public class ModelsWarehousePalletRates {
  public static final String SERIALIZED_NAME_PALLET_DELIVERY_EXPR = "palletDeliveryExpr";

  @SerializedName(SERIALIZED_NAME_PALLET_DELIVERY_EXPR)
  @jakarta.annotation.Nullable
  private String palletDeliveryExpr;

  public static final String SERIALIZED_NAME_PALLET_DELIVERY_VALUE_BASE = "palletDeliveryValueBase";

  @SerializedName(SERIALIZED_NAME_PALLET_DELIVERY_VALUE_BASE)
  @jakarta.annotation.Nullable
  private String palletDeliveryValueBase;

  public static final String SERIALIZED_NAME_PALLET_DELIVERY_VALUE_LITER =
      "palletDeliveryValueLiter";

  @SerializedName(SERIALIZED_NAME_PALLET_DELIVERY_VALUE_LITER)
  @jakarta.annotation.Nullable
  private String palletDeliveryValueLiter;

  public static final String SERIALIZED_NAME_PALLET_STORAGE_EXPR = "palletStorageExpr";

  @SerializedName(SERIALIZED_NAME_PALLET_STORAGE_EXPR)
  @jakarta.annotation.Nullable
  private String palletStorageExpr;

  public static final String SERIALIZED_NAME_PALLET_STORAGE_VALUE_EXPR = "palletStorageValueExpr";

  @SerializedName(SERIALIZED_NAME_PALLET_STORAGE_VALUE_EXPR)
  @jakarta.annotation.Nullable
  private String palletStorageValueExpr;

  public static final String SERIALIZED_NAME_WAREHOUSE_NAME = "warehouseName";

  @SerializedName(SERIALIZED_NAME_WAREHOUSE_NAME)
  @jakarta.annotation.Nullable
  private String warehouseName;

  public ModelsWarehousePalletRates() {}

  public ModelsWarehousePalletRates palletDeliveryExpr(
      @jakarta.annotation.Nullable String palletDeliveryExpr) {
    this.palletDeliveryExpr = palletDeliveryExpr;
    return this;
  }

  /**
   * Коэффициент доставки, %. На него умножается стоимость доставки. Во всех тарифах этот
   * коэффициент уже учтён
   *
   * @return palletDeliveryExpr
   */
  @jakarta.annotation.Nullable
  public String getPalletDeliveryExpr() {
    return palletDeliveryExpr;
  }

  public void setPalletDeliveryExpr(@jakarta.annotation.Nullable String palletDeliveryExpr) {
    this.palletDeliveryExpr = palletDeliveryExpr;
  }

  public ModelsWarehousePalletRates palletDeliveryValueBase(
      @jakarta.annotation.Nullable String palletDeliveryValueBase) {
    this.palletDeliveryValueBase = palletDeliveryValueBase;
    return this;
  }

  /**
   * Доставка 1 литра, ₽
   *
   * @return palletDeliveryValueBase
   */
  @jakarta.annotation.Nullable
  public String getPalletDeliveryValueBase() {
    return palletDeliveryValueBase;
  }

  public void setPalletDeliveryValueBase(
      @jakarta.annotation.Nullable String palletDeliveryValueBase) {
    this.palletDeliveryValueBase = palletDeliveryValueBase;
  }

  public ModelsWarehousePalletRates palletDeliveryValueLiter(
      @jakarta.annotation.Nullable String palletDeliveryValueLiter) {
    this.palletDeliveryValueLiter = palletDeliveryValueLiter;
    return this;
  }

  /**
   * Доставка каждого дополнительного литра, ₽
   *
   * @return palletDeliveryValueLiter
   */
  @jakarta.annotation.Nullable
  public String getPalletDeliveryValueLiter() {
    return palletDeliveryValueLiter;
  }

  public void setPalletDeliveryValueLiter(
      @jakarta.annotation.Nullable String palletDeliveryValueLiter) {
    this.palletDeliveryValueLiter = palletDeliveryValueLiter;
  }

  public ModelsWarehousePalletRates palletStorageExpr(
      @jakarta.annotation.Nullable String palletStorageExpr) {
    this.palletStorageExpr = palletStorageExpr;
    return this;
  }

  /**
   * Коэффициент хранения, %. На него умножается стоимость хранения. Во всех тарифах этот
   * коэффициент уже учтён
   *
   * @return palletStorageExpr
   */
  @jakarta.annotation.Nullable
  public String getPalletStorageExpr() {
    return palletStorageExpr;
  }

  public void setPalletStorageExpr(@jakarta.annotation.Nullable String palletStorageExpr) {
    this.palletStorageExpr = palletStorageExpr;
  }

  public ModelsWarehousePalletRates palletStorageValueExpr(
      @jakarta.annotation.Nullable String palletStorageValueExpr) {
    this.palletStorageValueExpr = palletStorageValueExpr;
    return this;
  }

  /**
   * Хранение 1 монопаллеты, ₽
   *
   * @return palletStorageValueExpr
   */
  @jakarta.annotation.Nullable
  public String getPalletStorageValueExpr() {
    return palletStorageValueExpr;
  }

  public void setPalletStorageValueExpr(
      @jakarta.annotation.Nullable String palletStorageValueExpr) {
    this.palletStorageValueExpr = palletStorageValueExpr;
  }

  public ModelsWarehousePalletRates warehouseName(
      @jakarta.annotation.Nullable String warehouseName) {
    this.warehouseName = warehouseName;
    return this;
  }

  /**
   * Название склада
   *
   * @return warehouseName
   */
  @jakarta.annotation.Nullable
  public String getWarehouseName() {
    return warehouseName;
  }

  public void setWarehouseName(@jakarta.annotation.Nullable String warehouseName) {
    this.warehouseName = warehouseName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsWarehousePalletRates modelsWarehousePalletRates = (ModelsWarehousePalletRates) o;
    return Objects.equals(this.palletDeliveryExpr, modelsWarehousePalletRates.palletDeliveryExpr)
        && Objects.equals(
            this.palletDeliveryValueBase, modelsWarehousePalletRates.palletDeliveryValueBase)
        && Objects.equals(
            this.palletDeliveryValueLiter, modelsWarehousePalletRates.palletDeliveryValueLiter)
        && Objects.equals(this.palletStorageExpr, modelsWarehousePalletRates.palletStorageExpr)
        && Objects.equals(
            this.palletStorageValueExpr, modelsWarehousePalletRates.palletStorageValueExpr)
        && Objects.equals(this.warehouseName, modelsWarehousePalletRates.warehouseName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        palletDeliveryExpr,
        palletDeliveryValueBase,
        palletDeliveryValueLiter,
        palletStorageExpr,
        palletStorageValueExpr,
        warehouseName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsWarehousePalletRates {\n");
    sb.append("    palletDeliveryExpr: ").append(toIndentedString(palletDeliveryExpr)).append("\n");
    sb.append("    palletDeliveryValueBase: ")
        .append(toIndentedString(palletDeliveryValueBase))
        .append("\n");
    sb.append("    palletDeliveryValueLiter: ")
        .append(toIndentedString(palletDeliveryValueLiter))
        .append("\n");
    sb.append("    palletStorageExpr: ").append(toIndentedString(palletStorageExpr)).append("\n");
    sb.append("    palletStorageValueExpr: ")
        .append(toIndentedString(palletStorageValueExpr))
        .append("\n");
    sb.append("    warehouseName: ").append(toIndentedString(warehouseName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("palletDeliveryExpr");
    openapiFields.add("palletDeliveryValueBase");
    openapiFields.add("palletDeliveryValueLiter");
    openapiFields.add("palletStorageExpr");
    openapiFields.add("palletStorageValueExpr");
    openapiFields.add("warehouseName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ModelsWarehousePalletRates
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!ModelsWarehousePalletRates.openapiRequiredFields
          .isEmpty()) { // has required fields but JSON element is null
        throw new IllegalArgumentException(
            String.format(
                "The required field(s) %s in ModelsWarehousePalletRates is not found in the empty JSON string",
                ModelsWarehousePalletRates.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!ModelsWarehousePalletRates.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(
            String.format(
                "The field `%s` in the JSON string is not defined in the `ModelsWarehousePalletRates` properties. JSON: %s",
                entry.getKey(), jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if ((jsonObj.get("palletDeliveryExpr") != null
            && !jsonObj.get("palletDeliveryExpr").isJsonNull())
        && !jsonObj.get("palletDeliveryExpr").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `palletDeliveryExpr` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("palletDeliveryExpr").toString()));
    }
    if ((jsonObj.get("palletDeliveryValueBase") != null
            && !jsonObj.get("palletDeliveryValueBase").isJsonNull())
        && !jsonObj.get("palletDeliveryValueBase").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `palletDeliveryValueBase` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("palletDeliveryValueBase").toString()));
    }
    if ((jsonObj.get("palletDeliveryValueLiter") != null
            && !jsonObj.get("palletDeliveryValueLiter").isJsonNull())
        && !jsonObj.get("palletDeliveryValueLiter").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `palletDeliveryValueLiter` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("palletDeliveryValueLiter").toString()));
    }
    if ((jsonObj.get("palletStorageExpr") != null && !jsonObj.get("palletStorageExpr").isJsonNull())
        && !jsonObj.get("palletStorageExpr").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `palletStorageExpr` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("palletStorageExpr").toString()));
    }
    if ((jsonObj.get("palletStorageValueExpr") != null
            && !jsonObj.get("palletStorageValueExpr").isJsonNull())
        && !jsonObj.get("palletStorageValueExpr").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `palletStorageValueExpr` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("palletStorageValueExpr").toString()));
    }
    if ((jsonObj.get("warehouseName") != null && !jsonObj.get("warehouseName").isJsonNull())
        && !jsonObj.get("warehouseName").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `warehouseName` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("warehouseName").toString()));
    }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!ModelsWarehousePalletRates.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'ModelsWarehousePalletRates' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<ModelsWarehousePalletRates> thisAdapter =
          gson.getDelegateAdapter(this, TypeToken.get(ModelsWarehousePalletRates.class));

      return (TypeAdapter<T>)
          new TypeAdapter<ModelsWarehousePalletRates>() {
            @Override
            public void write(JsonWriter out, ModelsWarehousePalletRates value) throws IOException {
              JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
              elementAdapter.write(out, obj);
            }

            @Override
            public ModelsWarehousePalletRates read(JsonReader in) throws IOException {
              JsonElement jsonElement = elementAdapter.read(in);
              validateJsonElement(jsonElement);
              return thisAdapter.fromJsonTree(jsonElement);
            }
          }.nullSafe();
    }
  }

  /**
   * Create an instance of ModelsWarehousePalletRates given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ModelsWarehousePalletRates
   * @throws IOException if the JSON string is invalid with respect to ModelsWarehousePalletRates
   */
  public static ModelsWarehousePalletRates fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModelsWarehousePalletRates.class);
  }

  /**
   * Convert an instance of ModelsWarehousePalletRates to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
