/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете: - получать информацию о [сборочных заданиях](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsAssemblyOrders) и их статусах, отменять сборочные задания, получать стикеры - добавлять, редактировать и удалять [идентификаторы маркировки](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsLabelIdentifiers) сборочных заданий - управлять [поставками](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsSupplies) - создавать, редактировать и удалять [пропуска](https://dev.wildberries.ru/openapi/orders-fbs#tag/fbsPasses) на склады WB Вы можете протестировать методы заказов FBS в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/marketplaceFbs) для эмуляции действий пользователя  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs) по работе с **заказами FBS**  Узнать больше о заказах FBS можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d)
 *
 * The version of the OpenAPI document: order
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";

export const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
  csv: ",",
  ssv: " ",
  tsv: "\t",
  pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
  url: string;
  options: RawAxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
  protected configuration: Configuration | undefined;

  constructor(
    configuration?: Configuration,
    protected basePath: string = BASE_PATH,
    protected axios: AxiosInstance = globalAxios,
  ) {
    if (configuration) {
      this.configuration = configuration;
      this.basePath = configuration.basePath ?? basePath;
    }
  }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
  constructor(
    public field: string,
    msg?: string,
  ) {
    super(msg);
    this.name = "RequiredError";
  }
}

interface ServerMap {
  [key: string]: {
    url: string;
    description: string;
  }[];
}

/**
 *
 * @export
 */
export const operationServerMap: ServerMap = {
  "OrdersFbsApi.deleteV3OrdersOrderIdMeta": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.deleteV3PassesPassId": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.deleteV3SuppliesSupplyId": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.deleteV3SuppliesSupplyIdTrbx": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3FbsDictionariesCountriesOksm": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "No description provided",
    },
  ],
  "OrdersFbsApi.getV3FbsOrdersArchive": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "No description provided",
    },
  ],
  "OrdersFbsApi.getV3FbsSettingsAutoreturns": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
  ],
  "OrdersFbsApi.getV3FbsSettingsAutoreturnsSubcategoriesRestricted": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
  ],
  "OrdersFbsApi.getV3FbsShippingPoints": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "No description provided",
    },
  ],
  "OrdersFbsApi.getV3FbsSuppliesSupplyIdStickersSpot": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "No description provided",
    },
  ],
  "OrdersFbsApi.getV3Orders": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3OrdersNew": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3Passes": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3PassesOffices": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3Supplies": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3SuppliesOrdersReshipment": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3SuppliesSupplyId": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3SuppliesSupplyIdBarcode": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3SuppliesSupplyIdOrderIds": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.getV3SuppliesSupplyIdTrbx": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.patchV3FbsSettingsAutoreturns": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
  ],
  "OrdersFbsApi.patchV3FbsSettingsAutoreturnsItems": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
  ],
  "OrdersFbsApi.patchV3FbsSuppliesShippingMethod": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "No description provided",
    },
  ],
  "OrdersFbsApi.patchV3OrdersOrderIdCancel": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.patchV3SuppliesSupplyIdDeliver": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.patchV3SuppliesSupplyIdOrders": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.postV3FbsSettingsAutoreturnsItems": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
  ],
  "OrdersFbsApi.postV3FbsSuppliesSpotList": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "No description provided",
    },
  ],
  "OrdersFbsApi.postV3OrdersClient": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.postV3OrdersMeta": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.postV3OrdersStatus": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.postV3OrdersStatusHistory": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.postV3OrdersStickers": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.postV3OrdersStickersCrossBorder": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "No description provided",
    },
  ],
  "OrdersFbsApi.postV3Passes": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.postV3Supplies": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.postV3SuppliesSupplyIdTrbx": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.postV3SuppliesSupplyIdTrbxStickers": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.putV3FbsSuppliesSupplyIdSpot": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "No description provided",
    },
  ],
  "OrdersFbsApi.putV3OrdersOrderIdMetaCustomsDeclaration": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.putV3OrdersOrderIdMetaExpiration": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.putV3OrdersOrderIdMetaGtin": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.putV3OrdersOrderIdMetaImei": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.putV3OrdersOrderIdMetaSgtin": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.putV3OrdersOrderIdMetaUin": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
  "OrdersFbsApi.putV3PassesPassId": [
    {
      url: "https://marketplace-api.wildberries.ru",
      description: "**Prod** ",
    },
    {
      url: "https://marketplace-api-sandbox.wildberries.ru",
      description: "**Sandbox** ",
    },
  ],
};
