/*
 * Аналитика и данные
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.valeryverkhoturov.wbapi.analytics.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.valeryverkhoturov.wbapi.analytics.model.ItemStocks;
import io.github.valeryverkhoturov.wbapi.analytics.model.Tag;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.valeryverkhoturov.wbapi.analytics.JSON;

/**
 * ItemsResponseProductsInnerProduct
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ItemsResponseProductsInnerProduct {
  public static final String SERIALIZED_NAME_NM_ID = "nmId";
  @SerializedName(SERIALIZED_NAME_NM_ID)
  @jakarta.annotation.Nonnull
  private Long nmId;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @jakarta.annotation.Nonnull
  private String title;

  public static final String SERIALIZED_NAME_VENDOR_CODE = "vendorCode";
  @SerializedName(SERIALIZED_NAME_VENDOR_CODE)
  @jakarta.annotation.Nonnull
  private String vendorCode;

  public static final String SERIALIZED_NAME_BRAND_NAME = "brandName";
  @SerializedName(SERIALIZED_NAME_BRAND_NAME)
  @jakarta.annotation.Nonnull
  private String brandName;

  public static final String SERIALIZED_NAME_SUBJECT_ID = "subjectId";
  @SerializedName(SERIALIZED_NAME_SUBJECT_ID)
  @jakarta.annotation.Nonnull
  private Integer subjectId;

  public static final String SERIALIZED_NAME_SUBJECT_NAME = "subjectName";
  @SerializedName(SERIALIZED_NAME_SUBJECT_NAME)
  @jakarta.annotation.Nonnull
  private String subjectName;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @jakarta.annotation.Nonnull
  private List<Tag> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_PRODUCT_RATING = "productRating";
  @SerializedName(SERIALIZED_NAME_PRODUCT_RATING)
  @jakarta.annotation.Nonnull
  private BigDecimal productRating;

  public static final String SERIALIZED_NAME_FEEDBACK_RATING = "feedbackRating";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_RATING)
  @jakarta.annotation.Nonnull
  private BigDecimal feedbackRating;

  public static final String SERIALIZED_NAME_STOCKS = "stocks";
  @SerializedName(SERIALIZED_NAME_STOCKS)
  @jakarta.annotation.Nonnull
  private ItemStocks stocks;

  public ItemsResponseProductsInnerProduct() {
  }

  public ItemsResponseProductsInnerProduct nmId(@jakarta.annotation.Nonnull Long nmId) {
    this.nmId = nmId;
    return this;
  }

  /**
   * Артикул WB
   * @return nmId
   */
  @jakarta.annotation.Nonnull
  public Long getNmId() {
    return nmId;
  }

  public void setNmId(@jakarta.annotation.Nonnull Long nmId) {
    this.nmId = nmId;
  }


  public ItemsResponseProductsInnerProduct title(@jakarta.annotation.Nonnull String title) {
    this.title = title;
    return this;
  }

  /**
   * Название карточки товара
   * @return title
   */
  @jakarta.annotation.Nonnull
  public String getTitle() {
    return title;
  }

  public void setTitle(@jakarta.annotation.Nonnull String title) {
    this.title = title;
  }


  public ItemsResponseProductsInnerProduct vendorCode(@jakarta.annotation.Nonnull String vendorCode) {
    this.vendorCode = vendorCode;
    return this;
  }

  /**
   * Артикул продавца
   * @return vendorCode
   */
  @jakarta.annotation.Nonnull
  public String getVendorCode() {
    return vendorCode;
  }

  public void setVendorCode(@jakarta.annotation.Nonnull String vendorCode) {
    this.vendorCode = vendorCode;
  }


  public ItemsResponseProductsInnerProduct brandName(@jakarta.annotation.Nonnull String brandName) {
    this.brandName = brandName;
    return this;
  }

  /**
   * Бренд
   * @return brandName
   */
  @jakarta.annotation.Nonnull
  public String getBrandName() {
    return brandName;
  }

  public void setBrandName(@jakarta.annotation.Nonnull String brandName) {
    this.brandName = brandName;
  }


  public ItemsResponseProductsInnerProduct subjectId(@jakarta.annotation.Nonnull Integer subjectId) {
    this.subjectId = subjectId;
    return this;
  }

  /**
   * ID предмета
   * @return subjectId
   */
  @jakarta.annotation.Nonnull
  public Integer getSubjectId() {
    return subjectId;
  }

  public void setSubjectId(@jakarta.annotation.Nonnull Integer subjectId) {
    this.subjectId = subjectId;
  }


  public ItemsResponseProductsInnerProduct subjectName(@jakarta.annotation.Nonnull String subjectName) {
    this.subjectName = subjectName;
    return this;
  }

  /**
   * Название предмета
   * @return subjectName
   */
  @jakarta.annotation.Nonnull
  public String getSubjectName() {
    return subjectName;
  }

  public void setSubjectName(@jakarta.annotation.Nonnull String subjectName) {
    this.subjectName = subjectName;
  }


  public ItemsResponseProductsInnerProduct tags(@jakarta.annotation.Nonnull List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public ItemsResponseProductsInnerProduct addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Ярлыки
   * @return tags
   */
  @jakarta.annotation.Nonnull
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(@jakarta.annotation.Nonnull List<Tag> tags) {
    this.tags = tags;
  }


  public ItemsResponseProductsInnerProduct productRating(@jakarta.annotation.Nonnull BigDecimal productRating) {
    this.productRating = productRating;
    return this;
  }

  /**
   * Оценка карточки
   * @return productRating
   */
  @jakarta.annotation.Nonnull
  public BigDecimal getProductRating() {
    return productRating;
  }

  public void setProductRating(@jakarta.annotation.Nonnull BigDecimal productRating) {
    this.productRating = productRating;
  }


  public ItemsResponseProductsInnerProduct feedbackRating(@jakarta.annotation.Nonnull BigDecimal feedbackRating) {
    this.feedbackRating = feedbackRating;
    return this;
  }

  /**
   * Оценка пользователей
   * @return feedbackRating
   */
  @jakarta.annotation.Nonnull
  public BigDecimal getFeedbackRating() {
    return feedbackRating;
  }

  public void setFeedbackRating(@jakarta.annotation.Nonnull BigDecimal feedbackRating) {
    this.feedbackRating = feedbackRating;
  }


  public ItemsResponseProductsInnerProduct stocks(@jakarta.annotation.Nonnull ItemStocks stocks) {
    this.stocks = stocks;
    return this;
  }

  /**
   * Get stocks
   * @return stocks
   */
  @jakarta.annotation.Nonnull
  public ItemStocks getStocks() {
    return stocks;
  }

  public void setStocks(@jakarta.annotation.Nonnull ItemStocks stocks) {
    this.stocks = stocks;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemsResponseProductsInnerProduct itemsResponseProductsInnerProduct = (ItemsResponseProductsInnerProduct) o;
    return Objects.equals(this.nmId, itemsResponseProductsInnerProduct.nmId) &&
        Objects.equals(this.title, itemsResponseProductsInnerProduct.title) &&
        Objects.equals(this.vendorCode, itemsResponseProductsInnerProduct.vendorCode) &&
        Objects.equals(this.brandName, itemsResponseProductsInnerProduct.brandName) &&
        Objects.equals(this.subjectId, itemsResponseProductsInnerProduct.subjectId) &&
        Objects.equals(this.subjectName, itemsResponseProductsInnerProduct.subjectName) &&
        Objects.equals(this.tags, itemsResponseProductsInnerProduct.tags) &&
        Objects.equals(this.productRating, itemsResponseProductsInnerProduct.productRating) &&
        Objects.equals(this.feedbackRating, itemsResponseProductsInnerProduct.feedbackRating) &&
        Objects.equals(this.stocks, itemsResponseProductsInnerProduct.stocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nmId, title, vendorCode, brandName, subjectId, subjectName, tags, productRating, feedbackRating, stocks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemsResponseProductsInnerProduct {\n");
    sb.append("    nmId: ").append(toIndentedString(nmId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    vendorCode: ").append(toIndentedString(vendorCode)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    subjectId: ").append(toIndentedString(subjectId)).append("\n");
    sb.append("    subjectName: ").append(toIndentedString(subjectName)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    productRating: ").append(toIndentedString(productRating)).append("\n");
    sb.append("    feedbackRating: ").append(toIndentedString(feedbackRating)).append("\n");
    sb.append("    stocks: ").append(toIndentedString(stocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nmId");
    openapiFields.add("title");
    openapiFields.add("vendorCode");
    openapiFields.add("brandName");
    openapiFields.add("subjectId");
    openapiFields.add("subjectName");
    openapiFields.add("tags");
    openapiFields.add("productRating");
    openapiFields.add("feedbackRating");
    openapiFields.add("stocks");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("nmId");
    openapiRequiredFields.add("title");
    openapiRequiredFields.add("vendorCode");
    openapiRequiredFields.add("brandName");
    openapiRequiredFields.add("subjectId");
    openapiRequiredFields.add("subjectName");
    openapiRequiredFields.add("tags");
    openapiRequiredFields.add("productRating");
    openapiRequiredFields.add("feedbackRating");
    openapiRequiredFields.add("stocks");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ItemsResponseProductsInnerProduct
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ItemsResponseProductsInnerProduct.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ItemsResponseProductsInnerProduct is not found in the empty JSON string", ItemsResponseProductsInnerProduct.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ItemsResponseProductsInnerProduct.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ItemsResponseProductsInnerProduct` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ItemsResponseProductsInnerProduct.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if (!jsonObj.get("vendorCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vendorCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vendorCode").toString()));
      }
      if (!jsonObj.get("brandName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandName").toString()));
      }
      if (!jsonObj.get("subjectName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subjectName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subjectName").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }

      JsonArray jsonArraytags = jsonObj.getAsJsonArray("tags");
      // validate the required field `tags` (array)
      for (int i = 0; i < jsonArraytags.size(); i++) {
        Tag.validateJsonElement(jsonArraytags.get(i));
      };
      // validate the required field `stocks`
      ItemStocks.validateJsonElement(jsonObj.get("stocks"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ItemsResponseProductsInnerProduct.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ItemsResponseProductsInnerProduct' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ItemsResponseProductsInnerProduct> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ItemsResponseProductsInnerProduct.class));

       return (TypeAdapter<T>) new TypeAdapter<ItemsResponseProductsInnerProduct>() {
           @Override
           public void write(JsonWriter out, ItemsResponseProductsInnerProduct value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ItemsResponseProductsInnerProduct read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ItemsResponseProductsInnerProduct given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ItemsResponseProductsInnerProduct
   * @throws IOException if the JSON string is invalid with respect to ItemsResponseProductsInnerProduct
   */
  public static ItemsResponseProductsInnerProduct fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ItemsResponseProductsInnerProduct.class);
  }

  /**
   * Convert an instance of ItemsResponseProductsInnerProduct to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

