/*
 * Аналитика и данные
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.valeryverkhoturov.wbapi.analytics.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.valeryverkhoturov.wbapi.analytics.model.History;
import io.github.valeryverkhoturov.wbapi.analytics.model.PostV3SalesFunnelProductsHistoryResponse200InnerProduct;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.valeryverkhoturov.wbapi.analytics.JSON;

/**
 * PostV3SalesFunnelProductsHistoryResponse200Inner
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PostV3SalesFunnelProductsHistoryResponse200Inner {
  public static final String SERIALIZED_NAME_PRODUCT = "product";
  @SerializedName(SERIALIZED_NAME_PRODUCT)
  @jakarta.annotation.Nonnull
  private PostV3SalesFunnelProductsHistoryResponse200InnerProduct product;

  public static final String SERIALIZED_NAME_HISTORY = "history";
  @SerializedName(SERIALIZED_NAME_HISTORY)
  @jakarta.annotation.Nonnull
  private List<History> history = new ArrayList<>();

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @jakarta.annotation.Nonnull
  private String currency;

  public PostV3SalesFunnelProductsHistoryResponse200Inner() {
  }

  public PostV3SalesFunnelProductsHistoryResponse200Inner product(@jakarta.annotation.Nonnull PostV3SalesFunnelProductsHistoryResponse200InnerProduct product) {
    this.product = product;
    return this;
  }

  /**
   * Get product
   * @return product
   */
  @jakarta.annotation.Nonnull
  public PostV3SalesFunnelProductsHistoryResponse200InnerProduct getProduct() {
    return product;
  }

  public void setProduct(@jakarta.annotation.Nonnull PostV3SalesFunnelProductsHistoryResponse200InnerProduct product) {
    this.product = product;
  }


  public PostV3SalesFunnelProductsHistoryResponse200Inner history(@jakarta.annotation.Nonnull List<History> history) {
    this.history = history;
    return this;
  }

  public PostV3SalesFunnelProductsHistoryResponse200Inner addHistoryItem(History historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<>();
    }
    this.history.add(historyItem);
    return this;
  }

  /**
   * Статистика за период
   * @return history
   */
  @jakarta.annotation.Nonnull
  public List<History> getHistory() {
    return history;
  }

  public void setHistory(@jakarta.annotation.Nonnull List<History> history) {
    this.history = history;
  }


  public PostV3SalesFunnelProductsHistoryResponse200Inner currency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Валюта отчёта
   * @return currency
   */
  @jakarta.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostV3SalesFunnelProductsHistoryResponse200Inner postV3SalesFunnelProductsHistoryResponse200Inner = (PostV3SalesFunnelProductsHistoryResponse200Inner) o;
    return Objects.equals(this.product, postV3SalesFunnelProductsHistoryResponse200Inner.product) &&
        Objects.equals(this.history, postV3SalesFunnelProductsHistoryResponse200Inner.history) &&
        Objects.equals(this.currency, postV3SalesFunnelProductsHistoryResponse200Inner.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(product, history, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostV3SalesFunnelProductsHistoryResponse200Inner {\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("product");
    openapiFields.add("history");
    openapiFields.add("currency");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("product");
    openapiRequiredFields.add("history");
    openapiRequiredFields.add("currency");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostV3SalesFunnelProductsHistoryResponse200Inner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostV3SalesFunnelProductsHistoryResponse200Inner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostV3SalesFunnelProductsHistoryResponse200Inner is not found in the empty JSON string", PostV3SalesFunnelProductsHistoryResponse200Inner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostV3SalesFunnelProductsHistoryResponse200Inner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PostV3SalesFunnelProductsHistoryResponse200Inner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostV3SalesFunnelProductsHistoryResponse200Inner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `product`
      PostV3SalesFunnelProductsHistoryResponse200InnerProduct.validateJsonElement(jsonObj.get("product"));
      // ensure the json data is an array
      if (!jsonObj.get("history").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `history` to be an array in the JSON string but got `%s`", jsonObj.get("history").toString()));
      }

      JsonArray jsonArrayhistory = jsonObj.getAsJsonArray("history");
      // validate the required field `history` (array)
      for (int i = 0; i < jsonArrayhistory.size(); i++) {
        History.validateJsonElement(jsonArrayhistory.get(i));
      };
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostV3SalesFunnelProductsHistoryResponse200Inner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostV3SalesFunnelProductsHistoryResponse200Inner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostV3SalesFunnelProductsHistoryResponse200Inner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostV3SalesFunnelProductsHistoryResponse200Inner.class));

       return (TypeAdapter<T>) new TypeAdapter<PostV3SalesFunnelProductsHistoryResponse200Inner>() {
           @Override
           public void write(JsonWriter out, PostV3SalesFunnelProductsHistoryResponse200Inner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostV3SalesFunnelProductsHistoryResponse200Inner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostV3SalesFunnelProductsHistoryResponse200Inner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostV3SalesFunnelProductsHistoryResponse200Inner
   * @throws IOException if the JSON string is invalid with respect to PostV3SalesFunnelProductsHistoryResponse200Inner
   */
  public static PostV3SalesFunnelProductsHistoryResponse200Inner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostV3SalesFunnelProductsHistoryResponse200Inner.class);
  }

  /**
   * Convert an instance of PostV3SalesFunnelProductsHistoryResponse200Inner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

