/*
 * Аналитика и данные
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.valeryverkhoturov.wbapi.analytics.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.valeryverkhoturov.wbapi.analytics.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Параметры отчёта */
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.10.0")
public class SearchReportTextReqParams {
  public static final String SERIALIZED_NAME_CURRENT_PERIOD = "currentPeriod";

  @SerializedName(SERIALIZED_NAME_CURRENT_PERIOD)
  @jakarta.annotation.Nonnull
  private Period currentPeriod;

  public static final String SERIALIZED_NAME_PAST_PERIOD = "pastPeriod";

  @SerializedName(SERIALIZED_NAME_PAST_PERIOD)
  @jakarta.annotation.Nullable
  private PastPeriod pastPeriod;

  public static final String SERIALIZED_NAME_NM_IDS = "nmIds";

  @SerializedName(SERIALIZED_NAME_NM_IDS)
  @jakarta.annotation.Nullable
  private List<String> nmIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_SUBJECT_IDS = "subjectIds";

  @SerializedName(SERIALIZED_NAME_SUBJECT_IDS)
  @jakarta.annotation.Nullable
  private List<Integer> subjectIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_BRAND_NAMES = "brandNames";

  @SerializedName(SERIALIZED_NAME_BRAND_NAMES)
  @jakarta.annotation.Nullable
  private List<String> brandNames = new ArrayList<>();

  public static final String SERIALIZED_NAME_TAG_IDS = "tagIds";

  @SerializedName(SERIALIZED_NAME_TAG_IDS)
  @jakarta.annotation.Nullable
  private List<Long> tagIds = new ArrayList<>();

  /**
   * Фильтрация по поисковым запросам, по которым больше всего: - &#x60;openCard&#x60; — перешли в
   * карточку - &#x60;addToCart&#x60; — добавили в корзину - &#x60;openToCart&#x60; — конверсия в
   * корзину - &#x60;orders&#x60; — заказали товаров - &#x60;cartToOrder&#x60; — конверсия в заказ
   */
  @JsonAdapter(TopOrderByEnum.Adapter.class)
  public enum TopOrderByEnum {
    OPEN_CARD("openCard"),

    ADD_TO_CART("addToCart"),

    OPEN_TO_CART("openToCart"),

    ORDERS("orders"),

    CART_TO_ORDER("cartToOrder");

    private String value;

    TopOrderByEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TopOrderByEnum fromValue(String value) {
      for (TopOrderByEnum b : TopOrderByEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TopOrderByEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TopOrderByEnum enumeration)
          throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TopOrderByEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TopOrderByEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TopOrderByEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TOP_ORDER_BY = "topOrderBy";

  @SerializedName(SERIALIZED_NAME_TOP_ORDER_BY)
  @jakarta.annotation.Nonnull
  private TopOrderByEnum topOrderBy;

  public static final String SERIALIZED_NAME_ORDER_BY = "orderBy";

  @SerializedName(SERIALIZED_NAME_ORDER_BY)
  @jakarta.annotation.Nonnull
  private OrderByGrTe orderBy;

  public static final String SERIALIZED_NAME_INCLUDE_SUBSTITUTED_S_K_US = "includeSubstitutedSKUs";

  @SerializedName(SERIALIZED_NAME_INCLUDE_SUBSTITUTED_S_K_US)
  @jakarta.annotation.Nullable
  private Boolean includeSubstitutedSKUs = true;

  public static final String SERIALIZED_NAME_INCLUDE_SEARCH_TEXTS = "includeSearchTexts";

  @SerializedName(SERIALIZED_NAME_INCLUDE_SEARCH_TEXTS)
  @jakarta.annotation.Nullable
  private Boolean includeSearchTexts = true;

  public static final String SERIALIZED_NAME_LIMIT = "limit";

  @SerializedName(SERIALIZED_NAME_LIMIT)
  @jakarta.annotation.Nonnull
  private TextLimit limit;

  public SearchReportTextReqParams() {}

  public SearchReportTextReqParams currentPeriod(@jakarta.annotation.Nonnull Period currentPeriod) {
    this.currentPeriod = currentPeriod;
    return this;
  }

  /**
   * Get currentPeriod
   *
   * @return currentPeriod
   */
  @jakarta.annotation.Nonnull
  public Period getCurrentPeriod() {
    return currentPeriod;
  }

  public void setCurrentPeriod(@jakarta.annotation.Nonnull Period currentPeriod) {
    this.currentPeriod = currentPeriod;
  }

  public SearchReportTextReqParams pastPeriod(@jakarta.annotation.Nullable PastPeriod pastPeriod) {
    this.pastPeriod = pastPeriod;
    return this;
  }

  /**
   * Get pastPeriod
   *
   * @return pastPeriod
   */
  @jakarta.annotation.Nullable
  public PastPeriod getPastPeriod() {
    return pastPeriod;
  }

  public void setPastPeriod(@jakarta.annotation.Nullable PastPeriod pastPeriod) {
    this.pastPeriod = pastPeriod;
  }

  public SearchReportTextReqParams nmIds(@jakarta.annotation.Nullable List<String> nmIds) {
    this.nmIds = nmIds;
    return this;
  }

  public SearchReportTextReqParams addNmIdsItem(String nmIdsItem) {
    if (this.nmIds == null) {
      this.nmIds = new ArrayList<>();
    }
    this.nmIds.add(nmIdsItem);
    return this;
  }

  /**
   * Артикулы WB, по которым составить отчёт. Оставьте пустым, чтобы получить отчёт по всем товарам
   *
   * @return nmIds
   */
  @jakarta.annotation.Nullable
  public List<String> getNmIds() {
    return nmIds;
  }

  public void setNmIds(@jakarta.annotation.Nullable List<String> nmIds) {
    this.nmIds = nmIds;
  }

  public SearchReportTextReqParams subjectIds(
      @jakarta.annotation.Nullable List<Integer> subjectIds) {
    this.subjectIds = subjectIds;
    return this;
  }

  public SearchReportTextReqParams addSubjectIdsItem(Integer subjectIdsItem) {
    if (this.subjectIds == null) {
      this.subjectIds = new ArrayList<>();
    }
    this.subjectIds.add(subjectIdsItem);
    return this;
  }

  /**
   * Список ID предметов для фильтрации
   *
   * @return subjectIds
   */
  @jakarta.annotation.Nullable
  public List<Integer> getSubjectIds() {
    return subjectIds;
  }

  public void setSubjectIds(@jakarta.annotation.Nullable List<Integer> subjectIds) {
    this.subjectIds = subjectIds;
  }

  public SearchReportTextReqParams brandNames(
      @jakarta.annotation.Nullable List<String> brandNames) {
    this.brandNames = brandNames;
    return this;
  }

  public SearchReportTextReqParams addBrandNamesItem(String brandNamesItem) {
    if (this.brandNames == null) {
      this.brandNames = new ArrayList<>();
    }
    this.brandNames.add(brandNamesItem);
    return this;
  }

  /**
   * Список брендов для фильтрации
   *
   * @return brandNames
   */
  @jakarta.annotation.Nullable
  public List<String> getBrandNames() {
    return brandNames;
  }

  public void setBrandNames(@jakarta.annotation.Nullable List<String> brandNames) {
    this.brandNames = brandNames;
  }

  public SearchReportTextReqParams tagIds(@jakarta.annotation.Nullable List<Long> tagIds) {
    this.tagIds = tagIds;
    return this;
  }

  public SearchReportTextReqParams addTagIdsItem(Long tagIdsItem) {
    if (this.tagIds == null) {
      this.tagIds = new ArrayList<>();
    }
    this.tagIds.add(tagIdsItem);
    return this;
  }

  /**
   * Список ID ярлыков для фильтрации
   *
   * @return tagIds
   */
  @jakarta.annotation.Nullable
  public List<Long> getTagIds() {
    return tagIds;
  }

  public void setTagIds(@jakarta.annotation.Nullable List<Long> tagIds) {
    this.tagIds = tagIds;
  }

  public SearchReportTextReqParams topOrderBy(
      @jakarta.annotation.Nonnull TopOrderByEnum topOrderBy) {
    this.topOrderBy = topOrderBy;
    return this;
  }

  /**
   * Фильтрация по поисковым запросам, по которым больше всего: - &#x60;openCard&#x60; — перешли в
   * карточку - &#x60;addToCart&#x60; — добавили в корзину - &#x60;openToCart&#x60; — конверсия в
   * корзину - &#x60;orders&#x60; — заказали товаров - &#x60;cartToOrder&#x60; — конверсия в заказ
   *
   * @return topOrderBy
   */
  @jakarta.annotation.Nonnull
  public TopOrderByEnum getTopOrderBy() {
    return topOrderBy;
  }

  public void setTopOrderBy(@jakarta.annotation.Nonnull TopOrderByEnum topOrderBy) {
    this.topOrderBy = topOrderBy;
  }

  public SearchReportTextReqParams orderBy(@jakarta.annotation.Nonnull OrderByGrTe orderBy) {
    this.orderBy = orderBy;
    return this;
  }

  /**
   * Get orderBy
   *
   * @return orderBy
   */
  @jakarta.annotation.Nonnull
  public OrderByGrTe getOrderBy() {
    return orderBy;
  }

  public void setOrderBy(@jakarta.annotation.Nonnull OrderByGrTe orderBy) {
    this.orderBy = orderBy;
  }

  public SearchReportTextReqParams includeSubstitutedSKUs(
      @jakarta.annotation.Nullable Boolean includeSubstitutedSKUs) {
    this.includeSubstitutedSKUs = includeSubstitutedSKUs;
    return this;
  }

  /**
   * Показать данные по прямым запросам с [подменным
   * артикулом](https://seller.wildberries.ru/help-center/article/A-524)
   *
   * @return includeSubstitutedSKUs
   */
  @jakarta.annotation.Nullable
  public Boolean getIncludeSubstitutedSKUs() {
    return includeSubstitutedSKUs;
  }

  public void setIncludeSubstitutedSKUs(
      @jakarta.annotation.Nullable Boolean includeSubstitutedSKUs) {
    this.includeSubstitutedSKUs = includeSubstitutedSKUs;
  }

  public SearchReportTextReqParams includeSearchTexts(
      @jakarta.annotation.Nullable Boolean includeSearchTexts) {
    this.includeSearchTexts = includeSearchTexts;
    return this;
  }

  /**
   * Показать данные по поисковым запросам без учёта подменного артикула
   *
   * @return includeSearchTexts
   */
  @jakarta.annotation.Nullable
  public Boolean getIncludeSearchTexts() {
    return includeSearchTexts;
  }

  public void setIncludeSearchTexts(@jakarta.annotation.Nullable Boolean includeSearchTexts) {
    this.includeSearchTexts = includeSearchTexts;
  }

  public SearchReportTextReqParams limit(@jakarta.annotation.Nonnull TextLimit limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   *
   * @return limit
   */
  @jakarta.annotation.Nonnull
  public TextLimit getLimit() {
    return limit;
  }

  public void setLimit(@jakarta.annotation.Nonnull TextLimit limit) {
    this.limit = limit;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchReportTextReqParams searchReportTextReqParams = (SearchReportTextReqParams) o;
    return Objects.equals(this.currentPeriod, searchReportTextReqParams.currentPeriod)
        && Objects.equals(this.pastPeriod, searchReportTextReqParams.pastPeriod)
        && Objects.equals(this.nmIds, searchReportTextReqParams.nmIds)
        && Objects.equals(this.subjectIds, searchReportTextReqParams.subjectIds)
        && Objects.equals(this.brandNames, searchReportTextReqParams.brandNames)
        && Objects.equals(this.tagIds, searchReportTextReqParams.tagIds)
        && Objects.equals(this.topOrderBy, searchReportTextReqParams.topOrderBy)
        && Objects.equals(this.orderBy, searchReportTextReqParams.orderBy)
        && Objects.equals(
            this.includeSubstitutedSKUs, searchReportTextReqParams.includeSubstitutedSKUs)
        && Objects.equals(this.includeSearchTexts, searchReportTextReqParams.includeSearchTexts)
        && Objects.equals(this.limit, searchReportTextReqParams.limit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        currentPeriod,
        pastPeriod,
        nmIds,
        subjectIds,
        brandNames,
        tagIds,
        topOrderBy,
        orderBy,
        includeSubstitutedSKUs,
        includeSearchTexts,
        limit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchReportTextReqParams {\n");
    sb.append("    currentPeriod: ").append(toIndentedString(currentPeriod)).append("\n");
    sb.append("    pastPeriod: ").append(toIndentedString(pastPeriod)).append("\n");
    sb.append("    nmIds: ").append(toIndentedString(nmIds)).append("\n");
    sb.append("    subjectIds: ").append(toIndentedString(subjectIds)).append("\n");
    sb.append("    brandNames: ").append(toIndentedString(brandNames)).append("\n");
    sb.append("    tagIds: ").append(toIndentedString(tagIds)).append("\n");
    sb.append("    topOrderBy: ").append(toIndentedString(topOrderBy)).append("\n");
    sb.append("    orderBy: ").append(toIndentedString(orderBy)).append("\n");
    sb.append("    includeSubstitutedSKUs: ")
        .append(toIndentedString(includeSubstitutedSKUs))
        .append("\n");
    sb.append("    includeSearchTexts: ").append(toIndentedString(includeSearchTexts)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("currentPeriod");
    openapiFields.add("pastPeriod");
    openapiFields.add("nmIds");
    openapiFields.add("subjectIds");
    openapiFields.add("brandNames");
    openapiFields.add("tagIds");
    openapiFields.add("topOrderBy");
    openapiFields.add("orderBy");
    openapiFields.add("includeSubstitutedSKUs");
    openapiFields.add("includeSearchTexts");
    openapiFields.add("limit");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("currentPeriod");
    openapiRequiredFields.add("topOrderBy");
    openapiRequiredFields.add("orderBy");
    openapiRequiredFields.add("limit");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SearchReportTextReqParams
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!SearchReportTextReqParams.openapiRequiredFields
          .isEmpty()) { // has required fields but JSON element is null
        throw new IllegalArgumentException(
            String.format(
                "The required field(s) %s in SearchReportTextReqParams is not found in the empty JSON string",
                SearchReportTextReqParams.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!SearchReportTextReqParams.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(
            String.format(
                "The field `%s` in the JSON string is not defined in the `SearchReportTextReqParams` properties. JSON: %s",
                entry.getKey(), jsonElement.toString()));
      }
    }

    // check to make sure all required properties/fields are present in the JSON string
    for (String requiredField : SearchReportTextReqParams.openapiRequiredFields) {
      if (jsonElement.getAsJsonObject().get(requiredField) == null) {
        throw new IllegalArgumentException(
            String.format(
                "The required field `%s` is not found in the JSON string: %s",
                requiredField, jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    // validate the required field `currentPeriod`
    Period.validateJsonElement(jsonObj.get("currentPeriod"));
    // validate the optional field `pastPeriod`
    if (jsonObj.get("pastPeriod") != null && !jsonObj.get("pastPeriod").isJsonNull()) {
      PastPeriod.validateJsonElement(jsonObj.get("pastPeriod"));
    }
    // ensure the optional json data is an array if present
    if (jsonObj.get("nmIds") != null
        && !jsonObj.get("nmIds").isJsonNull()
        && !jsonObj.get("nmIds").isJsonArray()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `nmIds` to be an array in the JSON string but got `%s`",
              jsonObj.get("nmIds").toString()));
    }
    // ensure the optional json data is an array if present
    if (jsonObj.get("subjectIds") != null
        && !jsonObj.get("subjectIds").isJsonNull()
        && !jsonObj.get("subjectIds").isJsonArray()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `subjectIds` to be an array in the JSON string but got `%s`",
              jsonObj.get("subjectIds").toString()));
    }
    // ensure the optional json data is an array if present
    if (jsonObj.get("brandNames") != null
        && !jsonObj.get("brandNames").isJsonNull()
        && !jsonObj.get("brandNames").isJsonArray()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `brandNames` to be an array in the JSON string but got `%s`",
              jsonObj.get("brandNames").toString()));
    }
    // ensure the optional json data is an array if present
    if (jsonObj.get("tagIds") != null
        && !jsonObj.get("tagIds").isJsonNull()
        && !jsonObj.get("tagIds").isJsonArray()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `tagIds` to be an array in the JSON string but got `%s`",
              jsonObj.get("tagIds").toString()));
    }
    if (!jsonObj.get("topOrderBy").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `topOrderBy` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("topOrderBy").toString()));
    }
    // validate the required field `topOrderBy`
    TopOrderByEnum.validateJsonElement(jsonObj.get("topOrderBy"));
    // validate the required field `orderBy`
    OrderByGrTe.validateJsonElement(jsonObj.get("orderBy"));
    // validate the required field `limit`
    TextLimit.validateJsonElement(jsonObj.get("limit"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!SearchReportTextReqParams.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'SearchReportTextReqParams' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<SearchReportTextReqParams> thisAdapter =
          gson.getDelegateAdapter(this, TypeToken.get(SearchReportTextReqParams.class));

      return (TypeAdapter<T>)
          new TypeAdapter<SearchReportTextReqParams>() {
            @Override
            public void write(JsonWriter out, SearchReportTextReqParams value) throws IOException {
              JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
              elementAdapter.write(out, obj);
            }

            @Override
            public SearchReportTextReqParams read(JsonReader in) throws IOException {
              JsonElement jsonElement = elementAdapter.read(in);
              validateJsonElement(jsonElement);
              return thisAdapter.fromJsonTree(jsonElement);
            }
          }.nullSafe();
    }
  }

  /**
   * Create an instance of SearchReportTextReqParams given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SearchReportTextReqParams
   * @throws IOException if the JSON string is invalid with respect to SearchReportTextReqParams
   */
  public static SearchReportTextReqParams fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchReportTextReqParams.class);
  }

  /**
   * Convert an instance of SearchReportTextReqParams to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
