/*
 * Аналитика и данные
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.valeryverkhoturov.wbapi.analytics.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.valeryverkhoturov.wbapi.analytics.JSON;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Данные по товару */
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.10.0")
public class TableItemItemSt {
  public static final String SERIALIZED_NAME_NM_I_D = "nmID";

  @SerializedName(SERIALIZED_NAME_NM_I_D)
  @jakarta.annotation.Nonnull
  private Long nmID;

  public static final String SERIALIZED_NAME_IS_DELETED = "isDeleted";

  @SerializedName(SERIALIZED_NAME_IS_DELETED)
  @jakarta.annotation.Nonnull
  private Boolean isDeleted;

  public static final String SERIALIZED_NAME_SUBJECT_NAME = "subjectName";

  @SerializedName(SERIALIZED_NAME_SUBJECT_NAME)
  @jakarta.annotation.Nonnull
  private String subjectName;

  public static final String SERIALIZED_NAME_NAME = "name";

  @SerializedName(SERIALIZED_NAME_NAME)
  @jakarta.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_VENDOR_CODE = "vendorCode";

  @SerializedName(SERIALIZED_NAME_VENDOR_CODE)
  @jakarta.annotation.Nonnull
  private String vendorCode;

  public static final String SERIALIZED_NAME_BRAND_NAME = "brandName";

  @SerializedName(SERIALIZED_NAME_BRAND_NAME)
  @jakarta.annotation.Nonnull
  private String brandName;

  public static final String SERIALIZED_NAME_MAIN_PHOTO = "mainPhoto";

  @SerializedName(SERIALIZED_NAME_MAIN_PHOTO)
  @jakarta.annotation.Nonnull
  private String mainPhoto;

  public static final String SERIALIZED_NAME_HAS_SIZES = "hasSizes";

  @SerializedName(SERIALIZED_NAME_HAS_SIZES)
  @jakarta.annotation.Nonnull
  private Boolean hasSizes;

  public static final String SERIALIZED_NAME_METRICS = "metrics";

  @SerializedName(SERIALIZED_NAME_METRICS)
  @jakarta.annotation.Nonnull
  private TableItemItemStMetrics metrics;

  public TableItemItemSt() {}

  public TableItemItemSt nmID(@jakarta.annotation.Nonnull Long nmID) {
    this.nmID = nmID;
    return this;
  }

  /**
   * Артикул WB
   *
   * @return nmID
   */
  @jakarta.annotation.Nonnull
  public Long getNmID() {
    return nmID;
  }

  public void setNmID(@jakarta.annotation.Nonnull Long nmID) {
    this.nmID = nmID;
  }

  public TableItemItemSt isDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Является ли товар удалённым
   *
   * @return isDeleted
   */
  @jakarta.annotation.Nonnull
  public Boolean getIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public TableItemItemSt subjectName(@jakarta.annotation.Nonnull String subjectName) {
    this.subjectName = subjectName;
    return this;
  }

  /**
   * Название предмета
   *
   * @return subjectName
   */
  @jakarta.annotation.Nonnull
  public String getSubjectName() {
    return subjectName;
  }

  public void setSubjectName(@jakarta.annotation.Nonnull String subjectName) {
    this.subjectName = subjectName;
  }

  public TableItemItemSt name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Название товара
   *
   * @return name
   */
  @jakarta.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public TableItemItemSt vendorCode(@jakarta.annotation.Nonnull String vendorCode) {
    this.vendorCode = vendorCode;
    return this;
  }

  /**
   * Артикул продавца
   *
   * @return vendorCode
   */
  @jakarta.annotation.Nonnull
  public String getVendorCode() {
    return vendorCode;
  }

  public void setVendorCode(@jakarta.annotation.Nonnull String vendorCode) {
    this.vendorCode = vendorCode;
  }

  public TableItemItemSt brandName(@jakarta.annotation.Nonnull String brandName) {
    this.brandName = brandName;
    return this;
  }

  /**
   * Бренд
   *
   * @return brandName
   */
  @jakarta.annotation.Nonnull
  public String getBrandName() {
    return brandName;
  }

  public void setBrandName(@jakarta.annotation.Nonnull String brandName) {
    this.brandName = brandName;
  }

  public TableItemItemSt mainPhoto(@jakarta.annotation.Nonnull String mainPhoto) {
    this.mainPhoto = mainPhoto;
    return this;
  }

  /**
   * Ссылка на главное фото
   *
   * @return mainPhoto
   */
  @jakarta.annotation.Nonnull
  public String getMainPhoto() {
    return mainPhoto;
  }

  public void setMainPhoto(@jakarta.annotation.Nonnull String mainPhoto) {
    this.mainPhoto = mainPhoto;
  }

  public TableItemItemSt hasSizes(@jakarta.annotation.Nonnull Boolean hasSizes) {
    this.hasSizes = hasSizes;
    return this;
  }

  /**
   * Является ли товар размерным. Неразмерный товар имеет единственный размер, с
   * &#x60;\&quot;techSize\&quot;:\&quot;0\&quot;&#x60;
   *
   * @return hasSizes
   */
  @jakarta.annotation.Nonnull
  public Boolean getHasSizes() {
    return hasSizes;
  }

  public void setHasSizes(@jakarta.annotation.Nonnull Boolean hasSizes) {
    this.hasSizes = hasSizes;
  }

  public TableItemItemSt metrics(@jakarta.annotation.Nonnull TableItemItemStMetrics metrics) {
    this.metrics = metrics;
    return this;
  }

  /**
   * Get metrics
   *
   * @return metrics
   */
  @jakarta.annotation.Nonnull
  public TableItemItemStMetrics getMetrics() {
    return metrics;
  }

  public void setMetrics(@jakarta.annotation.Nonnull TableItemItemStMetrics metrics) {
    this.metrics = metrics;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TableItemItemSt tableItemItemSt = (TableItemItemSt) o;
    return Objects.equals(this.nmID, tableItemItemSt.nmID)
        && Objects.equals(this.isDeleted, tableItemItemSt.isDeleted)
        && Objects.equals(this.subjectName, tableItemItemSt.subjectName)
        && Objects.equals(this.name, tableItemItemSt.name)
        && Objects.equals(this.vendorCode, tableItemItemSt.vendorCode)
        && Objects.equals(this.brandName, tableItemItemSt.brandName)
        && Objects.equals(this.mainPhoto, tableItemItemSt.mainPhoto)
        && Objects.equals(this.hasSizes, tableItemItemSt.hasSizes)
        && Objects.equals(this.metrics, tableItemItemSt.metrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        nmID, isDeleted, subjectName, name, vendorCode, brandName, mainPhoto, hasSizes, metrics);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TableItemItemSt {\n");
    sb.append("    nmID: ").append(toIndentedString(nmID)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    subjectName: ").append(toIndentedString(subjectName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    vendorCode: ").append(toIndentedString(vendorCode)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    mainPhoto: ").append(toIndentedString(mainPhoto)).append("\n");
    sb.append("    hasSizes: ").append(toIndentedString(hasSizes)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nmID");
    openapiFields.add("isDeleted");
    openapiFields.add("subjectName");
    openapiFields.add("name");
    openapiFields.add("vendorCode");
    openapiFields.add("brandName");
    openapiFields.add("mainPhoto");
    openapiFields.add("hasSizes");
    openapiFields.add("metrics");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("nmID");
    openapiRequiredFields.add("isDeleted");
    openapiRequiredFields.add("subjectName");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("vendorCode");
    openapiRequiredFields.add("brandName");
    openapiRequiredFields.add("mainPhoto");
    openapiRequiredFields.add("hasSizes");
    openapiRequiredFields.add("metrics");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TableItemItemSt
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!TableItemItemSt.openapiRequiredFields
          .isEmpty()) { // has required fields but JSON element is null
        throw new IllegalArgumentException(
            String.format(
                "The required field(s) %s in TableItemItemSt is not found in the empty JSON string",
                TableItemItemSt.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!TableItemItemSt.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(
            String.format(
                "The field `%s` in the JSON string is not defined in the `TableItemItemSt` properties. JSON: %s",
                entry.getKey(), jsonElement.toString()));
      }
    }

    // check to make sure all required properties/fields are present in the JSON string
    for (String requiredField : TableItemItemSt.openapiRequiredFields) {
      if (jsonElement.getAsJsonObject().get(requiredField) == null) {
        throw new IllegalArgumentException(
            String.format(
                "The required field `%s` is not found in the JSON string: %s",
                requiredField, jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if (!jsonObj.get("subjectName").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `subjectName` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("subjectName").toString()));
    }
    if (!jsonObj.get("name").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `name` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("name").toString()));
    }
    if (!jsonObj.get("vendorCode").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `vendorCode` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("vendorCode").toString()));
    }
    if (!jsonObj.get("brandName").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `brandName` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("brandName").toString()));
    }
    if (!jsonObj.get("mainPhoto").isJsonPrimitive()) {
      throw new IllegalArgumentException(
          String.format(
              "Expected the field `mainPhoto` to be a primitive type in the JSON string but got `%s`",
              jsonObj.get("mainPhoto").toString()));
    }
    // validate the required field `metrics`
    TableItemItemStMetrics.validateJsonElement(jsonObj.get("metrics"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!TableItemItemSt.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'TableItemItemSt' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<TableItemItemSt> thisAdapter =
          gson.getDelegateAdapter(this, TypeToken.get(TableItemItemSt.class));

      return (TypeAdapter<T>)
          new TypeAdapter<TableItemItemSt>() {
            @Override
            public void write(JsonWriter out, TableItemItemSt value) throws IOException {
              JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
              elementAdapter.write(out, obj);
            }

            @Override
            public TableItemItemSt read(JsonReader in) throws IOException {
              JsonElement jsonElement = elementAdapter.read(in);
              validateJsonElement(jsonElement);
              return thisAdapter.fromJsonTree(jsonElement);
            }
          }.nullSafe();
    }
  }

  /**
   * Create an instance of TableItemItemSt given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TableItemItemSt
   * @throws IOException if the JSON string is invalid with respect to TableItemItemSt
   */
  public static TableItemItemSt fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TableItemItemSt.class);
  }

  /**
   * Convert an instance of TableItemItemSt to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
