/*
Отчёты

Узнать больше об отчётах можно в [справочном центре](https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0)  С помощью этих методов вы можете получать [основные отчёты](https://dev.wildberries.ru/openapi/reports#tag/mainReports) и отчёты о: 1. [Остатках на складах](https://dev.wildberries.ru/openapi/reports#tag/warehousesInventoryReport) 2. [Товарах с обязательной маркировкой](https://dev.wildberries.ru/openapi/reports#tag/reportOnItemsWithMandatoryLabeling) 3. [Удержаниях](https://dev.wildberries.ru/openapi/reports#tag/retentionReports) 4. [Операциях при приёмке](https://dev.wildberries.ru/openapi/reports#tag/acceptanceExpenses) 5. [Платном хранении](https://dev.wildberries.ru/openapi/reports#tag/paidStorage) 6. [Продажах по регионам](https://dev.wildberries.ru/openapi/reports#tag/salesByRegions) 7. [Доле бренда в продажах](https://dev.wildberries.ru/openapi/reports#tag/shareOfBrandInSales) 8. [Заблокированных карточках](https://dev.wildberries.ru/openapi/reports#tag/blockedItems) 9. [Возвратах и перемещении товаров](https://dev.wildberries.ru/openapi/reports#tag/returnsAndItemMovementReport)

API version: reports
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
)

// checks if the GetV1AnalyticsBannedProducsBlockedResponse400 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetV1AnalyticsBannedProducsBlockedResponse400{}

// GetV1AnalyticsBannedProducsBlockedResponse400 struct for GetV1AnalyticsBannedProducsBlockedResponse400
type GetV1AnalyticsBannedProducsBlockedResponse400 struct {
	// Заголовок ошибки
	Title *string `json:"title,omitempty"`
	// HTTP статус-код
	Status *float32 `json:"status,omitempty"`
	// Детали ошибки
	Detail *string `json:"detail,omitempty"`
	// Уникальный ID запроса
	RequestId *string `json:"requestId,omitempty"`
	// ID внутреннего сервиса WB
	Origin *string `json:"origin,omitempty"`
}

// NewGetV1AnalyticsBannedProducsBlockedResponse400 instantiates a new GetV1AnalyticsBannedProducsBlockedResponse400 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetV1AnalyticsBannedProducsBlockedResponse400() *GetV1AnalyticsBannedProducsBlockedResponse400 {
	this := GetV1AnalyticsBannedProducsBlockedResponse400{}
	return &this
}

// NewGetV1AnalyticsBannedProducsBlockedResponse400WithDefaults instantiates a new GetV1AnalyticsBannedProducsBlockedResponse400 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetV1AnalyticsBannedProducsBlockedResponse400WithDefaults() *GetV1AnalyticsBannedProducsBlockedResponse400 {
	this := GetV1AnalyticsBannedProducsBlockedResponse400{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) SetTitle(v string) {
	o.Title = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetStatus() float32 {
	if o == nil || IsNil(o.Status) {
		var ret float32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetStatusOk() (*float32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given float32 and assigns it to the Status field.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) SetStatus(v float32) {
	o.Status = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) SetDetail(v string) {
	o.Detail = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) SetRequestId(v string) {
	o.RequestId = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *GetV1AnalyticsBannedProducsBlockedResponse400) SetOrigin(v string) {
	o.Origin = &v
}

func (o GetV1AnalyticsBannedProducsBlockedResponse400) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetV1AnalyticsBannedProducsBlockedResponse400) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	return toSerialize, nil
}

type NullableGetV1AnalyticsBannedProducsBlockedResponse400 struct {
	value *GetV1AnalyticsBannedProducsBlockedResponse400
	isSet bool
}

func (v NullableGetV1AnalyticsBannedProducsBlockedResponse400) Get() *GetV1AnalyticsBannedProducsBlockedResponse400 {
	return v.value
}

func (v *NullableGetV1AnalyticsBannedProducsBlockedResponse400) Set(val *GetV1AnalyticsBannedProducsBlockedResponse400) {
	v.value = val
	v.isSet = true
}

func (v NullableGetV1AnalyticsBannedProducsBlockedResponse400) IsSet() bool {
	return v.isSet
}

func (v *NullableGetV1AnalyticsBannedProducsBlockedResponse400) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetV1AnalyticsBannedProducsBlockedResponse400(val *GetV1AnalyticsBannedProducsBlockedResponse400) *NullableGetV1AnalyticsBannedProducsBlockedResponse400 {
	return &NullableGetV1AnalyticsBannedProducsBlockedResponse400{value: val, isSet: true}
}

func (v NullableGetV1AnalyticsBannedProducsBlockedResponse400) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetV1AnalyticsBannedProducsBlockedResponse400) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


