/*
Работа с товарами

С помощью методов этого раздела вы можете: - [создавать](https://dev.wildberries.ru/openapi/item-management#tag/listingItems) и [редактировать](https://dev.wildberries.ru/openapi/item-management#tag/listings) карточки товаров - получать [категории, предметы, характеристики и бренды товаров](https://dev.wildberries.ru/openapi/item-management#tag/categoriesSubcategoriesAndCharacteristics) - загружать [медиафайлы](https://dev.wildberries.ru/openapi/item-management#tag/mediaFiles) в карточки товаров - настраивать [ярлыки](https://dev.wildberries.ru/openapi/item-management#tag/labels) для поиска товаров - работать с [рекомендациями](https://dev.wildberries.ru/openapi/item-management#tag/recommendations) для товаров - устанавливать [цены и скидки](https://dev.wildberries.ru/openapi/item-management#tag/pricesAndDiscounts) - управлять [остатками товаров](https://dev.wildberries.ru/openapi/item-management#tag/sellerWarehousesInventory) и [складами](https://dev.wildberries.ru/openapi/item-management#tag/sellerWarehouses), если вы работаете по модели продаж со склада продавца Вы можете протестировать методы работы с товарами в [песочнице](https://dev.wildberries.ru/sandbox). Также в песочнице доступны [специальные методы](https://dev.wildberries.ru/docs/openapi-other/sandbox-environment#tag/itemManagement) для управления карточками товаров  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami) по **работе с товарами**

API version: items
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package items

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetV2DirectoryTnvedAllResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetV2DirectoryTnvedAllResponse200{}

// GetV2DirectoryTnvedAllResponse200 struct for GetV2DirectoryTnvedAllResponse200
type GetV2DirectoryTnvedAllResponse200 struct {
	// Данные
	Data []GetV2DirectoryTnvedAllResponse200DataInner `json:"data"`
	// Флаг наличия ошибки
	Error bool `json:"error"`
	// Текст ошибки
	ErrorText string `json:"errorText"`
	// Дополнительные ошибки
	AdditionalErrors NullableString `json:"additionalErrors"`
}

type _GetV2DirectoryTnvedAllResponse200 GetV2DirectoryTnvedAllResponse200

// NewGetV2DirectoryTnvedAllResponse200 instantiates a new GetV2DirectoryTnvedAllResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetV2DirectoryTnvedAllResponse200(data []GetV2DirectoryTnvedAllResponse200DataInner, error_ bool, errorText string, additionalErrors NullableString) *GetV2DirectoryTnvedAllResponse200 {
	this := GetV2DirectoryTnvedAllResponse200{}
	this.Data = data
	this.Error = error_
	this.ErrorText = errorText
	this.AdditionalErrors = additionalErrors
	return &this
}

// NewGetV2DirectoryTnvedAllResponse200WithDefaults instantiates a new GetV2DirectoryTnvedAllResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetV2DirectoryTnvedAllResponse200WithDefaults() *GetV2DirectoryTnvedAllResponse200 {
	this := GetV2DirectoryTnvedAllResponse200{}
	return &this
}

// GetData returns the Data field value
func (o *GetV2DirectoryTnvedAllResponse200) GetData() []GetV2DirectoryTnvedAllResponse200DataInner {
	if o == nil {
		var ret []GetV2DirectoryTnvedAllResponse200DataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetV2DirectoryTnvedAllResponse200) GetDataOk() ([]GetV2DirectoryTnvedAllResponse200DataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetV2DirectoryTnvedAllResponse200) SetData(v []GetV2DirectoryTnvedAllResponse200DataInner) {
	o.Data = v
}

// GetError returns the Error field value
func (o *GetV2DirectoryTnvedAllResponse200) GetError() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *GetV2DirectoryTnvedAllResponse200) GetErrorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *GetV2DirectoryTnvedAllResponse200) SetError(v bool) {
	o.Error = v
}

// GetErrorText returns the ErrorText field value
func (o *GetV2DirectoryTnvedAllResponse200) GetErrorText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorText
}

// GetErrorTextOk returns a tuple with the ErrorText field value
// and a boolean to check if the value has been set.
func (o *GetV2DirectoryTnvedAllResponse200) GetErrorTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorText, true
}

// SetErrorText sets field value
func (o *GetV2DirectoryTnvedAllResponse200) SetErrorText(v string) {
	o.ErrorText = v
}

// GetAdditionalErrors returns the AdditionalErrors field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetV2DirectoryTnvedAllResponse200) GetAdditionalErrors() string {
	if o == nil || o.AdditionalErrors.Get() == nil {
		var ret string
		return ret
	}

	return *o.AdditionalErrors.Get()
}

// GetAdditionalErrorsOk returns a tuple with the AdditionalErrors field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetV2DirectoryTnvedAllResponse200) GetAdditionalErrorsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdditionalErrors.Get(), o.AdditionalErrors.IsSet()
}

// SetAdditionalErrors sets field value
func (o *GetV2DirectoryTnvedAllResponse200) SetAdditionalErrors(v string) {
	o.AdditionalErrors.Set(&v)
}

func (o GetV2DirectoryTnvedAllResponse200) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetV2DirectoryTnvedAllResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["error"] = o.Error
	toSerialize["errorText"] = o.ErrorText
	toSerialize["additionalErrors"] = o.AdditionalErrors.Get()
	return toSerialize, nil
}

func (o *GetV2DirectoryTnvedAllResponse200) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"error",
		"errorText",
		"additionalErrors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetV2DirectoryTnvedAllResponse200 := _GetV2DirectoryTnvedAllResponse200{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetV2DirectoryTnvedAllResponse200)

	if err != nil {
		return err
	}

	*o = GetV2DirectoryTnvedAllResponse200(varGetV2DirectoryTnvedAllResponse200)

	return err
}

type NullableGetV2DirectoryTnvedAllResponse200 struct {
	value *GetV2DirectoryTnvedAllResponse200
	isSet bool
}

func (v NullableGetV2DirectoryTnvedAllResponse200) Get() *GetV2DirectoryTnvedAllResponse200 {
	return v.value
}

func (v *NullableGetV2DirectoryTnvedAllResponse200) Set(val *GetV2DirectoryTnvedAllResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableGetV2DirectoryTnvedAllResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableGetV2DirectoryTnvedAllResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetV2DirectoryTnvedAllResponse200(val *GetV2DirectoryTnvedAllResponse200) *NullableGetV2DirectoryTnvedAllResponse200 {
	return &NullableGetV2DirectoryTnvedAllResponse200{value: val, isSet: true}
}

func (v NullableGetV2DirectoryTnvedAllResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetV2DirectoryTnvedAllResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
