/*
 * Общение с покупателями
 * Узнать больше об общении с покупателями можно в [справочном центре](https://seller.wildberries.ru/instructions/category/f7f6c465-dd12-422d-80a0-a6d9562115d5?goBackOption=prevRoute&categoryId=30817062-14cc-4a82-bc78-3600c2b0685b)С помощью методов общения с покупателями вы можете работать с: 1. [Вопросами](/openapi/customer-communication#tag/questions) и [отзывами](/openapi/customer-communication#tag/feedbacks) покупателей 2. [Закреплёнными отзывами](/openapi/customer-communication#tag/pinnedFeedbacks) 3. [Чатами с покупателями](/openapi/customer-communication#tag/buyersChat) 4. [Заявками покупателей на возврат](/openapi/customer-communication#tag/buyersReturns) Вы можете протестировать методы общения с покупателями в [песочнице](/sandbox). Также в песочнице доступны [специальные методы](/docs/openapi-other/sandbox-environment#tag/questionsAndFeedbacks) для управления тестовыми вопросами и отзывамиУзнать, как использовать методы в бизнес-кейсах, можно в [инструкции](/knowledge-base/articles/019d49a4-0b26-7620-8d0b-e3050b7cd01d/obshchenie-s-pokupateliami) по работе с разделом **Общение с покупателями**
 *
 * The version of the OpenAPI document: communication
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.valeryverkhoturov.wbapi.communications.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.valeryverkhoturov.wbapi.communications.model.Event;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.valeryverkhoturov.wbapi.communications.JSON;

/**
 * EventsResult
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class EventsResult {
  public static final String SERIALIZED_NAME_NEXT = "next";
  @SerializedName(SERIALIZED_NAME_NEXT)
  @jakarta.annotation.Nullable
  private Integer next;

  public static final String SERIALIZED_NAME_NEWEST_EVENT_TIME = "newestEventTime";
  @SerializedName(SERIALIZED_NAME_NEWEST_EVENT_TIME)
  @jakarta.annotation.Nullable
  private OffsetDateTime newestEventTime;

  public static final String SERIALIZED_NAME_OLDEST_EVENT_TIME = "oldestEventTime";
  @SerializedName(SERIALIZED_NAME_OLDEST_EVENT_TIME)
  @jakarta.annotation.Nullable
  private OffsetDateTime oldestEventTime;

  public static final String SERIALIZED_NAME_TOTAL_EVENTS = "totalEvents";
  @SerializedName(SERIALIZED_NAME_TOTAL_EVENTS)
  @jakarta.annotation.Nullable
  private Integer totalEvents;

  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  @jakarta.annotation.Nullable
  private List<Event> events = new ArrayList<>();

  public EventsResult() {
  }

  public EventsResult next(@jakarta.annotation.Nullable Integer next) {
    this.next = next;
    return this;
  }

  /**
   * Пагинатор. Значение поля необходимо указать в запросе для получения следующего пакета данных
   * @return next
   */
  @jakarta.annotation.Nullable
  public Integer getNext() {
    return next;
  }

  public void setNext(@jakarta.annotation.Nullable Integer next) {
    this.next = next;
  }


  public EventsResult newestEventTime(@jakarta.annotation.Nullable OffsetDateTime newestEventTime) {
    this.newestEventTime = newestEventTime;
    return this;
  }

  /**
   * Время новейшего события в ответе
   * @return newestEventTime
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getNewestEventTime() {
    return newestEventTime;
  }

  public void setNewestEventTime(@jakarta.annotation.Nullable OffsetDateTime newestEventTime) {
    this.newestEventTime = newestEventTime;
  }


  public EventsResult oldestEventTime(@jakarta.annotation.Nullable OffsetDateTime oldestEventTime) {
    this.oldestEventTime = oldestEventTime;
    return this;
  }

  /**
   * Время старейшего события в ответе
   * @return oldestEventTime
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getOldestEventTime() {
    return oldestEventTime;
  }

  public void setOldestEventTime(@jakarta.annotation.Nullable OffsetDateTime oldestEventTime) {
    this.oldestEventTime = oldestEventTime;
  }


  public EventsResult totalEvents(@jakarta.annotation.Nullable Integer totalEvents) {
    this.totalEvents = totalEvents;
    return this;
  }

  /**
   * Количество событий
   * @return totalEvents
   */
  @jakarta.annotation.Nullable
  public Integer getTotalEvents() {
    return totalEvents;
  }

  public void setTotalEvents(@jakarta.annotation.Nullable Integer totalEvents) {
    this.totalEvents = totalEvents;
  }


  public EventsResult events(@jakarta.annotation.Nullable List<Event> events) {
    this.events = events;
    return this;
  }

  public EventsResult addEventsItem(Event eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Get events
   * @return events
   */
  @jakarta.annotation.Nullable
  public List<Event> getEvents() {
    return events;
  }

  public void setEvents(@jakarta.annotation.Nullable List<Event> events) {
    this.events = events;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventsResult eventsResult = (EventsResult) o;
    return Objects.equals(this.next, eventsResult.next) &&
        Objects.equals(this.newestEventTime, eventsResult.newestEventTime) &&
        Objects.equals(this.oldestEventTime, eventsResult.oldestEventTime) &&
        Objects.equals(this.totalEvents, eventsResult.totalEvents) &&
        Objects.equals(this.events, eventsResult.events);
  }

  @Override
  public int hashCode() {
    return Objects.hash(next, newestEventTime, oldestEventTime, totalEvents, events);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventsResult {\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    newestEventTime: ").append(toIndentedString(newestEventTime)).append("\n");
    sb.append("    oldestEventTime: ").append(toIndentedString(oldestEventTime)).append("\n");
    sb.append("    totalEvents: ").append(toIndentedString(totalEvents)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("next");
    openapiFields.add("newestEventTime");
    openapiFields.add("oldestEventTime");
    openapiFields.add("totalEvents");
    openapiFields.add("events");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EventsResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EventsResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EventsResult is not found in the empty JSON string", EventsResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EventsResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EventsResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("events") != null && !jsonObj.get("events").isJsonNull()) {
        JsonArray jsonArrayevents = jsonObj.getAsJsonArray("events");
        if (jsonArrayevents != null) {
          // ensure the json data is an array
          if (!jsonObj.get("events").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `events` to be an array in the JSON string but got `%s`", jsonObj.get("events").toString()));
          }

          // validate the optional field `events` (array)
          for (int i = 0; i < jsonArrayevents.size(); i++) {
            Event.validateJsonElement(jsonArrayevents.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventsResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventsResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventsResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventsResult.class));

       return (TypeAdapter<T>) new TypeAdapter<EventsResult>() {
           @Override
           public void write(JsonWriter out, EventsResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EventsResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EventsResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EventsResult
   * @throws IOException if the JSON string is invalid with respect to EventsResult
   */
  public static EventsResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventsResult.class);
  }

  /**
   * Convert an instance of EventsResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

