/*
 * Аналитика и данные
 *
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ValeryVerkhoturov.WbApiClient.Analytics.Client.OpenAPIDateConverter;

namespace ValeryVerkhoturov.WbApiClient.Analytics.Model
{
    /// <summary>
    /// Текущие остатки товаров на складах продавца
    /// </summary>
    [DataContract(Name = "InventorySellerResponse")]
    public partial class InventorySellerResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InventorySellerResponse" /> class.
        /// </summary>
        /// <param name="items">Остатки товаров на складах продавца по размерам.</param>
        public InventorySellerResponse(List<InventorySellerResponseItemsInner> items = default(List<InventorySellerResponseItemsInner>))
        {
            this.Items = items;
        }

        /// <summary>
        /// Остатки товаров на складах продавца по размерам
        /// </summary>
        /// <value>Остатки товаров на складах продавца по размерам</value>
        [DataMember(Name = "items", EmitDefaultValue = false)]
        public List<InventorySellerResponseItemsInner> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InventorySellerResponse {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
