/*
 * Аналитика и данные
 *
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ValeryVerkhoturov.WbApiClient.Analytics.Client.OpenAPIDateConverter;

namespace ValeryVerkhoturov.WbApiClient.Analytics.Model
{
    /// <summary>
    /// Медианная позиция товара в результатах поиска
    /// </summary>
    [DataContract(Name = "PositionInfo_median")]
    public partial class PositionInfoMedian : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PositionInfoMedian" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PositionInfoMedian() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PositionInfoMedian" /> class.
        /// </summary>
        /// <param name="current">Текущая медианная позиция товара (required).</param>
        /// <param name="dynamics">Динамика по сравнению с предыдущим периодом, %.</param>
        public PositionInfoMedian(int current = default(int), int dynamics = default(int))
        {
            this.Current = current;
            this.Dynamics = dynamics;
        }

        /// <summary>
        /// Текущая медианная позиция товара
        /// </summary>
        /// <value>Текущая медианная позиция товара</value>
        /*
        <example>5</example>
        */
        [DataMember(Name = "current", IsRequired = true, EmitDefaultValue = true)]
        public int Current { get; set; }

        /// <summary>
        /// Динамика по сравнению с предыдущим периодом, %
        /// </summary>
        /// <value>Динамика по сравнению с предыдущим периодом, %</value>
        /*
        <example>50</example>
        */
        [DataMember(Name = "dynamics", EmitDefaultValue = false)]
        public int Dynamics { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PositionInfoMedian {\n");
            sb.Append("  Current: ").Append(Current).Append("\n");
            sb.Append("  Dynamics: ").Append(Dynamics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
