/*
 * Аналитика и данные
 *
 * Узнать больше об аналитике и данных можно в [справочном центре](https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics)  В разделе описаны методы получения: 1. [Воронки продаж](https://dev.wildberries.ru/openapi/analytics#tag/salesFunnel) 2. [Ленты заказов](https://dev.wildberries.ru/openapi/analytics#tag/orderFeed) 3. [Поисковых запросов по вашим товарам](https://dev.wildberries.ru/openapi/analytics#tag/searchQueriesForYourItems) 4. [Истории остатков](https://dev.wildberries.ru/openapi/analytics#tag/stocksReport) 5. [Оценки товара](https://dev.wildberries.ru/openapi/analytics#tag/itemRating) 6. [Аналитики продавца в формате CSV](https://dev.wildberries.ru/openapi/analytics#tag/sellerAnalyticsCsv)
 *
 * The version of the OpenAPI document: analytics
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ValeryVerkhoturov.WbApiClient.Analytics.Client.OpenAPIDateConverter;

namespace ValeryVerkhoturov.WbApiClient.Analytics.Model
{
    /// <summary>
    /// Параметры отчёта
    /// </summary>
    [DataContract(Name = "SearchReportTextReq_params")]
    public partial class SearchReportTextReqParams : IValidatableObject
    {
        /// <summary>
        /// Фильтрация по поисковым запросам, по которым больше всего:   - &#x60;openCard&#x60; — перешли в карточку   - &#x60;addToCart&#x60; — добавили в корзину   - &#x60;openToCart&#x60; — конверсия в корзину   - &#x60;orders&#x60; — заказали товаров   - &#x60;cartToOrder&#x60; — конверсия в заказ 
        /// </summary>
        /// <value>Фильтрация по поисковым запросам, по которым больше всего:   - &#x60;openCard&#x60; — перешли в карточку   - &#x60;addToCart&#x60; — добавили в корзину   - &#x60;openToCart&#x60; — конверсия в корзину   - &#x60;orders&#x60; — заказали товаров   - &#x60;cartToOrder&#x60; — конверсия в заказ </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TopOrderByEnum
        {
            /// <summary>
            /// Enum OpenCard for value: openCard
            /// </summary>
            [EnumMember(Value = "openCard")]
            OpenCard = 1,

            /// <summary>
            /// Enum AddToCart for value: addToCart
            /// </summary>
            [EnumMember(Value = "addToCart")]
            AddToCart = 2,

            /// <summary>
            /// Enum OpenToCart for value: openToCart
            /// </summary>
            [EnumMember(Value = "openToCart")]
            OpenToCart = 3,

            /// <summary>
            /// Enum Orders for value: orders
            /// </summary>
            [EnumMember(Value = "orders")]
            Orders = 4,

            /// <summary>
            /// Enum CartToOrder for value: cartToOrder
            /// </summary>
            [EnumMember(Value = "cartToOrder")]
            CartToOrder = 5
        }


        /// <summary>
        /// Фильтрация по поисковым запросам, по которым больше всего:   - &#x60;openCard&#x60; — перешли в карточку   - &#x60;addToCart&#x60; — добавили в корзину   - &#x60;openToCart&#x60; — конверсия в корзину   - &#x60;orders&#x60; — заказали товаров   - &#x60;cartToOrder&#x60; — конверсия в заказ 
        /// </summary>
        /// <value>Фильтрация по поисковым запросам, по которым больше всего:   - &#x60;openCard&#x60; — перешли в карточку   - &#x60;addToCart&#x60; — добавили в корзину   - &#x60;openToCart&#x60; — конверсия в корзину   - &#x60;orders&#x60; — заказали товаров   - &#x60;cartToOrder&#x60; — конверсия в заказ </value>
        /*
        <example>openToCart</example>
        */
        [DataMember(Name = "topOrderBy", IsRequired = true, EmitDefaultValue = true)]
        public TopOrderByEnum TopOrderBy { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchReportTextReqParams" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchReportTextReqParams() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchReportTextReqParams" /> class.
        /// </summary>
        /// <param name="currentPeriod">currentPeriod (required).</param>
        /// <param name="pastPeriod">pastPeriod.</param>
        /// <param name="nmIds">Артикулы WB, по которым составить отчёт. Оставьте пустым, чтобы получить отчёт по всем товарам .</param>
        /// <param name="subjectIds">Список ID предметов для фильтрации.</param>
        /// <param name="brandNames">Список брендов для фильтрации.</param>
        /// <param name="tagIds">Список ID ярлыков для фильтрации.</param>
        /// <param name="topOrderBy">Фильтрация по поисковым запросам, по которым больше всего:   - &#x60;openCard&#x60; — перешли в карточку   - &#x60;addToCart&#x60; — добавили в корзину   - &#x60;openToCart&#x60; — конверсия в корзину   - &#x60;orders&#x60; — заказали товаров   - &#x60;cartToOrder&#x60; — конверсия в заказ  (required).</param>
        /// <param name="orderBy">orderBy (required).</param>
        /// <param name="includeSubstitutedSKUs">Показать данные по прямым запросам с [подменным артикулом](https://seller.wildberries.ru/help-center/article/A-524) (default to true).</param>
        /// <param name="includeSearchTexts">Показать данные по поисковым запросам без учёта подменного артикула (default to true).</param>
        /// <param name="limit">limit (required).</param>
        public SearchReportTextReqParams(Period currentPeriod = default(Period), PastPeriod pastPeriod = default(PastPeriod), List<string> nmIds = default(List<string>), List<int> subjectIds = default(List<int>), List<string> brandNames = default(List<string>), List<long> tagIds = default(List<long>), TopOrderByEnum topOrderBy = default(TopOrderByEnum), OrderByGrTe orderBy = default(OrderByGrTe), bool includeSubstitutedSKUs = true, bool includeSearchTexts = true, TextLimit limit = default(TextLimit))
        {
            // to ensure "currentPeriod" is required (not null)
            if (currentPeriod == null)
            {
                throw new ArgumentNullException("currentPeriod is a required property for SearchReportTextReqParams and cannot be null");
            }
            this.CurrentPeriod = currentPeriod;
            this.TopOrderBy = topOrderBy;
            // to ensure "orderBy" is required (not null)
            if (orderBy == null)
            {
                throw new ArgumentNullException("orderBy is a required property for SearchReportTextReqParams and cannot be null");
            }
            this.OrderBy = orderBy;
            // to ensure "limit" is required (not null)
            if (limit == null)
            {
                throw new ArgumentNullException("limit is a required property for SearchReportTextReqParams and cannot be null");
            }
            this.Limit = limit;
            this.PastPeriod = pastPeriod;
            this.NmIds = nmIds;
            this.SubjectIds = subjectIds;
            this.BrandNames = brandNames;
            this.TagIds = tagIds;
            this.IncludeSubstitutedSKUs = includeSubstitutedSKUs;
            this.IncludeSearchTexts = includeSearchTexts;
        }

        /// <summary>
        /// Gets or Sets CurrentPeriod
        /// </summary>
        [DataMember(Name = "currentPeriod", IsRequired = true, EmitDefaultValue = true)]
        public Period CurrentPeriod { get; set; }

        /// <summary>
        /// Gets or Sets PastPeriod
        /// </summary>
        [DataMember(Name = "pastPeriod", EmitDefaultValue = false)]
        public PastPeriod PastPeriod { get; set; }

        /// <summary>
        /// Артикулы WB, по которым составить отчёт. Оставьте пустым, чтобы получить отчёт по всем товарам 
        /// </summary>
        /// <value>Артикулы WB, по которым составить отчёт. Оставьте пустым, чтобы получить отчёт по всем товарам </value>
        [DataMember(Name = "nmIds", EmitDefaultValue = false)]
        public List<string> NmIds { get; set; }

        /// <summary>
        /// Список ID предметов для фильтрации
        /// </summary>
        /// <value>Список ID предметов для фильтрации</value>
        /*
        <example>[64,334]</example>
        */
        [DataMember(Name = "subjectIds", EmitDefaultValue = false)]
        public List<int> SubjectIds { get; set; }

        /// <summary>
        /// Список брендов для фильтрации
        /// </summary>
        /// <value>Список брендов для фильтрации</value>
        /*
        <example>[&quot;nike&quot;,&quot;adidas&quot;]</example>
        */
        [DataMember(Name = "brandNames", EmitDefaultValue = false)]
        public List<string> BrandNames { get; set; }

        /// <summary>
        /// Список ID ярлыков для фильтрации
        /// </summary>
        /// <value>Список ID ярлыков для фильтрации</value>
        /*
        <example>[32,53]</example>
        */
        [DataMember(Name = "tagIds", EmitDefaultValue = false)]
        public List<long> TagIds { get; set; }

        /// <summary>
        /// Gets or Sets OrderBy
        /// </summary>
        [DataMember(Name = "orderBy", IsRequired = true, EmitDefaultValue = true)]
        public OrderByGrTe OrderBy { get; set; }

        /// <summary>
        /// Показать данные по прямым запросам с [подменным артикулом](https://seller.wildberries.ru/help-center/article/A-524)
        /// </summary>
        /// <value>Показать данные по прямым запросам с [подменным артикулом](https://seller.wildberries.ru/help-center/article/A-524)</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "includeSubstitutedSKUs", EmitDefaultValue = true)]
        public bool IncludeSubstitutedSKUs { get; set; }

        /// <summary>
        /// Показать данные по поисковым запросам без учёта подменного артикула
        /// </summary>
        /// <value>Показать данные по поисковым запросам без учёта подменного артикула</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "includeSearchTexts", EmitDefaultValue = true)]
        public bool IncludeSearchTexts { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public TextLimit Limit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchReportTextReqParams {\n");
            sb.Append("  CurrentPeriod: ").Append(CurrentPeriod).Append("\n");
            sb.Append("  PastPeriod: ").Append(PastPeriod).Append("\n");
            sb.Append("  NmIds: ").Append(NmIds).Append("\n");
            sb.Append("  SubjectIds: ").Append(SubjectIds).Append("\n");
            sb.Append("  BrandNames: ").Append(BrandNames).Append("\n");
            sb.Append("  TagIds: ").Append(TagIds).Append("\n");
            sb.Append("  TopOrderBy: ").Append(TopOrderBy).Append("\n");
            sb.Append("  OrderBy: ").Append(OrderBy).Append("\n");
            sb.Append("  IncludeSubstitutedSKUs: ").Append(IncludeSubstitutedSKUs).Append("\n");
            sb.Append("  IncludeSearchTexts: ").Append(IncludeSearchTexts).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
