/*
 * Заказы DBW
 *
 * С помощью методов Заказы DBW (Деливери WB) вы можете: - получать информацию о [сборочных заданиях](https://dev.wildberries.ru/openapi/orders-dbw#tag/dbwAssemblyOrders), управлять статусами и отменять сборочные задания - получать, добавлять, редактировать и удалять [метаданные](https://dev.wildberries.ru/openapi/orders-dbw#tag/dbwLabelIdentifiers) сборочных заданий  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-036a-7721-98e8-bed5f1a4f72d/zakazy-dbw) по работе с **заказами DBW**
 *
 * The version of the OpenAPI document: ordersdbw
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ValeryVerkhoturov.WbApiClient.OrdersDbw.Client.OpenAPIDateConverter;

namespace ValeryVerkhoturov.WbApiClient.OrdersDbw.Model
{
    /// <summary>
    /// PutV3DbwOrdersOrderIdMetaGtinRequest
    /// </summary>
    [DataContract(Name = "putV3DbwOrdersOrderIdMetaGtin_request")]
    public partial class PutV3DbwOrdersOrderIdMetaGtinRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PutV3DbwOrdersOrderIdMetaGtinRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PutV3DbwOrdersOrderIdMetaGtinRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PutV3DbwOrdersOrderIdMetaGtinRequest" /> class.
        /// </summary>
        /// <param name="gtin">GTIN (required).</param>
        public PutV3DbwOrdersOrderIdMetaGtinRequest(string gtin = default(string))
        {
            // to ensure "gtin" is required (not null)
            if (gtin == null)
            {
                throw new ArgumentNullException("gtin is a required property for PutV3DbwOrdersOrderIdMetaGtinRequest and cannot be null");
            }
            this.Gtin = gtin;
        }

        /// <summary>
        /// GTIN
        /// </summary>
        /// <value>GTIN</value>
        /*
        <example>1234567890123</example>
        */
        [DataMember(Name = "gtin", IsRequired = true, EmitDefaultValue = true)]
        public string Gtin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PutV3DbwOrdersOrderIdMetaGtinRequest {\n");
            sb.Append("  Gtin: ").Append(Gtin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Gtin (string) maxLength
            if (this.Gtin != null && this.Gtin.Length > 13)
            {
                yield return new ValidationResult("Invalid value for Gtin, length must be less than 13.", new[] { "Gtin" });
            }

            // Gtin (string) minLength
            if (this.Gtin != null && this.Gtin.Length < 13)
            {
                yield return new ValidationResult("Invalid value for Gtin, length must be greater than 13.", new[] { "Gtin" });
            }

            yield break;
        }
    }

}
