/*
 * Заказы DBW
 *
 * С помощью методов Заказы DBW (Деливери WB) вы можете: - получать информацию о [сборочных заданиях](https://dev.wildberries.ru/openapi/orders-dbw#tag/dbwAssemblyOrders), управлять статусами и отменять сборочные задания - получать, добавлять, редактировать и удалять [метаданные](https://dev.wildberries.ru/openapi/orders-dbw#tag/dbwLabelIdentifiers) сборочных заданий  Узнать, как использовать методы в бизнес-кейсах, можно в [инструкции](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-036a-7721-98e8-bed5f1a4f72d/zakazy-dbw) по работе с **заказами DBW**
 *
 * The version of the OpenAPI document: ordersdbw
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ValeryVerkhoturov.WbApiClient.OrdersDbw.Client.OpenAPIDateConverter;

namespace ValeryVerkhoturov.WbApiClient.OrdersDbw.Model
{
    /// <summary>
    /// PutV3DbwOrdersOrderIdMetaUinRequest
    /// </summary>
    [DataContract(Name = "putV3DbwOrdersOrderIdMetaUin_request")]
    public partial class PutV3DbwOrdersOrderIdMetaUinRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PutV3DbwOrdersOrderIdMetaUinRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PutV3DbwOrdersOrderIdMetaUinRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PutV3DbwOrdersOrderIdMetaUinRequest" /> class.
        /// </summary>
        /// <param name="uin">УИН (required).</param>
        public PutV3DbwOrdersOrderIdMetaUinRequest(string uin = default(string))
        {
            // to ensure "uin" is required (not null)
            if (uin == null)
            {
                throw new ArgumentNullException("uin is a required property for PutV3DbwOrdersOrderIdMetaUinRequest and cannot be null");
            }
            this.Uin = uin;
        }

        /// <summary>
        /// УИН
        /// </summary>
        /// <value>УИН</value>
        /*
        <example>1234567890123456</example>
        */
        [DataMember(Name = "uin", IsRequired = true, EmitDefaultValue = true)]
        public string Uin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PutV3DbwOrdersOrderIdMetaUinRequest {\n");
            sb.Append("  Uin: ").Append(Uin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Uin (string) maxLength
            if (this.Uin != null && this.Uin.Length > 16)
            {
                yield return new ValidationResult("Invalid value for Uin, length must be less than 16.", new[] { "Uin" });
            }

            // Uin (string) minLength
            if (this.Uin != null && this.Uin.Length < 16)
            {
                yield return new ValidationResult("Invalid value for Uin, length must be greater than 16.", new[] { "Uin" });
            }

            yield break;
        }
    }

}
